### ISSUE TITLE
sing-tun crash

### ISSUE THREAD

**Issue by adiprasetya** [SagerNet/sing-box#1097]
### Operating system

Android

### System version

11

### Installation type

Original sing-box Command Line

### Version

<details>

```console
sing-box version 1.7.0-alpha.11

Environment: go1.21.3 android/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_clash_api
Revision: 567d4f3db5ea69c8e80157b9ed241e57633782ad
CGO: enabled
```
</details>

### Description

sing-tun crashing, don't know why. it suddenly crashed like that. is it killed by system?

never like this before 1.7.0-alpha11.

### Reproduction

running it normally, using this command line.
```sh
sudo sing-box -C ... run
```
and using this tun configuration.
```json
{
  "log": {
    "disabled": false,
    "level": "error",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "tun",
      "interface_name": "tun0",
      "inet4_address": "172.19.0.1/30",
      "mtu": 1384,
      "auto_route": true,
      "strict_route": false,
      "sniff": true,
      "stack": "system",
      "inet4_route_address": [
        "0.0.0.0/1",
        "128.0.0.0/1"
      ],
      "inet4_route_exclude_address": [
        "192.168.0.0/16"
      ]
    }
  ],
  "route": {
    "auto_detect_interface": true
   }
}
```

### Logs

<details>

```console
panic: runtime error: slice bounds out of range [:1472] with capacity 1364

goroutine 14 [running]:
github.com/sagernet/sing-tun/internal/clashtcpip.UDPPacket.Payload(...)
	pkg/mod/github.com/sagernet/sing-tun@v0.1.20-0.20231107141025-be3aecff893d/internal/clashtcpip/udp.go:36
github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40001ea160, {0x400022a000, 0x564, 0x568}, {0x400022a014, 0x550, 0x554})
	pkg/mod/github.com/sagernet/sing-tun@v0.1.20-0.20231107141025-be3aecff893d/stack_system.go:334 +0x4b0
github.com/sagernet/sing-tun.(*System).processIPv4(0x40001ea160, {0x400022a000, 0x564, 0x568})
	pkg/mod/github.com/sagernet/sing-tun@v0.1.20-0.20231107141025-be3aecff893d/stack_system.go:246 +0x200
github.com/sagernet/sing-tun.(*System).tunLoop(0x40001ea160)
	pkg/mod/github.com/sagernet/sing-tun@v0.1.20-0.20231107141025-be3aecff893d/stack_system.go:159 +0x1a4
created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
	pkg/mod/github.com/sagernet/sing-tun@v0.1.20-0.20231107141025-be3aecff893d/stack_system.go:100 +0x64

```
</details>

**Comment by nekohasekai** [comment]
Should be fixed in 1.6.4.
