### ISSUE TITLE
websocket, sing-dns crashed

### ISSUE THREAD

**Issue by adiprasetya** [SagerNet/sing-box#1106]
### Operating system

Android

### System version

11

### Installation type

Original sing-box Command Line

### Version

<details>

```console
sing-box version 1.7.0-alpha.11

Environment: go1.21.3 android/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_clash_api
Revision: 567d4f3db5ea69c8e80157b9ed241e57633782ad
CGO: enabled

```
</details>

### Description

Suddenly crashed when maybe my local DNS fails to resolve outbound DNS according to the rules.

### Reproduction

using the "local" dns server on android it seems to be working, even using pre-build in release. tested with other dns address, it's still crashing when my dns local failed to resolve.

dns configuration
```json
{
    "dns": {
    "servers": [
      {
        "tag": "default",
        "address": "8.8.8.8",
        "detour": "proxy"
      },
      {
        "tag": "local",
        "address": "local",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "local",
        "disable_cache": true
      }
    ],
    "strategy": "ipv4_only",
    "final": "default"
    }
}
```
outbound configuration
```json
{
    "outbounds": [
    {
      "type": "trojan",
      "tag": "proxy",
      "connect_timeout": "3s",
      "server": "example.com",
      "server_port": 443,
      "password": "some-unique-password",
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "utls": { "enabled": true }
      },
      "transport": {
        "type": "ws",
        "path": "/trojan",
        "headers": {
          "Host": "example.com"
        },
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    }
    ]
}

```

### Logs

<details>

```console
+0000 2023-11-12 16:45:44 ERROR [3663801824 10.0s] inbound/tun[0]: write request: lookup example.com: i/o timeout

panic: close of closed channel

goroutine 872 [running]:
github.com/sagernet/sing-box/transport/v2raywebsocket.(*EarlyWebsocketConn).Write(0x40005cae40, {0x40003583f5?, 0x2d, 0x63a0503dc0?})
	/Users/sekai/Projects/sing-box/transport/v2raywebsocket/conn.go:199 +0x120
github.com/sagernet/sing-box/transport/trojan.WritePacket({0x639fc30c18, 0x40005cae40}, 0x400042c5a0, {{{0x0, 0xffff08080808}, 0x400000e030}, 0x35, {0x0, 0x0}})
	/Users/sekai/Projects/sing-box/transport/trojan/protocol.go:307 +0x2e0
github.com/sagernet/sing-box/transport/trojan.(*ClientPacketConn).WritePacket(0x0?, 0x0?, {{{0x0, 0xffff08080808}, 0x400000e030}, 0x35, {0x0, 0x0}})
	/Users/sekai/Projects/sing-box/transport/trojan/protocol.go:120 +0x13c
github.com/sagernet/sing/common/bufio.WritePacketBuffer({0x7b198e11d0?, 0x400040ef00}, 0x400042c4b0, {{{0x0, 0xffff08080808}, 0x400000e030}, 0x35, {0x0, 0x0}})
	pkg/mod/github.com/sagernet/sing@v0.2.18-0.20231108041402-4fbbd193203c/common/bufio/io.go:85 +0x22c
github.com/sagernet/sing/common/bufio.WritePacket({0x639fc1e768, 0x400040ef00}, {0x40004a6060, 0x22, 0x23}, {0x639fc1b350, 0x40005970b0})
	pkg/mod/github.com/sagernet/sing@v0.2.18-0.20231108041402-4fbbd193203c/common/bufio/io.go:62 +0x10c
github.com/sagernet/sing-box/transport/trojan.(*ClientPacketConn).WriteTo(0x4000677818?, {0x40004a6060?, 0x0?, 0x639eed6384?}, {0x639fc1b350?, 0x40005970b0?})
	/Users/sekai/Projects/sing-box/transport/trojan/protocol.go:139 +0x48
github.com/sagernet/sing/common/bufio.(*BindPacketConn).Write(0x0?, {0x40004a6060?, 0x23?, 0x100000200000000?})
	pkg/mod/github.com/sagernet/sing@v0.2.18-0.20231108041402-4fbbd193203c/common/bufio/bind.go:29 +0x38
github.com/sagernet/sing-dns.(*UDPTransport).WriteMessage(0x4000782190?, {0x639fc2dd58, 0x4000782150}, 0x0?)
	pkg/mod/github.com/sagernet/sing-dns@v0.1.10/transport_udp.go:73 +0x6c
github.com/sagernet/sing-dns.(*myTransportAdapter).exchange(0x40004bcd80, {0x639fc256e8, 0x40002e62d0}, 0x40000b6630)
	pkg/mod/github.com/sagernet/sing-dns@v0.1.10/transport_base.go:144 +0x1c0
github.com/sagernet/sing-dns.(*myTransportAdapter).Exchange(0x639fa45140?, {0x639fc256e8, 0x40002e62d0}, 0x40000b6630)
	pkg/mod/github.com/sagernet/sing-dns@v0.1.10/transport_base.go:119 +0x7c
github.com/sagernet/sing-dns.(*Client).Exchange(0x400042d200, {0x639fc25790, 0x40000f4540}, {0x639fc2bb20, 0x40004bcd80}, 0x40000b6630, 0x3)
	pkg/mod/github.com/sagernet/sing-dns@v0.1.10/client.go:115 +0x668
github.com/sagernet/sing-box/route.(*Router).Exchange(0x40000db180, {0x639fc256e8, 0x40002e6270}, 0x40000b6630)
	/Users/sekai/Projects/sing-box/route/router_dns.go:102 +0x264
github.com/sagernet/sing-box/outbound.(*DNS).NewPacketConnection.func1.1()
	/Users/sekai/Projects/sing-box/outbound/dns.go:161 +0x98
created by github.com/sagernet/sing-box/outbound.(*DNS).NewPacketConnection.func1 in goroutine 871
	/Users/sekai/Projects/sing-box/outbound/dns.go:160 +0x80
```
</details>

**Comment by nekohasekai** [comment]
Should be fixed in 1.6.4.
