### ISSUE TITLE
rule_set中download_detour使用direct造成panic

### ISSUE THREAD

**Issue by TTT-TD** [SagerNet/sing-box#1167]
### 操作系统

Windows

### 系统版本

Windows 11 22H2 (22621.1105) x64

### 安装类型

sing-box 原始命令行程序

### 版本

<details>

```console
sing-box version 1.8.0-alpha.7

Environment: go1.21.1 windows/amd64
Tags: with_gvisor,with_clash_api,with_utls,with_quic,with_ech,with_reality_server,with_acme
Revision: 5f40f1d2411bde99f29e013621fdc08f784c7918
CGO: disabled
```
</details>

### 描述

1. rule_set中使用`"download_detour": "direct"`启动内核导致panic
2. rule_set中`download_detour`字段使用urltest或者默认为urltest的selector不会下载规则

### 重现方式

使用如下配置则出现panic: runtime error: invalid memory address or nil pointer dereference

<details>

```json
"route":{
    "auto_detect_interface":true,
    "rule_set":[
      {
        "type":"remote",
        "tag":"geoip-cn",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geoip/cn.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geoip-telegram",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geoip/telegram.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-cn",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/cn.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-telegram",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/telegram.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-microsoft",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/microsoft.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-tld-!cn",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/tld-!cn.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-youtube",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/youtube.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-category-ads-all",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/category-ads-all.srs",
        "download_detour":"direct",
        "format":"binary"
      },
      {
        "type":"remote",
        "tag":"geosite-openai",
        "url":"https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/openai.srs",
        "download_detour":"direct",
        "format":"binary"
      }
    ],
    "rules":[ 
   ....
```
</details>

### 日志

<details>

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x102b1b9]
goroutine 108 [running]:
github.com/sagernet/sing-box/transport/fakeip.(*Transport).Lookup(0xc00028f640, {0xc000316220?, 0x0?}, {0xc000090580, 0xa}, 0x3)
  github.com/sagernet/sing-box/transport/fakeip/server.go:75 +0x59
github.com/sagernet/sing-dns.(*Client).Lookup(0xc0002937a0, {0x165a4f8, 0xc00009c770}, {0x1661ff0?, 0xc00028f640}, {0xc000090580, 0xa}, 0x3)
  github.com/sagernet/sing-dns@v0.1.11/client.go:226 +0xb57
github.com/sagernet/sing-box/route.(*Router).Lookup(0xc0000338c0, {0x165a450, 0xc000315ad0}, {0xc000090580, 0xa}, 0x0)
  github.com/sagernet/sing-box/route/router_dns.go:134 +0x211
github.com/sagernet/sing-box/route.(*Router).LookupDefault(0x165a450?, {0x165a450?, 0xc000315ad0?}, {0xc000090580?, 0x118fbc0?})
  github.com/sagernet/sing-box/route/router_dns.go:147 +0x25
github.com/sagernet/sing-box/common/dialer.(*ResolveDialer).DialContext(0xc00028f700, {0x165a450, 0xc000315a40}, {0x14393fa, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc000090580, ...}})
  github.com/sagernet/sing-box/common/dialer/resolve.go:46 +0x1b4
github.com/sagernet/sing-box/outbound.(*Direct).DialContext(0xc0002a3ad0, {0x165a488?, 0xc00028c190?}, {0x14393fa, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc000090580, ...}})
  github.com/sagernet/sing-box/outbound/direct.go:92 +0x4e9
github.com/sagernet/sing-box/route.(*RuleSetStartContext).HTTPClient.func1({0x165a488, 0xc00028c190}, {0x14393fa, 0x3}, {0xc000090580?, 0x398bf4?})
  github.com/sagernet/sing-box/route/rule_set.go:53 +0xd9
net/http.(*Transport).dial(0x1?, {0x165a488?, 0xc00028c190?}, {0x14393fa?, 0x0?}, {0xc000090580?, 0x1?})
  net/http/transport.go:1183 +0xd2
net/http.(*Transport).dialConn(0xc0004e0500, {0x165a488, 0xc00028c190}, {{}, 0x0, {0xc00003f220, 0x5}, {0xc000090580, 0xe}, 0x0})
  net/http/transport.go:1625 +0x7e8
net/http.(*Transport).dialConnFor(0x0?, 0xc000358210)
  net/http/transport.go:1467 +0x9f
created by net/http.(*Transport).queueForDial in goroutine 104
  net/http/transport.go:1436 +0x3cb
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x102b1b9]

goroutine 55 [running]:
github.com/sagernet/sing-box/transport/fakeip.(*Transport).Lookup(0xc00028f640, {0xc0004941f0?, 0x0?}, {0xc0004062f0, 0xa}, 0x3)
  github.com/sagernet/sing-box/transport/fakeip/server.go:75 +0x59
github.com/sagernet/sing-dns.(*Client).Lookup(0xc0002937a0, {0x165a4f8, 0xc000486310}, {0x1661ff0?, 0xc00028f640}, {0xc0004062f0, 0xa}, 0x3)
  github.com/sagernet/sing-dns@v0.1.11/client.go:226 +0xb57
github.com/sagernet/sing-box/route.(*Router).Lookup(0xc0000338c0, {0x165a450, 0xc000414ae0}, {0xc0004062f0, 0xa}, 0x0)
  github.com/sagernet/sing-box/route/router_dns.go:134 +0x211
github.com/sagernet/sing-box/route.(*Router).LookupDefault(0x165a450?, {0x165a450?, 0xc000414ae0?}, {0xc0004062f0?, 0x118fbc0?})
  github.com/sagernet/sing-box/route/router_dns.go:147 +0x25
github.com/sagernet/sing-box/common/dialer.(*ResolveDialer).DialContext(0xc00028f700, {0x165a450, 0xc000414a50}, {0x14393fa, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc0004062f0, ...}})
  github.com/sagernet/sing-box/common/dialer/resolve.go:46 +0x1b4
github.com/sagernet/sing-box/outbound.(*Direct).DialContext(0xc0002a3ad0, {0x165a488?, 0xc00028c190?}, {0x14393fa, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc0004062f0, ...}})
  github.com/sagernet/sing-box/outbound/direct.go:92 +0x4e9
github.com/sagernet/sing-box/route.(*RuleSetStartContext).HTTPClient.func1({0x165a488, 0xc00028c190}, {0x14393fa, 0x3}, {0xc0004062f0?, 0x398bf4?})
  github.com/sagernet/sing-box/route/rule_set.go:53 +0xd9
net/http.(*Transport).dial(0x2f8f01?, {0x165a488?, 0xc00028c190?}, {0x14393fa?, 0x0?}, {0xc0004062f0?, 0x1?})
  net/http/transport.go:1183 +0xd2
net/http.(*Transport).dialConn(0xc0004e0500, {0x165a488, 0xc00028c190}, {{}, 0x0, {0xc00003ee60, 0x5}, {0xc0004062f0, 0xe}, 0x0})
  net/http/transport.go:1625 +0x7e8
net/http.(*Transport).dialConnFor(0x0?, 0xc0001451e0)
  net/http/transport.go:1467 +0x9f
created by net/http.(*Transport).queueForDial in goroutine 101
  net/http/transport.go:1436 +0x3cb
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x102b1b9]
goroutine 16 [running]:
github.com/sagernet/sing-box/transport/fakeip.(*Transport).Lookup(0xc00028f640, {0xc0002b2370?, 0x0?}, {0xc000494140, 0xa}, 0x3)
  github.com/sagernet/sing-box/transport/fakeip/server.go:75 +0x59
github.com/sagernet/sing-dns.(*Client).Lookup(0xc0002937a0, {0x165a4f8, 0xc000308540}, {0x1661ff0?, 0xc00028f640}, {0xc000494140, 0xa}, 0x3)
  github.com/sagernet/sing-dns@v0.1.11/client.go:226 +0xb57
github.com/sagernet/sing-box/route.(*Router).Lookup(0xc0000338c0, {0x165a450, 0xc0002faf90}, {0xc000494140, 0xa}, 0x0)
  github.com/sagernet/sing-box/route/router_dns.go:134 +0x211
github.com/sagernet/sing-box/route.(*Router).LookupDefault(0x165a450?, {0x165a450?, 0xc0002faf90?}, {0xc000494140?, 0x118fbc0?})
  github.com/sagernet/sing-box/route/router_dns.go:147 +0x25
github.com/sagernet/sing-box/common/dialer.(*ResolveDialer).DialContext(0xc00028f700, {0x165a450, 0xc0002faf00}, {0x14393fa, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc000494140, ...}})
  github.com/sagernet/sing-box/common/dialer/resolve.go:46 +0x1b4
github.com/sagernet/sing-box/outbound.(*Direct).DialContext(0xc0002a3ad0, {0x165a488?, 0xc00028c190?}, {0x14393fa, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc000494140, ...}})
  github.com/sagernet/sing-box/outbound/direct.go:92 +0x4e9
github.com/sagernet/sing-box/route.(*RuleSetStartContext).HTTPClient.func1({0x165a488, 0xc00028c190}, {0x14393fa, 0x3}, {0xc000494140?, 0x398bf4?})
  github.com/sagernet/sing-box/route/rule_set.go:53 +0xd9
net/http.(*Transport).dial(0x2191701?, {0x165a488?, 0xc00028c190?}, {0x14393fa?, 0x0?}, {0xc000494140?, 0x1?})
  net/http/transport.go:1183 +0xd2
net/http.(*Transport).dialConn(0xc0004e0500, {0x165a488, 0xc00028c190}, {{}, 0x0, {0xc00003ebe0, 0x5}, {0xc000494140, 0xe}, 0x0})
  net/http/transport.go:1625 +0x7e8
net/http.(*Transport).dialConnFor(0x8b6860?, 0xc0004dc0b0)
  net/http/transport.go:1467 +0x9f
created by net/http.(*Transport).queueForDial in goroutine 99
  net/http/transport.go:1436 +0x3cb



```
</details>

**Comment by nekohasekai** [comment]
Please don't be too smart to only provide partial configuration.

**Comment by nekohasekai** [comment]
Will be fixed in the next version.

**Comment by nekohasekai** [comment]
Of course, you can do this.
