### ISSUE TITLE
tun 模式下 sing-box core panic（第三方图形客户端）

### ISSUE THREAD

**Issue by ghost** [SagerNet/sing-box#1208]
### 操作系统

Windows

### 系统版本

Windows 11 Version 23H2 for x64-based Systems (KB4023057)

### 安装类型

宣传使用 sing-box 的第三方图形客户端程序 (Windows)

### 如果您使用图形客户端程序，请提供该程序版本。

V2rayN  V6.31

### 版本

```shell
<details>


V 1.7.2

</details>
```

### 描述

tun模式常上网，突然断开，看了第三方客户端日志是singbox 的panic，所以来这边提了。
大概正常连接30-40分钟就会断开，重复了三次，每次报错似乎都是空指针的问题。

### 重现方式

不知道如何复现，突然发生。

DNS模式是第三方客户端默认的

```
{
  "servers": [
    {
      "tag": "remote",
      "address": "tcp://8.8.8.8",
      "detour": "proxy"
    },
    {
      "tag": "local",
      "address": "223.5.5.5",
      "detour": "direct"
    },
    {
      "tag": "block",
      "address": "rcode://success"
    }
  ],
  "rules": [
    {
      "geosite": [
        "cn"
      ],
      "server": "local",
      "disable_cache": true
    },
    {
      "geosite": [
        "category-ads-all"
      ],
      "server": "block",
      "disable_cache": true
    }
  ],
  "fakeip": {
    "enabled": true,
    "inet4_range": "198.18.0.0/15",
    "inet6_range": "fc00::/18"
  },
  "strategy": "ipv4_only"
}
```

### 日志

```shell
<details>



panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa441f6]
goroutine 42482 [running]:
bufio.(*Reader).fill(0xc006d11680)
	$GOROOT/src/bufio/bufio.go:113 +0xd6
bufio.(*Reader).Discard(0xc006d11680, 0x6)
	$GOROOT/src/bufio/bufio.go:191 +0x72
github.com/sagernet/sing-box/transport/v2raygrpclite.(*GunConn).read(0xc0071f63c0, {0xc00717c080, 0x2, 0x2})
	/Users/sekai/Projects/sing-box/transport/v2raygrpclite/conn.go:79 +0x9c
github.com/sagernet/sing-box/transport/v2raygrpclite.(*GunConn).Read(0xc006ffcb40?, {0xc00717c080?, 0xc001e25c48?, 0x7b0f54?})
	/Users/sekai/Projects/sing-box/transport/v2raygrpclite/conn.go:58 +0x18
io.ReadAtLeast({0x16f61254058, 0xc005c4a540}, {0xc00717c080, 0x2, 0x2}, 0x2)
	$GOROOT/src/io/io.go:335 +0x90
io.ReadFull(...)
	$GOROOT/src/io/io.go:354
encoding/binary.Read({0x16f61254058, 0xc005c4a540}, {0x18fa2f0, 0x23079c0}, {0x148f3e0, 0xc001e25e9e?})
	$GOROOT/src/encoding/binary/binary.go:237 +0xc5
github.com/sagernet/sing-dns.(*TCPTransport).ReadMessage(0x10013ac?, {0x18fd0f8?, 0xc005c4a540})
	pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_tcp.go:57 +0x85
github.com/sagernet/sing-dns.(*myTransportAdapter).recvLoop.func1({0x10013ac?, 0x0?})
	pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:91 +0x49
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
	pkg/mod/github.com/sagernet/sing@v0.2.18-0.20231203085253-0ba5576c7be8/common/task/task.go:68 +0x73
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 42535
	pkg/mod/github.com/sagernet/sing@v0.2.18-0.20231203085253-0ba5576c7be8/common/task/task.go:67 +0x185



</details>
```

### 完整性要求

- [x] 我保证

### 负责性要求

- [x] 我保证

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/2eecdc38a47c76458a1f1206cdd5e969bfd88d34
