### ISSUE TITLE
Termux 运行 sing-box 时报错 panic

### ISSUE THREAD

**Issue by gzleangle** [SagerNet/sing-box#1231]
### Operating system

Android

### System version

Android 13

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.8.0-beta.1

Environment: go1.21.5 android/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: e7d0a1111625524d7cb5aec4462d297c2ce19d2d
CGO: enabled
```

### Description

在 Termux 下运行 sing-box-1.8.0-beta.1-android-arm64 报错。

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x64115ad9d8]

### Reproduction

执行 ./sing-box run -c t.json

<details>

<summary>配置文件</summary>

```json
{
  "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct"
      },
      {
        "tag": "google",
        "address": "8.8.8.8",
        "detour": "proxy"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "local"
      },
      {
        "rule_set": [
          "geosite-cn"
        ],
        "server": "local"
      }
    ],
    "final": "google"
  },
  "inbounds": [
    {
      "type": "socks",
      "listen": "127.0.0.1",
      "listen_port": 1080,
      "sniff": true,
      "sniff_override_destination": true
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
      "server": "",
      "server_port": ,
      "uuid": "",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "",
        "insecure": false,
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "",
          "short_id": ""
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "rule_set": [
          "geosite-cn",
          "geoip-cn"
        ],
        "outbound": "direct"
      },
      {
        "ip_is_private": true,
        "outbound": "direct"
      }
    ],
    "rule_set": [
      {
        "type": "remote",
        "tag": "geoip-cn",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
        "download_detour": "proxy"
      },
      {
        "type": "remote",
        "tag": "geosite-cn",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs",
        "download_detour": "proxy"
      }
    ],
    "final": "proxy",
    "auto_detect_interface": true
  },
  "experimental": {
    "cache_file": {
      "enabled": true
    }
  }
}
```

</details>

### Logs

```shell
~/sing-box $ ./sing-box run -c t.json
+0000 2023-12-11 23:47:11 INFO outbound/vless[proxy]: outbound connection to raw.githubusercontent.com:443
+0000 2023-12-11 23:47:11 INFO outbound/vless[proxy]: outbound connection to raw.githubusercontent.com:443
+0000 2023-12-11 23:47:11 INFO outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
+0000 2023-12-11 23:47:11 INFO outbound/direct[direct]: outbound packet connection to 223.5.5.5:53
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x64115ad9d8]

goroutine 21 [running]:
github.com/sagernet/sing-box/route.(*Router).AutoDetectInterfaceFunc.func1({0x40002a9980?, 0x4?}, {0x40002a9990?, 0x1?})
        /Users/sekai/Projects/sing-box/route/router.go:1042 +0x78
github.com/sagernet/sing-box/route.(*Router).AutoDetectInterfaceFunc.BindToInterfaceFunc.func2({0x40002a998c, 0x4}, {0x40002a9990, 0xc}, {0x6411982330, 0x40000708f0})
        pkg/mod/github.com/sagernet/sing@v0.2.19-0.20231209022445-766839c00099/common/control/bind.go:19 +0x50
net.(*sysDialer).dialUDP.func1({0x40002a1fb0?, 0x641089527f?}, {0x40002a998c?, 0x6410a77a68?}, {0x40002a9990?, 0x6410a9ea1c?}, {0x6411982330?, 0x40000708f0?})
        $GOROOT/src/net/udpsock_posix.go:209 +0x50
net.(*netFD).dial(0x4000192b00, {0x6411985540, 0x40000f7730}, {0x6411988d58, 0x0}, {0x6411988d58?, 0x40002a1fb0}, 0x400014ee48)
        $GOROOT/src/net/sock_posix.go:130 +0x234
net.socket({0x6411985540, 0x40000f7730}, {0x641089527f, 0x3}, 0x2, 0x2, 0x6410895806?, 0x0?, {0x6411988d58?, 0x0}, ...)
        $GOROOT/src/net/sock_posix.go:70 +0x21c
net.internetSocket({0x6411985540, 0x40000f7730}, {0x641089527f, 0x3}, {0x6411988d58, 0x0}, {0x6411988d58, 0x40002a1fb0}, 0x400014ee58?, 0x6410bb6ce0?, ...)
        $GOROOT/src/net/ipsock_posix.go:142 +0xa8
net.(*sysDialer).dialUDP(0x400014ee88?, {0x6411985540?, 0x40000f7730?}, 0x6410bb4394?, 0x400014ef08?)
        $GOROOT/src/net/udpsock_posix.go:212 +0x94
net.(*sysDialer).dialSingle(0x40001e3680, {0x6411985540, 0x40000f7730}, {0x641197a368?, 0x40002a1fb0})
        $GOROOT/src/net/dial.go:653 +0x21c
net.(*sysDialer).dialSerial(0x40001e3680, {0x6411985540, 0x40000f7730}, {0x4000295650?, 0x1, 0x641230a6a0?})
        $GOROOT/src/net/dial.go:614 +0x1a0
net.(*sysDialer).dialParallel(0x6411985498?, {0x6411985540?, 0x40000f7730?}, {0x4000295650?, 0x4?, 0x641089527f?}, {0x0?, 0x40002a9960?, 0xc?})
        $GOROOT/src/net/dial.go:515 +0x2d0
net.(*Dialer).DialContext(0x400029f2f0, {0x6411985498, 0x40001263f0}, {0x641089527f, 0x3}, {0x40002a9960, 0xc})
        $GOROOT/src/net/dial.go:506 +0x574
github.com/sagernet/sing-box/common/dialer.(*DefaultDialer).DialContext(0x400029f200, {0x6411985498, 0x40001263f0}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/common/dialer/default.go:127 +0x2b4
github.com/sagernet/sing-box/common/dialer.(*ResolveDialer).DialContext(0x40002c0300, {0x6411985498, 0x40001263f0}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/common/dialer/resolve.go:37 +0x298
github.com/sagernet/sing-box/outbound.(*Direct).DialContext(0x40002be5b0, {0x64119854d0?, 0x40001400f0?}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/outbound/direct.go:92 +0x3f0
github.com/sagernet/sing-box/common/dialer.(*DetourDialer).DialContext(0x10?, {0x64119854d0, 0x40001400f0}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/common/dialer/detour.go:47 +0x90
github.com/sagernet/sing-dns.(*UDPTransport).DialContext(0x64119854d0?, {0x64119854d0?, 0x40001400f0?}, {0x0?, 0x400011e040?})
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_udp.go:53 +0x74
github.com/sagernet/sing-dns.(*myTransportAdapter).open(0x4000293830, {0x64119854d0, 0x40000a2e60})
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:71 +0x184
github.com/sagernet/sing-dns.(*myTransportAdapter).exchange(0x4000293830, {0x6411985498, 0x4000126390}, 0x400012a240)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:132 +0x54
github.com/sagernet/sing-dns.(*myTransportAdapter).Exchange(0x6411785900?, {0x6411985498, 0x4000126390}, 0x400012a240)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:119 +0x7c
github.com/sagernet/sing-dns.(*Client).Exchange(0x40002a13e0, {0x64119854d0, 0x40001400a0}, {0x641198bbb0, 0x4000293830}, 0x400012a240, 0x0)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/client.go:115 +0x668
github.com/sagernet/sing-dns.(*Client).lookupToExchange(0x40002a13e0, {0x64119854d0, 0x40001400a0}, {0x641198bbb0, 0x4000293830}, {0x400011e040, 0xe}, 0x1c, 0x0?)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/client.go:436 +0x200
github.com/sagernet/sing-dns.(*Client).Lookup.func2({0x64119854d0?, 0x40001400a0?})
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/client.go:176 +0x54
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        pkg/mod/github.com/sagernet/sing@v0.2.19-0.20231209022445-766839c00099/common/task/task.go:84 +0xc0
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 19
        pkg/mod/github.com/sagernet/sing@v0.2.19-0.20231209022445-766839c00099/common/task/task.go:75 +0x16c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x64115ad9d8]

goroutine 15 [running]:
github.com/sagernet/sing-box/route.(*Router).AutoDetectInterfaceFunc.func1({0x4000384000?, 0x4?}, {0x4000384010?, 0x1?})
        /Users/sekai/Projects/sing-box/route/router.go:1042 +0x78
github.com/sagernet/sing-box/route.(*Router).AutoDetectInterfaceFunc.BindToInterfaceFunc.func2({0x400038400c, 0x4}, {0x4000384010, 0xc}, {0x6411982330, 0x4000382000})
        pkg/mod/github.com/sagernet/sing@v0.2.19-0.20231209022445-766839c00099/common/control/bind.go:19 +0x50
net.(*sysDialer).dialUDP.func1({0x40001264b0?, 0x641089527f?}, {0x400038400c?, 0x6410a77a68?}, {0x4000384010?, 0x6410a9ea1c?}, {0x6411982330?, 0x4000382000?})
        $GOROOT/src/net/udpsock_posix.go:209 +0x50
net.(*netFD).dial(0x4000380000, {0x6411985540, 0x400013e0e0}, {0x6411988d58, 0x0}, {0x6411988d58?, 0x40001264b0}, 0x400014ae48)
        $GOROOT/src/net/sock_posix.go:130 +0x234
net.socket({0x6411985540, 0x400013e0e0}, {0x641089527f, 0x3}, 0x2, 0x2, 0x6410895806?, 0x1c?, {0x6411988d58?, 0x0}, ...)
        $GOROOT/src/net/sock_posix.go:70 +0x21c
net.internetSocket({0x6411985540, 0x400013e0e0}, {0x641089527f, 0x3}, {0x6411988d58, 0x0}, {0x6411988d58, 0x40001264b0}, 0x400014ae58?, 0x6410bb6ce0?, ...)
        $GOROOT/src/net/ipsock_posix.go:142 +0xa8
net.(*sysDialer).dialUDP(0x400014ae88?, {0x6411985540?, 0x400013e0e0?}, 0x6410bb4394?, 0x400014af08?)
        $GOROOT/src/net/udpsock_posix.go:212 +0x94
net.(*sysDialer).dialSingle(0x4000156000, {0x6411985540, 0x400013e0e0}, {0x641197a368?, 0x40001264b0})
        $GOROOT/src/net/dial.go:653 +0x21c
net.(*sysDialer).dialSerial(0x4000156000, {0x6411985540, 0x400013e0e0}, {0x40001201a0?, 0x1, 0x641230a6a0?})
        $GOROOT/src/net/dial.go:614 +0x1a0
net.(*sysDialer).dialParallel(0x6411985498?, {0x6411985540?, 0x400013e0e0?}, {0x40001201a0?, 0x4?, 0x641089527f?}, {0x0?, 0x400011e0c0?, 0xc?})
        $GOROOT/src/net/dial.go:515 +0x2d0
net.(*Dialer).DialContext(0x400029f2f0, {0x6411985498, 0x4000306000}, {0x641089527f, 0x3}, {0x400011e0c0, 0xc})
        $GOROOT/src/net/dial.go:506 +0x574
github.com/sagernet/sing-box/common/dialer.(*DefaultDialer).DialContext(0x400029f200, {0x6411985498, 0x4000306000}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/common/dialer/default.go:127 +0x2b4
github.com/sagernet/sing-box/common/dialer.(*ResolveDialer).DialContext(0x40002c0300, {0x6411985498, 0x4000306000}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/common/dialer/resolve.go:37 +0x298
github.com/sagernet/sing-box/outbound.(*Direct).DialContext(0x40002be5b0, {0x64119854d0?, 0x4000300000?}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/outbound/direct.go:92 +0x3f0
github.com/sagernet/sing-box/common/dialer.(*DetourDialer).DialContext(0x10?, {0x64119854d0, 0x4000300000}, {0x641089527f, 0x3}, {{{0x0, 0xffffdf050505}, 0x400000e060}, 0x35, {0x0, ...}})
        /Users/sekai/Projects/sing-box/common/dialer/detour.go:47 +0x90
github.com/sagernet/sing-dns.(*UDPTransport).DialContext(0x64119854d0?, {0x64119854d0?, 0x4000300000?}, {0x0?, 0x40002a9910?})
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_udp.go:53 +0x74
github.com/sagernet/sing-dns.(*myTransportAdapter).open(0x4000293830, {0x64119854d0, 0x40000a2e60})
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:71 +0x184
github.com/sagernet/sing-dns.(*myTransportAdapter).exchange(0x4000293830, {0x6411985498, 0x40002a1f20}, 0x4000293cb0)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:132 +0x54
github.com/sagernet/sing-dns.(*myTransportAdapter).Exchange(0x6411785900?, {0x6411985498, 0x40002a1f20}, 0x4000293cb0)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/transport_base.go:119 +0x7c
github.com/sagernet/sing-dns.(*Client).Exchange(0x40002a13e0, {0x64119854d0, 0x40000a3220}, {0x641198bbb0, 0x4000293830}, 0x4000293cb0, 0x0)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/client.go:115 +0x668
github.com/sagernet/sing-dns.(*Client).lookupToExchange(0x40002a13e0, {0x64119854d0, 0x40000a3220}, {0x641198bbb0, 0x4000293830}, {0x40002a9910, 0xe}, 0x1c, 0x0?)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/client.go:436 +0x200
github.com/sagernet/sing-dns.(*Client).Lookup.func2({0x64119854d0?, 0x40000a3220?})
        pkg/mod/github.com/sagernet/sing-dns@v0.1.11/client.go:176 +0x54
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        pkg/mod/github.com/sagernet/sing@v0.2.19-0.20231209022445-766839c00099/common/task/task.go:84 +0xc0
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 13
        pkg/mod/github.com/sagernet/sing@v0.2.19-0.20231209022445-766839c00099/common/task/task.go:75 +0x16c
~/sing-box $
```

**Comment by CHIZI-0618** [comment]
或许无特权运行时 auto detect interface 有问题。
你只开了一个 socks inbound，并不需要开启 route.auto_detect_interface

**Comment by gzleangle** [comment]
> 或许无特权运行时 auto detect interface 有问题。 你只开了一个 socks inbound，并不需要开启 route.auto_detect_interface

去掉 route.auto_detect_interface 后报以下错误

FATAL[0000] start service: start package manager: read packages list: open /data/system/packages.xml: permission denied

**Comment by CHIZI-0618** [comment]
> > 或许无特权运行时 auto detect interface 有问题。 你只开了一个 socks inbound，并不需要开启 route.auto_detect_interface
> 
> 去掉 route.auto_detect_interface 后报以下错误
> 
> FATAL[0000] start service: start package manager: read packages list: open /data/system/packages.xml: permission denied

我默认认为你的配置文件是完整的。
在你的配置文件中我没有发现 process/package_name 类型的 route.rules，也没有开启 route.find_process，更不会有 tun_inbound.include_package 等选项，所以我不清楚为什么会读取 /data/system/packages.xml 文件

**Comment by gzleangle** [comment]
是的，配置文件是完整的，仅去掉了 route.auto_detect_interface，配置里没有 process/package_name 类型的 route.rules

**Comment by CHIZI-0618** [comment]
尝试 https://github.com/SagerNet/sing-box/releases/tag/v1.7.5

**Comment by gzleangle** [comment]
sing-box-1.8.0-beta.2 已正常运行，感谢
