### ISSUE TITLE
Panic caused by new buffer system

### ISSUE THREAD

**Issue by Mahdi-zarei** [SagerNet/sing-box#1247]
### Operating system

Linux

### System version

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

### Installation type

Original sing-box Command Line

### Version

```shell
latest dev-next branch
```

### Description

After [Add simple buffer struct pool](https://github.com/SagerNet/sing/commit/0dd22b339654ebcd2bc37333cf3830b7340db6ee) sing-box panics repeatedly, by reverting this commit no more panics occurred. This only happens on the server side.

### Reproduction
```
{
  "log": {
    "level": "error",
    "timestamp": true
  },
  "dns": {
    "disable_cache": false,
    "servers": [
      {
        "tag": "google",
        "address": "8.8.8.8",
        "strategy": "prefer_ipv4",
        "detour": "direct"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "TtoWG",
      "interface_name": "sing",
      "inet4_address": "172.19.0.1/24",
      "inet6_address": "fdfe:dcba:9876::1/96",
      "mtu": 1500,
      "gso": true,
      "sniff": true,
      "auto_route": true,
      "stack": "system",
      "include_interface": [
        "tun0"
      ]
    },
    {
      "type": "vless",
      "tag": "Vin6",
      "listen": "...",
      "listen_port": 443,
      "domain_strategy": "prefer_ipv4",
      "sniff": true,
      "users": [
        {
          ...
        }
      ],
      "multiplex": {
        "enabled": true
      },
      "tls": {
        "enabled": true,
        "server_name": "www.cloudflare.com",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "www.cloudflare.com",
            "server_port": 443
          },
          "private_key": "...",
          "short_id": [
            "..."
          ],
          "max_time_difference": "70m"
        }
      }
    },
    {
      "type": "trojan",
      "tag": "TRJin",
      "tcp_fast_open": true,
      "listen": "...",
      "listen_port": 443,
      "domain_strategy": "prefer_ipv4",
      "sniff": true,
      "users": [
        ...
      ],
      "multiplex": {
        "enabled": true
      },
      "tls": {
        "enabled": true,
        "server_name": "...",
        ...
      }
    },
    {
      "type": "tuic",
      "tag": "Tin",
      "listen": "...",
      "listen_port": 800,
      "domain_strategy": "prefer_ipv4",
      "sniff": true,
      "users": [
        ...
      ],
      "congestion_control": "bbr",
      "tls": {
        "enabled": true,
        "server_name": "...",
        ...
      }
    },
    {
      "type": "vless",
      "tag": "VG-in",
      "listen": "...",
      "listen_port": 2096,
      "domain_strategy": "prefer_ipv4",
      "tcp_fast_open": true,
      "sniff": true,
      "users": [
        ...
      ],
      "multiplex": {
        "enabled": true
      },
      "tls": {
        "enabled": true,
        "server_name": "...",
        ...
      },
      "transport": {
        "type": "ws",
        "path": "/...",
        "headers": {
          "Host": "..."
        }
      }
    },
    {
      "type": "vless",
      "tag": "VH-in",
      "listen": "...",
      "listen_port": 8080,
      "domain_strategy": "prefer_ipv4",
      "tcp_fast_open": true,
      "sniff": true,
      "users": [
        ...
      ],
      "multiplex": {
        "enabled": true
      },
      "transport": {
        "type": "http",
        "host": [
          "..."
        ],
        "idle_timeout": "30s"
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "wireguard",
      "tag": "wg",
      "server": "2606:4700:d0::a29f:c001",
      "server_port": 2408,
      "system_interface": true,
      "gso": true,
      "interface_name": "wg0",
      "local_address": [
        "172.16.0.2/24",
        "2606:4700:110:8ea5:e3d2:d16c:3d44:b254/96"
      ],
      "mtu": 1280,
      "peer_public_key": "...",
      "private_key": "...",
      "reserved": "4z1N"
    }
  ],
  "route": {
    "rule_set": [
      {
        "type": "local",
        "tag": "irip",
        "format": "binary",
        "path": "/root/sing/irgip.srs"
      }
    ],
    "rules": [
      {
        "ip_is_private": true,
        "outbound": "block"
      },
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        ...
      },
      {
          ...
      },
      {
        "rule_set": "irip",
        "outbound": "block"
      }
    ]
  }
}
```

The config above runs with the said issue.

### Logs

```shell
panic: runtime error: slice bounds out of range [:510] with capacity 0
goroutine 361 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Bytes(...)
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/buf/buffer.go:341
github.com/sagernet/sing/common/bufio.(*ExtendedWriterWrapper).WriteBuffer(0x8000?, 0xc0002b1f00?)
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/conn.go:117 +0xc5
github.com/sagernet/sing/common/bufio.CopyExtendedWithPool({0x148cd20?, 0xc0002754e8}, {0x1490668?, 0xc000267e40}, {0x1490690, 0xc000267e50}, {0x0, 0x0, 0x>
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:141 +0x1cb
github.com/sagernet/sing/common/bufio.CopyExtended({0x148cd20, 0xc0002754e8}, {0x1490668?, 0xc000267e40}, {0x1490690?, 0xc000267e50?}, {0x0, 0x0, 0x0}, {0x>
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:76 +0x26e
github.com/sagernet/sing/common/bufio.Copy({0x148a920?, 0xc00011a5a0?}, {0x148cd20, 0xc0002754e8})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:55 +0x587
github.com/sagernet/sing/common/bufio.CopyConnContextList.func1({0xc002483fd0?, 0x53b790?})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:168 +0x72
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/task/task.go:84 +0xce
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 388
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/task/task.go:75 +0x185

panic: runtime error: slice bounds out of range [:100] with capacity 0
goroutine 715 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Bytes(...)
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/buf/buffer.go:341
github.com/sagernet/sing/common/bufio/deadline.(*reader).pipeReturnBuffer(0xc0022d3bc8?, 0xc003810a80, 0xc0000e9128?)
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/deadline/reader.go:117 +0x158
github.com/sagernet/sing/common/bufio/deadline.(*reader).ReadBuffer(0xc002c7fb60, 0xc00439e040)
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/deadline/reader.go:110 +0x22f
github.com/sagernet/sing/common/bufio/deadline.(*Conn).ReadBuffer(0x8000?, 0xc002afba60?)
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/deadline/conn.go:36 +0x1c
github.com/sagernet/sing/common/bufio.CopyExtendedWithPool({0x148cd20?, 0xc002d02a80}, {0x1490668?, 0xc002d8c150}, {0x7fa4281f1c60, 0xc002afba60}, {0x0, 0x0, 0xc000065800?}, {0x0, ...})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:130 +0x18d
github.com/sagernet/sing/common/bufio.CopyExtended({0x148cd20, 0xc002d02a80}, {0x1490668?, 0xc002d8c150}, {0x7fa4281f1c60?, 0xc002afba60?}, {0x0, 0x0, 0x0}, {0x0, ...})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:76 +0x26e
github.com/sagernet/sing/common/bufio.Copy({0x148a920?, 0xc0000629e8?}, {0x148cd20, 0xc002d02a80})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:55 +0x587
github.com/sagernet/sing/common/bufio.CopyConnContextList.func1({0xc0022d3fd0?, 0x53b790?})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/bufio/copy.go:168 +0x72
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/task/task.go:84 +0xce
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 713
        /root/go/pkg/mod/github.com/sagernet/sing@v0.3.0-beta.2.0.20231215035907-17dab0e7bc33/common/task/task.go:75 +0x185

```

**Comment by nekohasekai** [comment]
Please provide the log of the latest prerelease version of sing-box, not your fork. (I see sing v0.5 which does not exist)

**Comment by Mahdi-zarei** [comment]
I had tried to match the lines as the changes were not related. The logs are now updated and are of the sing-box built upon the latest official dev-next changes.

**Comment by nekohasekai** [comment]
No, they are not the same code. If you are determined to use dev-next instead of prerelease, please solve this problem instead.

**Comment by Mahdi-zarei** [comment]
Sorry I did not quite get it, do you mean that I should fallback to prerelease versions and wait for a more stable version to be released or do you mean that I should try and find the solution myself if I am going to use the dev-next branch? Btw the logs are currently not from my fork anymore and they are from the dev-next branch of sing-box without any modifications.

**Comment by nekohasekai** [comment]
What I mean is that I need bug reports for prerelease, not dev-next, because the code is different. Anyway, I've rolled back the change so this issue can be closed.

**Comment by Mahdi-zarei** [comment]
This is understandable, thank you!
