### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by Gzxhwq** [SagerNet/sing-box#125]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

Random crach in dev-next branch

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version v1.1-beta8-12-g8d450d2

Environment: go1.19.1 linux/amd64
Tags: with_quic,with_wireguard,with_utls,with_acme,with_clash_api
Revision: 8d450d203bdea293eddf09d19923e555ae346c2f
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": {
    "disabled": false,
    "level": "debug",
    "output": "/etc/sing-box/sing-box.log",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui": "",
      "secret": "***********",
      "default_mode": "rule",
      "store_selected": true,
      "cache_file": "cache.db"
    }
  }, 
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8"
      },
      {
        "tag": "local",
        "address": "tls://1.12.12.12",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "domain": "mydomain.com",
        "geosite": "cn",
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "endpoint_independent_nat": true,
      "stack": "system",
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "Home",    
      "outbounds": [
        "GRPC-out",
        "WS-out",
      ],
      "default": "GRPC-out"
    }
    {
      "type": "trojan",
      "tag": "GRPC-out",
      "server": "***********",
      "server_port": ************,
      "password": "**********",
      "transport": {
        "type": "grpc",
        "service_name": "**************"
      },
      "tls": {
        "enabled": true,
        "server_name": "*****************"
      }
    },
    {
      "type": "trojan",
      "tag": "WS-out",
      "server": "***************",
      "server_port": ***************,
      "password": "*****************",
      "transport": {
        "type": "ws",
        "path": "/*******************",
        "early_data_header_name": "Sec-WebSocket-Protocol"
      },
      "tls": {
        "enabled": true,
        "server_name": "**********************"
      },
      "multiplex": {
        "enabled": true,
        "protocol": "smux",
        "max_connections": 4,
        "min_streams": 4
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  }
}


```

</details>

### Server and client log file

<details>

```console
panic: runtime error: index out of range [1] with length 0

goroutine 1530 [running]:
encoding/binary.bigEndian.PutUint16(...)
	encoding/binary/binary.go:144
github.com/sagernet/sing-tun/internal/clashtcpip.UDPPacket.SetLength(...)
	github.com/sagernet/sing-tun@v0.0.0-20220929163559-a93592a9b581/internal/clashtcpip/udp.go:16
github.com/sagernet/sing-tun.(*systemPacketWriter4).WritePacket(0xc0000a0340, 0xc00200fe80, {{{0x0, 0xffffadc204a9}, 0xc000010030}, 0x1bb, {0x0, 0x0}})
	github.com/sagernet/sing-tun@v0.0.0-20220929163559-a93592a9b581/system.go:391 +0x6c7
github.com/sagernet/sing/common/udpnat.(*conn).WritePacket(0x0?, 0x0?, {{{0x0, 0xffffadc204a9}, 0xc000010030}, 0x1bb, {0x0, 0x0}})
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/udpnat/service.go:158 +0x5d
github.com/sagernet/sing-box/experimental/trackerconn.(*HookPacketConn).WritePacket(0xc000faa200, 0xc00200fe80?, {{{0x0, 0xffffadc204a9}, 0xc000010030}, 0x1bb, {0x0, 0x0}})
	github.com/sagernet/sing-box/experimental/trackerconn/packet_conn.go:63 +0x76
github.com/sagernet/sing/common/bufio.CopyPacket({0x7fffd05036b0, 0xc000faa220}, {0x7fffd05036d0?, 0xc00228c180?})
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/bufio/copy.go:268 +0x5b1
github.com/sagernet/sing/common/bufio.CopyPacketConn.func2({0x0?, 0xc00034a900?})
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/bufio/copy.go:342 +0x6c
github.com/sagernet/sing/common/task.(*Group).Run.func1()
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/task/task.go:59 +0x93
created by github.com/sagernet/sing/common/task.(*Group).Run
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/task/task.go:58 +0x54a


```

</details>

**Comment by nekohasekai** [comment]
Try 77508a9c6a0ac52aab33d9dc7ce517c7b1d2acb0

**Comment by Gzxhwq** [comment]
Test for a few hours, no crash again. It seems fixed.

**Comment by Gzxhwq** [comment]
Crash again, maybe another problem?

```
panic: runtime error: slice bounds out of range [60:32]

goroutine 26422 [running]:
github.com/sagernet/sing-tun/internal/clashtcpip.IPv4Packet.Payload(...)
	github.com/sagernet/sing-tun@v0.0.0-20221001115016-6335837b6402/internal/clashtcpip/ip.go:101
github.com/sagernet/sing-tun.(*systemPacketWriter4).WritePacket(0xc008546b80, 0xc006e81e80, {{{0x0, 0xffff8efa45ca}, 0xc0000ac018}, 0x1bb, {0x0, 0x0}})
	github.com/sagernet/sing-tun@v0.0.0-20221001115016-6335837b6402/system.go:400 +0x6f0
github.com/sagernet/sing/common/udpnat.(*conn).WritePacket(0x0?, 0x0?, {{{0x0, 0xffff8efa45ca}, 0xc0000ac018}, 0x1bb, {0x0, 0x0}})
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/udpnat/service.go:158 +0x5d
github.com/sagernet/sing-box/experimental/trackerconn.(*HookPacketConn).WritePacket(0xc00885f620, 0xc0018bfe80?, {{{0x0, 0xffff8efa45ca}, 0xc0000ac018}, 0x1bb, {0x0, 0x0}})
	github.com/sagernet/sing-box/experimental/trackerconn/packet_conn.go:63 +0x76
github.com/sagernet/sing/common/bufio.CopyPacket({0x7fffd0b47400, 0xc00885f640}, {0x7fffd0b47420?, 0xc0018464b0?})
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/bufio/copy.go:268 +0x5b1
github.com/sagernet/sing/common/bufio.CopyPacketConn.func2({0xc001e600a8?, 0xc001e600a0?})
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/bufio/copy.go:342 +0x6c
github.com/sagernet/sing/common/task.(*Group).Run.func1()
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/task/task.go:59 +0x93
created by github.com/sagernet/sing/common/task.(*Group).Run
	github.com/sagernet/sing@v0.0.0-20221001030341-348376220066/common/task/task.go:58 +0x54a
```

**Comment by nekohasekai** [comment]
Try 7d8fb389ebd329046d2c19b8d6b169272866c38f

**Comment by Gzxhwq** [comment]
OK，trying.
