### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by rentry00** [SagerNet/sing-box#1270]
### Operating system

Windows

### System version

windows 10

### Installation type

Original sing-box Command Line

### If you are using a graphical client, please provide the version of the client.

1.8 rc.1

### Version

```shell
1.8 rc.1
```

### Description

使用sing-box rule-set进行json转binary时，出现内存泄漏问题  json文件60m

runtime: out of memory: cannot allocate 1073741824-byte block (1077805056 in use)
f out of memoryatal error: out of memory

### Reproduction

使用sing-box rule-set进行json转binary时，出现内存泄漏问题  json文件60m

runtime: out of memory: cannot allocate 1073741824-byte block (1077805056 in use)
f out of memoryatal error: out of memory

### Logs

```shell
runtime: out of memory: cannot allocate 1073741824-byte block (1077805056 in use)
fatal error: out of memory

goroutine 1 [running]:
runtime.throw({0x1d8df3b, 0xd})
        $GOROOT/src/runtime/panic.go:1047 +0x4d fp=0xc20dce8 sp=0xc20dcd4 pc=0xe7b50d
runtime.(*mcache).allocLarge(0x3120088, 0x3ffffe00, 0x1)
        $GOROOT/src/runtime/mcache.go:236 +0x1be fp=0xc20dd10 sp=0xc20dce8 pc=0xe54dbe
runtime.mallocgc(0x3ffffe00, 0x1bda6e0, 0x1)
        $GOROOT/src/runtime/malloc.go:1053 +0x3eb fp=0xc20dd48 sp=0xc20dd10 pc=0xe4c55b
runtime.makeslice(0x1bda6e0, 0x1ffffdfe, 0x3ffffe00)
        $GOROOT/src/runtime/slice.go:103 +0x4f fp=0xc20dd5c sp=0xc20dd48 pc=0xe918ef
github.com/sagernet/sing/common/json/internal/contextjson_120.(*Decoder).refill(0xbc70840)
        pkg/mod/github.com/sagernet/sing@v0.3.0-beta.7/common/json/internal/contextjson_120/stream.go:159 +0xd9 fp=0xc20dd8c sp=0xc20dd5c pc=0x1221079
github.com/sagernet/sing/common/json/internal/contextjson_120.(*Decoder).readValue(0xbc70840)
        pkg/mod/github.com/sagernet/sing@v0.3.0-beta.7/common/json/internal/contextjson_120/stream.go:140 +0x99 fp=0xc20ddb4 sp=0xc20dd8c pc=0x1220d19
github.com/sagernet/sing/common/json/internal/contextjson_120.(*Decoder).Decode(0xbc70840, {0x1c767a0, 0xbc099b0})
        pkg/mod/github.com/sagernet/sing@v0.3.0-beta.7/common/json/internal/contextjson_120/stream.go:63 +0x6e fp=0xc20ddd4 sp=0xc20ddb4 pc=0x1220aae
main.compileRuleSet({0xbc343c0, 0x4d})
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_rule_set_compile.go:53 +0x1c7 fp=0xc20de54 sp=0xc20ddd4 pc=0x1aff007
main.glob..func19(0x28e48c0, {0xbd902b8, 0x1, 0x3})
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_rule_set_compile.go:25 +0x3a fp=0xc20de70 sp=0xc20de54 pc=0x1afecca
github.com/spf13/cobra.(*Command).execute(0x28e48c0, {0xbd902a0, 0x3, 0x3})
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa36 fp=0xc20df2c sp=0xc20de70 pc=0x1ae9f36
github.com/spf13/cobra.(*Command).ExecuteC(0x28e5ac0)
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x45d fp=0xc20dfa8 sp=0xc20df2c pc=0x1aea78d
github.com/spf13/cobra.(*Command).Execute(...)
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /Users/sekai/Projects/sing-box/cmd/sing-box/main.go:38 +0x27 fp=0xc20dfc4 sp=0xc20dfa8 pc=0x1b04307
runtime.main()
        $GOROOT/src/runtime/proc.go:250 +0x22e fp=0xc20dff0 sp=0xc20dfc4 pc=0xe7e35e
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xc20dff4 sp=0xc20dff0 pc=0xeb1161

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1dea024, 0x28eb898, 0x11, 0x14, 0x1)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc5dfdc sp=0xbc5dfc8 pc=0xe7e78f
runtime.goparkunlock(...)
        $GOROOT/src/runtime/proc.go:387
runtime.forcegchelper()
        $GOROOT/src/runtime/proc.go:305 +0xcf fp=0xbc5dff0 sp=0xbc5dfdc pc=0xe7e5bf
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc5dff4 sp=0xbc5dff0 pc=0xeb1161
created by runtime.init.5
        $GOROOT/src/runtime/proc.go:293 +0x23

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1dea024, 0x28ec5a0, 0xc, 0x14, 0x1)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc5efcc sp=0xbc5efb8 pc=0xe7e78f
runtime.goparkunlock(...)
        $GOROOT/src/runtime/proc.go:387
runtime.bgsweep(0xbc401c0)
        $GOROOT/src/runtime/mgcsweep.go:319 +0xf2 fp=0xbc5efe8 sp=0xbc5efcc pc=0xe65d72
runtime.gcenable.func1()
        $GOROOT/src/runtime/mgc.go:178 +0x27 fp=0xbc5eff0 sp=0xbc5efe8 pc=0xe573d7
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc5eff4 sp=0xbc5eff0 pc=0xeb1161
created by runtime.gcenable
        $GOROOT/src/runtime/mgc.go:178 +0x7c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1dea024, 0x28ecb80, 0xd, 0x14, 0x2)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc5ffb8 sp=0xbc5ffa4 pc=0xe7e78f
runtime.goparkunlock(...)
        $GOROOT/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x28ecb80)
        $GOROOT/src/runtime/mgcscavenge.go:400 +0x5f fp=0xbc5ffcc sp=0xbc5ffb8 pc=0xe631ff
runtime.bgscavenge(0xbc401c0)
        $GOROOT/src/runtime/mgcscavenge.go:633 +0x77 fp=0xbc5ffe8 sp=0xbc5ffcc pc=0xe63a07
runtime.gcenable.func2()
        $GOROOT/src/runtime/mgc.go:179 +0x27 fp=0xbc5fff0 sp=0xbc5ffe8 pc=0xe57397
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc5fff4 sp=0xbc5fff0 pc=0xeb1161
created by runtime.gcenable
        $GOROOT/src/runtime/mgc.go:179 +0xc1

goroutine 5 [finalizer wait]:
runtime.gopark(0x1de9f50, 0x2915070, 0x10, 0x14, 0x1)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc5cf94 sp=0xbc5cf80 pc=0xe7e78f
runtime.runfinq()
        $GOROOT/src/runtime/mfinal.go:193 +0xf4 fp=0xbc5cff0 sp=0xbc5cf94 pc=0xe56564
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc5cff4 sp=0xbc5cff0 pc=0xeb1161
created by runtime.createfing
        $GOROOT/src/runtime/mfinal.go:163 +0x60

goroutine 6 [select]:
runtime.gopark(0x1dea05c, 0x0, 0x9, 0x18, 0x1)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc58e40 sp=0xbc58e2c pc=0xe7e78f
runtime.selectgo(0xbc58f9c, 0xbc58f58, 0x0, 0x0, 0x2, 0x1)
        $GOROOT/src/runtime/select.go:327 +0xbc0 fp=0xbc58f30 sp=0xbc58e40 pc=0xe8f180
github.com/sagernet/sing/common/observable.(*Observer[...]).process(0x1f81360)
        pkg/mod/github.com/sagernet/sing@v0.3.0-beta.7/common/observable/observer.go:35 +0xdc fp=0xbc58fe4 sp=0xbc58f30 pc=0x127143c
github.com/sagernet/sing/common/observable.NewObserver[...].func1()
        pkg/mod/github.com/sagernet/sing@v0.3.0-beta.7/common/observable/observer.go:27 +0x2e fp=0xbc58ff0 sp=0xbc58fe4 pc=0x1270f1e
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc58ff4 sp=0xbc58ff0 pc=0xeb1161
created by github.com/sagernet/sing/common/observable.NewObserver[...]
        pkg/mod/github.com/sagernet/sing@v0.3.0-beta.7/common/observable/observer.go:27 +0xde

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbcb6000, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbcb2f94 sp=0xbcb2f80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbcb2ff0 sp=0xbcb2f94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbcb2ff4 sp=0xbcb2ff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbc3aeb8, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbcb3f94 sp=0xbcb3f80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbcb3ff0 sp=0xbcb3f94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbcb3ff4 sp=0xbcb3ff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbc3aed0, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbcaef94 sp=0xbcaef80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbcaeff0 sp=0xbcaef94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbcaeff4 sp=0xbcaeff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbcb6018, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc59f94 sp=0xbc59f80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbc59ff0 sp=0xbc59f94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc59ff4 sp=0xbc59ff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xc1e2000, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbcb4f94 sp=0xbcb4f80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbcb4ff0 sp=0xbcb4f94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbcb4ff4 sp=0xbcb4ff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbc3aee8, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbcaff94 sp=0xbcaff80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbcafff0 sp=0xbcaff94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbcafff4 sp=0xbcafff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbcb6030, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbc5af94 sp=0xbc5af80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbc5aff0 sp=0xbc5af94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbc5aff4 sp=0xbc5aff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x1de9f60, 0xbc3af00, 0x1a, 0x14, 0x0)
        $GOROOT/src/runtime/proc.go:381 +0xff fp=0xbcb5f94 sp=0xbcb5f80 pc=0xe7e78f
runtime.gcBgMarkWorker()
        $GOROOT/src/runtime/mgc.go:1275 +0xee fp=0xbcb5ff0 sp=0xbcb5f94 pc=0xe59aee
runtime.goexit()
        $GOROOT/src/runtime/asm_386.s:1326 +0x1 fp=0xbcb5ff4 sp=0xbcb5ff0 pc=0xeb1161
created by runtime.gcBgMarkStartWorkers
        $GOROOT/src/runtime/mgc.go:1199 +0x25
```

**Comment by nekohasekai** [comment]
stdlib problem.
