### ISSUE TITLE
[Android tun] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yjmp14** [SagerNet/sing-box#139]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

When using tun mode on Android, it gets such error. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x555d8ba3f0]                                                                   
goroutine 1 [running]:
github.com/sagernet/sing-tun.(*NativeTun).rules(0x4000378480)                  pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20221005115555-9a556307f6a3/tun_linux.go:280 +0x4b0                                       github.com/sagernet/sing-tun.(*NativeTun).setRules(0x555e8b6460?)
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20221005115555-9a556307f6a3/tun_linux.go:482 +0x24
github.com/sagernet/sing-tun.(*NativeTun).configure(0x4000378480, {0x555e26d540, 0x40000d6000})
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20221005115555-9a556307f6a3/tun_linux.go:151 +0x1e0
github.com/sagernet/sing-tun.Open({{0x40002f9f2c, 0x4}, {0x400008b9a0, 0x1, 0x1}, {0x400008b9c0, 0x1, 0x1}, 0x2328, 0x1, ...})
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20221005115555-9a556307f6a3/tun_linux.go:43 +0x1b0
github.com/sagernet/sing-box/inbound.(*Tun).Start(0x40000d6c60)
        /home/sekai/Projects/sing-box/inbound/tun.go:142 +0xb4
github.com/sagernet/sing-box.(*Box).start(0x40000cc9a0)
        /home/sekai/Projects/sing-box/box.go:225 +0x394
github.com/sagernet/sing-box.(*Box).Start(0x555e275ef8?)
        /home/sekai/Projects/sing-box/box.go:189 +0x2c
main.create()
        /home/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:72 +0x1ec
main.run()                                                                     /home/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:84 +0x90
main.glob..func3(0x555e8afec0?, {0x555dc80b7c?, 0x2?, 0x2?})
        /home/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:23 +0x1c
github.com/spf13/cobra.(*Command).execute(0x555e8afec0, {0x400008aa40, 0x2, 0x2})
        pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x555e8b0140)
        pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/sekai/Projects/sing-box/cmd/sing-box/main.go:30 +0x28
```

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1-beta9


Environment: go1.19.2 android/arm64
Tags: with_gvisor,with_quic,with_wireguard,with_clash_api
Revision: 143b62218040348c7c165ecec27c25e324dffee9
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
# paste log here
```

</details>

**Comment by nekohasekai** [comment]
Try 41fb0c01116765fdf8640512602acbd3a030cb6e

**Comment by yjmp14** [comment]
> Try [41fb0c0](https://github.com/SagerNet/sing-box/commit/41fb0c01116765fdf8640512602acbd3a030cb6e)

This works fine.
