### ISSUE TITLE
panic: run time error. android dev-next branch.

### ISSUE THREAD

**Issue by NDI3-MDAx** [SagerNet/sing-box#141]
### Welcome

- [ ] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

built on commit [Fix interface monitor](https://github.com/SagerNet/sing-box/commit/41fb0c01116765fdf8640512602acbd3a030cb6e)

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1-beta9

Environment: go1.19.1 android/arm64
Tags: with_gvisor,with_quic,with_wireguard,with_clash_api
Revision: 41fb0c01116765fdf8640512602acbd3a030cb6e
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```json
{
  "log": {
    "disabled": false,
    "level": "error",
    "timestamp": true
  },
  "dns": {
    "disable_cache": false,
    "disable_expire": false,
    "servers": [
      {
        "tag": "global",
        "address": "8.8.8.8",
        "detour": "proxy"
      },
      {
        "tag": "cn",
        "address": "https://223.5.5.5/dns-query",
        "detour": "direct"
      },
      {
        "tag": "cn-2",
        "address": "https://1.12.12.12/dns-query",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "domain": ["cdn.jsdelivr.net"],
        "geosite": ["cn"],
        "server": "cn"
      }
    ],
    "final": "global"
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "socks-in",
      "listen": "127.0.0.1",
      "listen_port": 5353,
      "sniff": true,
      "sniff_override_destination": false
    },
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": true,
      "sniff": true,
      "endpoint_independent_nat": false,
      "exclude_package": [
        "com.android.captiveportallogin"
      ]
    }
  ],
  "outbounds": [
    {
      "type": "trojan",
      "tag": "proxy",
      "server": "xxx",
      "server_port": 443,
      "password": "xxx",
      "tls": {
        "server_name": "xxx",
        "enabled": true,
        "insecure": false
      },
      "transport": {
        "type": "ws",
        "path": "xxx",
        "headers": {
          "Host": "xxx"
        },
        "max_early_data": 1024
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "geoip": {
      "path": "/data/sing-box/geoip.db"
    },
    "geosite": {
      "path": "/data/sing-box/geosite.db"
    },
    "auto_detect_interface": true,
    "override_android_vpn": true,
    "rules": [
      {
        "port": 53,
        "outbound": "dns-out"
      },
      {
        "port": 853,
        "outbound": "dns-out"
      },
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": ["cn"],
        "geoip": ["cn", "private"],
        "outbound": "direct"
      }
    ],
    "final": "proxy"
  },
  "experimental": {}
}
```

</details>

### Server and client log file

<details>

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x628a073a60]

goroutine 149 [running]:
github.com/sagernet/sing-box/transport/v2raywebsocket.(*WebsocketConn).Upstream(0x628a327c00?)
        <autogenerated>:1
github.com/sagernet/sing/common/network.calculateWriterMTU({0x628a4443e0, 0x0})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/network/thread.go:174 +0x7c
github.com/sagernet/sing/common/network.calculateWriterMTU({0x628a3efd60, 0x4000597aa0})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/network/thread.go:174 +0x80
github.com/sagernet/sing/common/network.calculateWriterMTU({0x628a402fa0, 0x40004a0f50})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/network/thread.go:174 +0x80
github.com/sagernet/sing/common/network.CalculateMTU({0x0?, 0x0?}, {0x628a402fa0, 0x40004a0f50})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/network/thread.go:138 +0x3c
github.com/sagernet/sing/common/bufio.WritePacketBuffer({0x7b830ed0c0?, 0x40004a0f50}, 0x4000597b30, {{{0x0, 0xffff08080808}, 0x4000128018}, 0x35, {0x0, 0x0}})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/bufio/io.go:70 +0xd8
github.com/sagernet/sing/common/bufio.WritePacket({0x628a469a80, 0x40004a0f50}, {0x4000545000, 0x21, 0x1000}, {0x628a4738f8, 0x4000597ad0})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/bufio/io.go:60 +0x114
github.com/sagernet/sing/protocol/trojan.(*ClientPacketConn).WriteTo(0x10?, {0x4000545000?, 0x400023e9f8?, 0x6289eedb7c?}, {0x628a4738f8?, 0x4000597ad0?})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/protocol/trojan/protocol.go:128 +0x48
github.com/sagernet/sing/common/bufio.(*BindPacketConn).Write(0x0?, {0x4000545000?, 0x400023ea28?, 0x6289a22d34?})
        github.com/sagernet/sing@v0.0.0-20221007121755-ec72b91c12e2/common/bufio/conn.go:84 +0x38
github.com/sagernet/sing-dns.(*UDPTransport).WriteMessage(0x4000024028?, {0x628a480980, 0x4000024000}, 0x0?)
        github.com/sagernet/sing-dns@v0.0.0-20220929010544-ee843807aae3/transport_udp.go:81 +0x15c
github.com/sagernet/sing-dns.(*myTransportAdapter).exchange(0x40000d4580, {0x628a477d48, 0x40005ae6c0}, 0x4000288090)
        github.com/sagernet/sing-dns@v0.0.0-20220929010544-ee843807aae3/transport_base.go:132 +0x1b0
github.com/sagernet/sing-dns.(*myTransportAdapter).Exchange(0x628a4774a0?, {0x628a477d48, 0x40005ae6c0}, 0x4000288090)
        github.com/sagernet/sing-dns@v0.0.0-20220929010544-ee843807aae3/transport_base.go:107 +0x7c
github.com/sagernet/sing-dns.(*Client).Exchange(0x4000290810, {0x628a477d48, 0x40005ae6c0}, {0x628a479ba0, 0x40000d4580}, 0x4000288090, 0x0)
        github.com/sagernet/sing-dns@v0.0.0-20220929010544-ee843807aae3/client.go:81 +0x294
github.com/sagernet/sing-box/route.(*Router).Exchange(0x4000286b40, {0x628a477d80?, 0x4000597950?}, 0x4000288090)
        github.com/sagernet/sing-box/route/router_dns.go:60 +0x244
github.com/sagernet/sing-box/outbound.(*DNS).NewPacketConnection.func1.1()
        github.com/sagernet/sing-box/outbound/dns.go:128 +0x90
created by github.com/sagernet/sing-box/outbound.(*DNS).NewPacketConnection.func1
        github.com/sagernet/sing-box/outbound/dns.go:127 +0x110
```

</details>

**Comment by nekohasekai** [comment]
Try a01bb569d1fc635e8d740719135b81f839d97d0b

**Comment by BlindingDark** [comment]
It works! Thanks a lot 🙏

**Comment by NDI3-MDAx** [comment]
Just tried it, works fine with this commit, thanks :+1:
