### ISSUE TITLE
Docker下服务器地址错误

### ISSUE THREAD

**Issue by ricolxwz** [SagerNet/sing-box#1460]
### 操作系统

Linux

### 系统版本

Debian12

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
v1.9.0-alpha.5
```

### 描述

Docker启动后报错:
```shell
goroutine 1 [running]:
github.com/sagernet/sing/common.Must1[...](...)
	github.com/sagernet/sing@v0.3.1-beta.1/common/cond.go:294
github.com/sagernet/sing-box/route.NewRouter({_, _}, {_, _}, {0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
	github.com/sagernet/sing-box/route/router.go:278 +0x309a
github.com/sagernet/sing-box.New({{{0xc00013c400, 0x149, 0x200}, {0x0, 0x0}, 0x0, 0x0, 0x0, {0xc0000a4408, 0x1, ...}, ...}, ...})
	github.com/sagernet/sing-box/box.go:88 +0x594
main.create()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:137 +0x198
main.run()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:174 +0x10c
main.init.func24(0xc000101a00?, {0x14572fe?, 0x4?, 0x1457302?})
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:30 +0x17
github.com/spf13/cobra.(*Command).execute(0x20137c0, {0xc0000b6800, 0x4, 0x4})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x2013aa0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	github.com/sagernet/sing-box/cmd/sing-box/main.go:38 +0x1e
panic: invalid server address
```

### 重现方式

Shell构建指令: 
```shell
read -p "Enter Port: " port
echo "net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0" | sudo tee -a /etc/sysctl.conf > /dev/null
sudo sysctl -p
echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf > /dev/null
sudo apt update -y
sudo apt install ca-certificates curl -y
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update -y
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
CONFIG='{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64",
  "experimental": true,
  "ip6tables": true
}'
FILE="/etc/docker/daemon.json"
if [ -f "$FILE" ]; then
    sudo cp $FILE ${FILE}.bak
    echo "$CONFIG" | sudo tee $FILE > /dev/null
else
    echo "$CONFIG" | sudo tee $FILE > /dev/null
fi
sudo systemctl restart docker
sudo docker pull ghcr.io/sagernet/sing-box:latest
sudo mkdir -p /var/lib/sing-box
sudo mkdir -p /etc/sing-box
sudo openssl ecparam -genkey -name prime256v1 -out /etc/sing-box/private.key
sudo openssl req -new -x509 -days 36500 -key /etc/sing-box/private.key -out /etc/sing-box/cert.crt -subj "/CN=bing.com"
echo -e "{
    \x22inbounds\x22: [
        {
            \x22type\x22: \x22hysteria2\x22,
            \x22listen\x22: \x22::\x22,
            \x22listen_port\x22: $port,
            \x22users\x22: [
                {
                    \x22password\x22: \x22$(openssl rand -base64 12)\x22
                }
            ],
            \x22tls\x22: {
                \x22enabled\x22: true,
                \x22certificate_path\x22: \x22/etc/sing-box/cert.crt\x22,
                \x22key_path\x22: \x22/etc/sing-box/private.key\x22
            }
        }
    ],
    \x22outbounds\x22: [
        {
            \x22type\x22: \x22direct\x22
        }
    ]
}" | sudo tee /etc/sing-box/config.json > /dev/null
sudo docker run -d \
        -v /etc/sing-box:/etc/sing-box/ \
        --name sing-box \
        --restart unless-stopped \
        -p 80:80 \
        -p 80:80/udp \
        -p 443:443 \
        -p 443:443/udp \
        -p $port:$port \
        -p $port:$port/udp \
        --device /dev/net/tun \
        --cap-add NET_ADMIN \
        ghcr.io/sagernet/sing-box \
        -D /var/lib/sing-box \
        -C /etc/sing-box/ run
cat /etc/sing-box/config.json | sed 's/,/\n/g' | grep "password" | sed 's/:/\n/g' | sed '1d' | sed 's/}//g' | sed 's/"//g' | tr -d ' '
sudo reboot
```

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by ygxbnet** [comment]
我也遇到了这个问题，是因为 sing-box 目前 Docker 镜像的 [latest](https://github.com/SagerNet/sing-box/pkgs/container/sing-box) 标签是最新的开发版本，可能有 bug。

你把脚本中的镜像指定一个非开发版的镜像就可以了。

比如你可以把脚本中的这一行命令：

```shell
sudo docker pull ghcr.io/sagernet/sing-box:latest
```

替换成：

```shell
sudo docker pull ghcr.io/sagernet/sing-box:v1.8.5
```

这样应该就可以临时解决这个报错

**Comment by ygxbnet** [comment]
之前确实是放在稳定版的，但就 1.9.0 的测试版出来后就改了，不知道为什么。
我也觉得把 latest tag 放到最新稳定版上比较好，把 dev tag 放在最新的开发版

**Comment by nekohasekai** [comment]
由于 Docker 版本无法撤回，我们预计在 1.9.0 stable release 修复这个问题。
