### ISSUE TITLE
dhcp导致客户端崩溃

### ISSUE THREAD

**Issue by charliez0** [SagerNet/sing-box#1467]
### 操作系统

Windows

### 系统版本

24H2 Windows Feature Experience Pack 1000.26052.1100.0

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.9.0-alpha.8

Environment: go1.22.0 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 7b2abccc7f31123097945e318194616accd12494
CGO: disabled
```

### 描述

当使用dhcp://auto启动即可触发崩溃

### 重现方式

```json
{
  "dns": {
    "servers": [{
      "tag": "dhcp",
      "address": "dhcp://auto"
    }]
  }
}
```

### 日志

```shell
INFO[0000] router: updated default interface 以太网, index 15
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x137d17c]

goroutine 1 [running]:
github.com/sagernet/sing-box/transport/dhcp.(*Transport).updateServers(0xc000162820)
        /Users/sekai/Projects/sing-box/transport/dhcp/server.go:155 +0x15c
github.com/sagernet/sing-box/transport/dhcp.(*Transport).fetchServers(0xc000162820)
        /Users/sekai/Projects/sing-box/transport/dhcp/server.go:146 +0x114
github.com/sagernet/sing-box/transport/dhcp.(*Transport).Start(0xc000162820)
        /Users/sekai/Projects/sing-box/transport/dhcp/server.go:73 +0x1c
github.com/sagernet/sing-box/route.(*Router).Start(0xc000170008)
        /Users/sekai/Projects/sing-box/route/router.go:625 +0x1876
github.com/sagernet/sing-box.(*Box).preStart(0xc00012a3c0)
        /Users/sekai/Projects/sing-box/box.go:273 +0x7c7
github.com/sagernet/sing-box.(*Box).start(0xc00012a3c0)
        /Users/sekai/Projects/sing-box/box.go:277 +0x2a
github.com/sagernet/sing-box.(*Box).Start(0xc00012a3c0)
        /Users/sekai/Projects/sing-box/box.go:219 +0x36
main.create()
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:160 +0x472
main.run()
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:174 +0x10c
main.init.func24(0xc000126700?, {0x16962c6?, 0x4?, 0x16962ca?})
        /Users/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:30 +0x17
github.com/spf13/cobra.(*Command).execute(0x22c3cc0, {0xc00010a1a0, 0x2, 0x2})
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x22c3fa0)
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /Users/sekai/Projects/sing-box/cmd/sing-box/main.go:38 +0x1e
```

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by charliez0** [comment]
另外在windows下dns设置成local也貌似有一定的问题，这个要等多久才能修复啊😭

**Comment by nekohasekai** [comment]
应已在最新版本中修复。

**Comment by nekohasekai** [comment]
> 这个要等多久才能修复啊😭

打开一个新的 issue。

**Comment by charliez0** [comment]
@nekohasekai 问题仍然没有得到解决
```plain
FATAL[0000] start service: initialize DNS server[2]: create UDP transport from DHCP result: 192.168.0.1: invalid server address
```

**Comment by charliez0** [comment]
另外如果在address指定不带协议的ip地址，如"192.168.0.1"，则会报错如下：
```plain
FATAL[0000] create service: parse route options: parse dns server[local]: invalid server address
```
换成"udp://192.168.0.1"即可恢复正常，怀疑上面问题与此有关

**Comment by charliez0** [comment]
另外如果在address指定不带协议的ip地址，如"192.168.0.1"，则会报错如下：
```plain
FATAL[0000] create service: parse route options: parse dns server[local]: invalid server address
```
换成"udp://192.168.0.1"即可恢复正常，怀疑上面问题与此有关

**Comment by charliez0** [comment]
问题已经解决
