### ISSUE TITLE
panic: sync/atomic: store of inconsistently typed value into Value

### ISSUE THREAD

**Issue by rsyslogd** [SagerNet/sing-box#1585]
### 操作系统

iOS

### 系统版本

windows 11

### 安装类型

sing-box 原始命令行程序

### 如果您使用图形客户端程序，请提供该程序版本。

v6.33

### 版本

```shell
v1.8.8
```

### 描述

+0800 2024-03-16 10:23:53 INFO [2435045117 0ms] inbound/http[http]: inbound connection to content-autofill.googleapis.com:443
+0800 2024-03-16 10:23:53 INFO [2435045117 2ms] outbound/socks[proxy]: outbound connection to content-autofill.googleapis.com:443
panic: sync/atomic: store of inconsistently typed value into Value
goroutine 600 [running]:
sync/atomic.(*Value).Store(0xc00036cb60, {0x10cb960, 0xc000aa45a0})
	sync/atomic/value.go:78 +0xd5
github.com/sagernet/sing/common/atomic.(*TypedValue[...]).Store(...)
	github.com/sagernet/sing@v0.3.5/common/atomic/typed.go:22
github.com/sagernet/sing/protocol/http.HandleConnection.func1.1()
	github.com/sagernet/sing@v0.3.5/protocol/http/handshake.go:130 +0xc8
created by github.com/sagernet/sing/protocol/http.HandleConnection.func1 in goroutine 599
	github.com/sagernet/sing@v0.3.5/protocol/http/handshake.go:127 +0x20a
开始更新 Core...
sing_box v1.8.8 已是最新版本。

### 重现方式

间歇性发生

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by rsyslogd** [comment]
v2rayN 6.33
NaiveProxy
