### ISSUE TITLE
TProxy 模式下 UDP 连接爆炸

### ISSUE THREAD

**Issue by pierre-primary** [SagerNet/sing-box#1586]
### 操作系统

Linux

### 系统版本

PVE8.0-LXC-alpine:3.19.1; x86_64; 内核: 6.5.13-1 

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.8.9

Environment: go1.22.1 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: e27fb51b54ffab1a4cf0045da84133c7a4dfa976
CGO: disabled
```

### 描述

起因：
    开始使用 TUN 模式，一切正常；但隐隐感觉有延迟；所有改用 TProxy

使用 TProxy 后：
1. 有时手动重启后，内存瞬间 100%，再次重启后恢复
2. 不定时也会出现内存占用100%的情况；重启后恢复

检测：
1. lsof | grep 'sing-box' | wc -l 查看到文件描述符2W+没释放。
2. netstat 和 ss 未发现异常连接。（很奇怪，文件描述符还在，连接没了，可能我错过了）

猜测：
TProxy 下，UDP 响应开Socket成本略高。且全局DNS劫持，导致 UDP 特别多（家里设备多，乱七八糟什么请求都有，每个瞬间都保持DNS请求在50个以上）。

解决：
用 DNS-IN 代替 DNS 拦截，规则 DNS-OUT 只响应 DNS-IN 进入的请求；目前跑了半天没遇到问题。而且改用 DNS-IN，DNS 请求少了很多，剩5、6个

问题：
也不知道是不是问题，遇到了就报一下，不是问题就关闭吧，可能是我的负载有点大

### 重现方式

代理模式：TProxy(TCP+UDP)
DNS模式：DNS 全局劫持（nft 命中所有53端口，通过 TProxy 入站）

openrc-run 配置
```bash
#!/sbin/openrc-run

# shellcheck shell=sh disable=SC2034

root_dir=/opt/sing-box

name=$RC_SVCNAME
description="sing-box service"
supervisor="supervise-daemon"
command="$root_dir/bin/sing-box"
command_args="-D /var/lib/sing-box -c $root_dir/etc/config.json run"

depend() {
    after net dns
}

reload() {
    ebegin "Reloading $RC_SVCNAME"
    /bin/kill -HUP "$MAINPID"
    eend $?
}

start_post() {
    $root_dir/shell/proxy.sh
}

stop_pre() {
    $root_dir/shell/proxy.sh down
}
```

TProxy 设置
```bash
#!/bin/sh

# 透明代理配置
TPROXY_PORT=9001 # 代理服务端口
PROXY_MARK=1     # 代理流量标记
OUTPUT_MARK=255  # 直接出站流量标记 (对应 sing-box 配置中的 outbound.routing_mark 或 route.default_mark)

RULE_COUNTER=""
# RULE_COUNTER="counter"

# 清除旧规则
cleanup() {
    nft flush ruleset >/dev/null 2>&1
    ip route del local default table 100 >/dev/null 2>&1
    ip rule del fwmark $PROXY_MARK table 100 >/dev/null 2>&1
}

# 设置新规则
setup() {
    ip rule add fwmark $PROXY_MARK table 100
    ip route add local default dev lo table 100
    nft -f - <<EOF
table ip sing-box-v4 {
    # IPv4 保留地址 (不会广域网使用的地址，无须代理)
    # 0.0.0.0/8 不被分配给任何主机或者网络接口，一般不会用于目标地址
    # 它代表了未知或不确定的目标，常作为默认路由
    # 但在某些情况下， 0.0.0.0 也用来表示对所有的本地接口广播
    # 其它: * 表示必须的保留地址；- 表示家庭网络中基本不用的地址;
    set RESERVED_IPSET {
        type ipv4_addr
        flags interval
        auto-merge # 自动合并，避免重复报错
        elements = {
            0.0.0.0/8,          # * 未知目标地址
            10.0.0.0/8,         # * A 类私有保留地址
            100.64.0.0/10,      # * 运营商保留地址
            127.0.0.0/8,        # * 本地回环接口地址
            169.254.0.0/16,     # * DHCP 保留地址
            172.16.0.0/12,      # * B 类私有保留地址
            192.0.0.0/24,       # - IANA 保留地址
            192.0.2.0/24,       # - 测试网络 (TEST-NET)
            198.18.0.0/15,      # - 网间通信测试网络
            198.51.100.0/24,    # - 测试网络 (TEST-NET-2)
            192.88.99.0/24,     # - 6to4 任播中继，已废弃
            192.168.0.0/16,     # * C 类私有保留地址
            203.0.113.0/24,     # - 测试网络 (TEST-NET-3)
            224.0.0.0/4,        # * 多播地址
            240.0.0.0/4,        # - 研究测试保留，除了 255.255.255.255
            255.255.255.255/32  # * 全局广播地址
        }
    }

    # 局域网透明代理
    chain prerouting {
        type filter hook prerouting priority mangle; policy accept;

        # 绕过应答流量
        ct direction reply $RULE_COUNTER accept comment "Optimize: Reply Packets"

        # 优化已经建立 TCP 透明代理连接；使用系统记录的Socket，将流量直接送入协议栈
        ip protocol tcp socket transparent 1 $RULE_COUNTER meta mark set $PROXY_MARK accept comment "Optimize: Just re-route established TCP proxy connections"
                
        # 劫持所有 DNS；DNS 请求比较多，TProxy 成本高，不建议使用；建议直接开一个 DNS-INBOUND
        udp dport 53 $RULE_COUNTER tproxy to 127.0.0.1:$TPROXY_PORT meta mark set $PROXY_MARK accept comment "Proxy: DNS(UDP) Hijack"

        # 绕过发往保留地址的流量
        ip daddr @RESERVED_IPSET $RULE_COUNTER accept comment "Bypass: Reserved Address"

        # 绕过发往本机地址的流量 (如果保留地址包含了所有本机接口，可以忽略此规则)
        # fib daddr type local $RULE_COUNTER accept comment "Bypass: Local Address"

        # 转发到代理服务
        ip protocol { tcp, udp } $RULE_COUNTER tproxy to 127.0.0.1:$TPROXY_PORT meta mark set $PROXY_MARK accept comment "Proxy: Default"
    }

    # 本机透明代理
    chain output {
        type route hook output priority mangle; policy accept;

        # 绕过应答流量
        ct direction reply $RULE_COUNTER accept comment "Optimize: Reply Packets"

        # 绕过代理程序出站流量
        meta mark $OUTPUT_MARK $RULE_COUNTER accept comment "Bypass: Proxy Output"

        # 重路由 DNS(UDP) 出站流量; DNS 请求比较多，TProxy 成本高，不建议使用；建议直接开一个 DNS-INBOUND
        udp dport 53 $RULE_COUNTER meta mark set $PROXY_MARK accept comment "Re-route: DNS(UDP) Output"

        # 绕过发往保留地址的流量
        ip daddr @RESERVED_IPSET $RULE_COUNTER accept comment "Bypass: Reserved Address"

        # 绕过发往本机地址的流量 (如果保留地址包含了所有本机接口，可以忽略此规则)
        # fib daddr type local $RULE_COUNTER accept comment "Bypass: Local Address"
        
        # 重路由默认出站流量; 需配合策略路由
        ip protocol { tcp, udp } $RULE_COUNTER meta mark set $PROXY_MARK accept comment "Re-route: Default Output"
    }
}
EOF
}

cleanup
if [ "$1" = "down" ]; then
    exit 0
fi
setup

```

### 日志

```shell
日志我只开了 WARN，不详细


+0800 2024-03-16 14:53:55 ERROR [3102736530 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:59692: upload: splice write: connection timed out
+0800 2024-03-16 14:53:55 ERROR [1736526249 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:50566: upload: splice write: connection timed out
+0800 2024-03-16 14:53:56 ERROR [2709799482 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:59710: upload: splice write: connection timed out
+0800 2024-03-16 14:53:56 ERROR [3924683744 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:59696: upload: splice write: connection timed out
+0800 2024-03-16 14:57:22 ERROR [317450079 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:62871: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 15:09:56 ERROR [1646888839 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:38150: upload: splice write: connection timed out
+0800 2024-03-16 15:18:44 ERROR [326551131 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:33706: upload: splice write: connection timed out
+0800 2024-03-16 15:19:50 ERROR [1564521370 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:56415: dial tcp 20.44.10.123:443: i/o timeout
+0800 2024-03-16 15:19:58 ERROR [1107371200 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:56594: dial tcp 20.44.10.123:443: i/o timeout
+0800 2024-03-16 15:24:57 ERROR [2154746761 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:48968: upload: splice write: connection timed out
+0800 2024-03-16 15:27:07 ERROR [2362868476 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:58085: dial tcp 20.44.10.123:443: i/o timeout
+0800 2024-03-16 15:48:51 ERROR [2776204048 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:53426: dial tcp 20.54.24.246:443: i/o timeout
+0800 2024-03-16 15:53:58 ERROR [1377012102 5m0s] inbound/tproxy[1]: process connection from 10.10.1.12:56108: upload: splice write: connection timed out
+0800 2024-03-16 15:58:18 ERROR [2319155540 7.26s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 15:58:46 ERROR [2746393072 33.44s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 16:09:45 ERROR [586973371 8m25s] inbound/tproxy[1]: process connection from 10.10.1.12:42798: upload: splice read: connection timed out
+0800 2024-03-16 16:09:50 ERROR [2953069102 8m23s] inbound/tproxy[1]: process connection from 10.10.1.12:43602: upload: raw read: connection timed out
+0800 2024-03-16 16:23:12 ERROR [1801812318 15m54s] inbound/tproxy[1]: process connection from 10.10.1.12:52818: upload: raw read: connection timed out
+0800 2024-03-16 16:23:14 ERROR [918206176 15m54s] inbound/tproxy[1]: process connection from 10.10.1.12:49486: upload: splice read: connection timed out
+0800 2024-03-16 16:23:14 ERROR [1429338753 15m54s] inbound/tproxy[1]: process connection from 10.10.1.12:49480: upload: splice read: connection timed out
+0800 2024-03-16 16:23:14 ERROR [2744468798 15m54s] inbound/tproxy[1]: process connection from 10.10.1.12:49470: upload: splice read: connection timed out
+0800 2024-03-16 16:32:16 ERROR [19756900 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:57402: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 16:32:20 ERROR [131778767 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:57447: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 16:32:33 ERROR [2342980479 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:57618: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 16:32:38 ERROR [2681682468 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:57878: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 16:33:04 ERROR [3218166384 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:58323: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 16:50:05 ERROR [297041695 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:56759: dial tcp 20.42.73.27:443: i/o timeout
+0800 2024-03-16 16:50:20 ERROR [2613102107 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:56927: dial tcp 20.42.73.27:443: i/o timeout
+0800 2024-03-16 16:51:49 ERROR [4032647967 6m36s] inbound/tproxy[1]: process connection from 10.10.1.12:56448: upload: raw read: connection timed out
+0800 2024-03-16 16:52:19 ERROR [3123778001 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:58484: dial tcp 20.42.73.27:443: i/o timeout
+0800 2024-03-16 16:54:44 ERROR [873463590 9m37s] inbound/tproxy[1]: process connection from 10.10.1.12:44510: upload: splice write: connection timed out
+0800 2024-03-16 16:56:04 ERROR [3202914982 5.0s] inbound/tproxy[1]: process connection from 10.10.1.10:59449: dial tcp 20.42.73.27:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [1562495718 5.51s] inbound/tproxy[1]: process connection from 10.10.1.10:54462: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [3999562241 5.52s] inbound/tproxy[1]: process connection from 10.10.1.10:54474: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [3924045930 5.44s] inbound/tproxy[1]: process connection from 10.10.1.10:54485: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [3289500935 5.38s] inbound/tproxy[1]: process connection from 10.10.1.10:54470: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [1749105397 5.64s] inbound/tproxy[1]: process connection from 10.10.1.10:54463: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [3203303084 5.65s] inbound/tproxy[1]: process connection from 10.10.1.10:54475: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:02:53 ERROR [3113049069 5.36s] inbound/tproxy[1]: process connection from 10.10.1.10:54498: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:03:05 ERROR [74179352 7.27s] inbound/tproxy[1]: process connection from 10.10.1.10:54930: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:03:15 ERROR [2750895352 15.37s] inbound/tproxy[1]: process connection from 10.10.1.10:54964: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:03:15 ERROR [1318058268 16.13s] inbound/tproxy[1]: process connection from 10.10.1.10:54962: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:03:19 ERROR [2294578278 16.47s] inbound/tproxy[1]: process connection from 10.10.1.10:54970: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:03:27 ERROR [3024544841 27.3s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:03:29 ERROR [2169099208 15.1s] inbound/tproxy[1]: process connection from 10.10.1.10:55489: dial tcp 20.44.248.140:443: i/o timeout
+0800 2024-03-16 17:03:31 ERROR [1990832165 28.75s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:03:40 ERROR [2270471873 22.9s] inbound/tproxy[1]: process connection from 10.10.1.10:55533: dial tcp 20.44.248.140:443: i/o timeout
panic: send on closed channel

goroutine 181 [running]:
github.com/sagernet/sing-dns.(*myTransportAdapter).recvLoop.func1({0x165e0f0?, 0xc0008387d0?})
        github.com/sagernet/sing-dns@v0.1.12/transport_base.go:101 +0xfc
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.3.6/common/task/task.go:91 +0x107
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 169
        github.com/sagernet/sing@v0.3.6/common/task/task.go:75 +0x198
+0800 2024-03-16 17:24:23 ERROR [1166621763 21m20s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:24:46 ERROR [2794568112 21m27s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:32:14 ERROR dns: exchange failed for ipv6.msftconnecttest.com. IN A: dial udp 10.10.1.5:53: i/o timeout
+0800 2024-03-16 17:34:11 ERROR dns: exchange failed for www.msftconnecttest.com. IN A: dial udp 10.10.1.5:53: i/o timeout
+0800 2024-03-16 17:32:27 ERROR [2934528943 29m18s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:35:13 ERROR [3696904983 31m52s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:35:46 ERROR [549574721 32m28s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 17:37:47 ERROR [2103794277 34m51s] outbound/urltest[🎈 自动选择]: context deadline exceeded
+0800 2024-03-16 18:01:25 ERROR [1585499529 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:62049: dial tcp 52.168.117.173:443: i/o timeout
+0800 2024-03-16 18:20:14 ERROR [3357396718 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:51361: dial tcp 13.89.179.9:443: i/o timeout
+0800 2024-03-16 18:22:22 ERROR [3574093143 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:54980: dial tcp 13.89.179.9:443: i/o timeout
+0800 2024-03-16 18:32:41 ERROR [3377479718 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:57619: dial tcp 204.79.197.239:443: i/o timeout
+0800 2024-03-16 18:35:16 ERROR [1230784 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:61587: dial tcp 20.54.24.246:443: i/o timeout
+0800 2024-03-16 18:36:56 ERROR [3974591704 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:63836: dial tcp 20.205.243.166:443: i/o timeout
+0800 2024-03-16 18:39:55 ERROR [3256463053 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:58310: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 18:39:57 ERROR [428803473 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:58336: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 18:40:10 ERROR [3132584884 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:58484: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 18:40:36 ERROR [3285420049 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:58780: dial tcp 52.182.141.63:443: i/o timeout
+0800 2024-03-16 18:43:23 ERROR [1751296606 18m36s] inbound/tproxy[2]: process connection from 10.10.1.12:50182: upload: splice write: connection timed out
+0800 2024-03-16 18:53:03 ERROR [3927356413 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:62448: dial tcp 40.126.16.163:443: i/o timeout
+0800 2024-03-16 18:53:28 ERROR [808509271 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:63510: dial tcp 40.126.16.163:443: i/o timeout
+0800 2024-03-16 18:53:36 ERROR [1789718496 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:63704: dial tcp 20.166.126.56:443: i/o timeout
+0800 2024-03-16 18:53:48 ERROR [2197807184 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:63973: dial tcp 20.166.126.56:443: i/o timeout
+0800 2024-03-16 18:54:18 ERROR [3823631248 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:53699: dial tcp 40.126.16.163:443: i/o timeout
+0800 2024-03-16 18:54:18 ERROR [697406702 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:53700: dial tcp 40.126.16.163:443: i/o timeout
+0800 2024-03-16 19:09:22 ERROR [1735843311 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:60925: dial tcp 13.89.179.9:443: i/o timeout
+0800 2024-03-16 19:10:25 ERROR [1943345876 5.0s] inbound/tproxy[2]: process connection from 10.10.1.10:62343: dial tcp 40.126.35.86:443: i/o timeout
+0800 2024-03-16 19:14:59 ERROR [2254993854 16m58s] inbound/tproxy[2]: process connection from 10.10.1.12:59110: upload: splice write: connection timed out
+0800 2024-03-16 19:14:59 ERROR [330643699 16m58s] inbound/tproxy[2]: process connection from 10.10.1.12:43770: upload: splice write: connection timed out
+0800 2024-03-16 19:14:59 ERROR [4199619561 16m58s] inbound/tproxy[2]: process connection from 10.10.1.12:59126: upload: splice write: connection timed out
+0800 2024-03-16 19:14:59 ERROR [3569544632 16m58s] inbound/tproxy[2]: process connection from 10.10.1.12:38912: upload: splice write: connection timed out
+0800 2024-03-16 19:14:59 ERROR [611503023 16m59s] inbound/tproxy[2]: process connection from 10.10.1.12:59128: upload: splice write: connection timed out
+0800 2024-03-16 19:14:59 ERROR [1795456996 16m59s] inbound/tproxy[2]: process connection from 10.10.1.12:38888: upload: splice write: connection timed out
+0800 2024-03-16 19:15:00 ERROR [2977871033 16m59s] inbound/tproxy[2]: process connection from 10.10.1.12:43758: upload: splice write: connection timed out
+0800 2024-03-16 19:15:00 ERROR [3935493972 17m0s] inbound/tproxy[2]: process connection from 10.10.1.12:43754: upload: splice write: connection timed out
+0800 2024-03-16 19:15:00 ERROR [888132780 16m59s] inbound/tproxy[2]: process connection from 10.10.1.12:38862: upload: splice write: connection timed out
+0800 2024-03-16 19:15:09 ERROR [2873356718 17m4s] inbound/tproxy[2]: process connection from 10.10.1.12:38950: upload: splice write: connection timed out
```
```


### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by ldzhjn** [comment]
@pierre-primary 

> 用 DNS-IN 代替 DNS 拦截，规则 DNS-OUT 只响应 DNS-IN 进入的请求

请问这个具体是怎么设置的？
按照你的描述 我是这么配置的
开机直接内存100%卡死...重启也一样
```
{
  "dns": {
    "servers": [
      {
        "tag": "nodedns",
        "address": "tls://223.5.5.5:853",
        "detour": "direct"
      },
      {
        "tag": "fakeipDNS",
        "address": "fakeip"
      }
     ],
     "rules": [
        "server": "nodedns",
        "disable_cache": true
      },
      {
        "inbound": "dns-in",
        "server": "fakeipDNS",
        "disable_cache": false,
        "rewrite_ttl": 1
      },
      {
        "outbound": "any",
        "server": "nodedns",
        "disable_cache": true
      }
      ],
      "fakeip": {
        "enabled": true,
        "inet4_range": "198.18.0.0/15" 
      },
        "strategy": "ipv4_only",
        "independent_cache": true
  },
  "inbounds": [
      {
        "type": "mixed",
        "listen": "0.0.0.0",
        "listen_port": 7890,
        "always_resolve_udp": true,
        "sniff": true,
        "users": []
      },
      {
        "type": "direct",
        "tag": "dns-in",
        "listen": "::",
        "listen_port": 53
      },
      {
        "type": "tproxy",
        "tag": "tproxy-in",
        "listen": "::",
        "listen_port": 7896,
        "tcp_fast_open": true,
        "udp_fragment": true,
        "sniff": true,
        "sniff_override_destination": false,
        "always_resolve_udp": true,
        "sniff_timeout": "100ms",
        "udp_timeout": 100
      }
  ],
  "outbounds": [
      {
         "tag": "direct",
         "type": "direct"
      },
      {
         "tag": "dns-out",
         "type": "dns"
      }
    ],
    "route": {
      "rules": [
      {
        "inbound": "dns-in",
        "outbound": "dns-out"
      },
      {
        "clash_mode": "direct",
        "outbound": "direct"
      }
    ]
    }
  }
```

**Comment by pierre-primary** [comment]
@ldzhjn  没什么特殊的
```json
{
    "log": {
        "level": "warn",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "block",
                "address": "rcode://name_error"
            },
            {
                "tag": "local-dns",
                "address": "10.10.1.5",
                "detour": "direct"
            },
            {
                "tag": "remote-dns-ipv4",
                "address": "tls://1.1.1.1",
                "strategy": "ipv4_only",
                "detour": "proxy"
            }
        ],
        "rules": [
            {
                "outbound": "any",
                "server": "local-dns",
                "disable_cache": true
            },
            {
                "rule_set": ["geosite:private", "geosite:cn"],
                "server": "local-dns"
            },
            {
                "network": ["tcp", "udp"],
                "server": "remote-dns-ipv4"
            }
        ],
        "final": "local-dns"
    },
    "inbounds": [
        {
            "type": "direct",
            "tag": "dns-in",
            "listen": "::",
            "listen_port": 53
        },
        {
            "type": "mixed",
            "listen": "::",
            "listen_port": 9000,
            "tcp_fast_open": true,
            "udp_fragment": false,
            "sniff": true
        },
        {
            "type": "tproxy",
            "listen": "127.0.0.1",
            "listen_port": 9001,
            "udp_fragment": false,
            "sniff": true
        }
    ],
    "outbounds": [
        {
            "type": "dns",
            "tag": "dns-out"
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "tag": "proxy"
        }
    ],
    "route": {
        "rules": [
            {
                "inbound": "dns-in",
                "outbound": "dns-out"
            },
            {
                "network": "udp",
                "port": 443,
                "outbound": "block"
            }
        ],
        "final": "direct",
        "auto_detect_interface": true,
        "default_mark": 255
    },
    "experimental": {
        "cache_file": {
            "enabled": true
        }
    }
}
```

**Comment by redapricot** [comment]
@pierre-primary 请问这个问题彻底解决了吗？我这边也出现了与你描述类似的问题。
想寻求个解决方案，感谢！

**Comment by yzxiu** [comment]
1.9.4 版本，也遇到过这个问题

**Comment by maosasagawa** [comment]
在安卓1.10.0也依旧有这个问题，有的订阅会出现，有的订阅能正常使用
