### ISSUE TITLE
sing-box randomly panics

### ISSUE THREAD

**Issue by Utaea** [SagerNet/sing-box#1612]
### Operating system

Linux

### System version

OpenSUSE Tumbleweed 20240315

### Installation type

Original sing-box Command Line

### Version

```shell
v1.8.0, v1.8.9, v1.9.0-beta.17
```

### Description

Sing-box works fine at first, but it will randomly panic within 1-2 days. There seems to be no obvious reason for the panic. I have sing-box with the same version and similar config running in same environment on other environment, but that works fine. I have no idea in figuring out this. According to the log, this seems to be related to `sing` package, please feel free to transfer this issue to `sing` if necessary.

### Reproduction

Here's the sing-box config:

```json
{
    "inbounds": [
        {
            "fallback": {
                "server": "fe2.update.microsoft.com",
                "server_port": 80
            },
            "listen": "0.0.0.0",
            "listen_port": 2666,
            "tag": "trojan-multiport-in",
            "tls": {
                "certificate_path": "/tmp/conf/server.crt",
                "enabled": true,
                "key_path": "/tmp/conf/server.key"
            },
            "type": "trojan",
            "users": []
        },
        {
            "listen": "::",
            "listen_port": 26666,
            "method": "aes-128-gcm",
            "password": "<redacted>",
            "tag": "ss-in",
            "type": "shadowsocks"
        },
        {
            "listen": "::",
            "listen_port": 38888,
            "method": "aes-128-gcm",
            "password": "<redacted>",
            "tag": "ss-in",
            "type": "shadowsocks",
            "users": [
                {
                    "name": "default",
                    "password": "<redacted>"
                }
            ]
        },
        {
            "fallback": {
                "server": "fe2.update.microsoft.com",
                "server_port": 80
            },
            "listen": "0.0.0.0",
            "listen_port": 9443,
            "tag": "trojan-in",
            "tls": {
                "certificate_path": "/tmp/conf/server.crt",
                "enabled": true,
                "key_path": "/tmp/conf/server.key"
            },
            "type": "trojan",
            "users": []
        },
        {
            "listen": "::",
            "listen_port": 9666,
            "tag": "vmess-in",
            "tls": {
                "certificate_path": "/tmp/conf/server.crt",
                "enabled": true,
                "key_path": "/tmp/conf/server.key"
            },
            "transport": {
                "service_name": "<redacted>",
                "type": "grpc"
            },
            "type": "vmess",
            "users": []
        },
        {
            "detour": "vmess-in-inline-forward",
            "down_mbps": 200,
            "ignore_client_bandwidth": false,
            "listen": "::",
            "listen_port": 22443,
            "masquerade": "https://www.example.com",
            "tag": "hy2-in-cn-forward",
            "tls": {
                "certificate_path": "/tmp/conf/server.crt",
                "enabled": true,
                "key_path": "/tmp/conf/server.key"
            },
            "type": "hysteria2",
            "up_mbps": 200,
            "users": [
                {
                    "name": "default",
                    "password": "<redacted>"
                }
            ]
        },
        {
            "tag": "vmess-in-inline-forward",
            "type": "vmess",
            "users": []
        }
    ],
    "log": {
        "disabled": false,
        "level": "warning"
    }
}
```

### Logs

After some time of running sing-box will panic and produce the following output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x821665]
goroutine 75999 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Len(...)
        github.com/sagernet/sing@v0.4.0-beta.3/common/buf/buffer.go:327
github.com/sagernet/sing/common/bufio.copyPacketWaitWithPool({0x7f35c1dd9d28, 0xc000a0f1d0}, {0x7f35c1de00c8, 0xc00055be00}, {0x165d908, 0xc000>
        github.com/sagernet/sing@v0.4.0-beta.3/common/bufio/copy_direct.go:72 +0x145
github.com/sagernet/sing/common/bufio.CopyPacket({0x7f35c1de00c8?, 0xc00055be00?}, {0x7f35c1dd9d28, 0xc000a0f1d0})
        github.com/sagernet/sing@v0.4.0-beta.3/common/bufio/copy.go:240 +0x448
github.com/sagernet/sing/common/bufio.CopyPacketConnContextList.func2({0xc000c19f50?, 0xd8a501?})
        github.com/sagernet/sing@v0.4.0-beta.3/common/bufio/copy.go:331 +0x68
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.4.0-beta.3/common/task/task.go:91 +0x107
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 76016
        github.com/sagernet/sing@v0.4.0-beta.3/common/task/task.go:75 +0x198
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nekohasekai** [comment]
Try 1.9.0-rc.2
