### ISSUE TITLE
运行部分时间后就会出现这部分信息，在终端中运行

### ISSUE THREAD

**Issue by GOD-XINGCHEN** [SagerNet/sing-box#1721]
### 操作系统

Android

### 系统版本

12

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.9.0-rc.13                                                                                  Environment: go1.22.2 android/arm64                    Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api                                                 Revision: 3341b622697646f5d5f62d1c08b180aaf445beae     CGO: enabled
```

### 描述

goroutine 55827 [running]:                             github.com/gobwas/pool/internal/pmath.CeilToPowerOfTwo(0x8?)                                                          github.com/gobwas/pool@v0.2.1/internal/pmath/pmath.go:34 +0x80                                        github.com/gobwas/pool.(*Pool).Get(0x4000054060, 0x4a385ee185f2daeb)                                                  github.com/gobwas/pool@v0.2.1/generic.go:63 +0x30                                                     github.com/gobwas/pool/pbytes.(*Pool).Get(0x4000463018?, 0x4a385ee185f2daeb, 0x4003126400?)                           github.com/gobwas/pool@v0.2.1/pbytes/pool.go:33 +0x30                                                 github.com/gobwas/pool/pbytes.(*Pool).GetLen(...)              github.com/gobwas/pool@v0.2.1/pbytes/pool.go:58github.com/gobwas/pool/pbytes.GetLen(...)                      github.com/gobwas/pool@v0.2.1/pbytes/pbytes.go:20                                                     github.com/sagernet/ws/wsutil.ControlHandler.HandleClose({{0x62d1189e20, 0x4002674d80}, {0x707cb88cb0, 0x40031bde48}, 0x2, 0x1}, {0x0, 0x7, 0x8, 0x0, ...})                  github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/handler.go:156 +0xd4                 github.com/sagernet/ws/wsutil.ControlHandler.Handle({{0x62d1189e20, 0x4002674d80}, {0x707cb88cb0, 0x40031bde48}, 0x2, 0x1}, {0x0, 0x7, 0x8, 0x0, ...})                       github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/handler.go:64 +0xd4                  github.com/sagernet/sing-box/transport/v2raywebsocket.NewConn.ControlFrameHandler.func1({0x0, 0x7, 0x8, 0x0, {0x0, 0x0, 0x0, 0x0}, 0x4a385ee185f2dadd}, {0x62d1189e20?, ...})                                                       github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/helper.go:244 +0x74                  github.com/sagernet/ws/wsutil.(*Reader).NextFrame(0x4002674d20)                                                       github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/reader.go:212 +0x27c                 github.com/sagernet/ws/wsutil.(*Reader).Discard(0x4002674d20)                                                         github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/reader.go:154 +0x6c                  github.com/sagernet/sing-box/transport/v2raywebsocket.(*WebsocketConn).Read(0x40007eff40, {0x40012823c0, 0x12, 0x40})                                                        github.com/sagernet/sing-box/transport/v2raywebsocket/conn.go:84 +0xf0                                github.com/sagernet/sing-box/transport/v2raywebsocket.(*EarlyWebsocketConn).Read(0x4000463388?, {0x40012823c0?, 0x38?, 0x62d10cc320?})                                       github.com/sagernet/sing-box/transport/v2raywebsocket/conn.go:145 +0x68                               io.ReadAtLeast({0x708002f0f8, 0x400238a980}, {0x40012823c0, 0x12, 0x40}, 0x12)                                        io/io.go:335 +0xa0                             io.ReadFull(...)                                               io/io.go:354                                   github.com/sagernet/sing/common/buf.(*Buffer).ReadFullFrom(0x4002386a80, {0x708002f0f8?, 0x400238a980?}, 0x62d002a971?)                                                      github.com/sagernet/sing@v0.4.0-beta.18/common/buf/buffer.go:167 +0x74                                github.com/sagernet/sing-vmess.(*rawClientConn).readResponse(0x40017b8280)                                            github.com/sagernet/sing-vmess@v0.1.8/client.go:359 +0x260                                            github.com/sagernet/sing-vmess.(*clientConn).Read(0x40017b8280, {0x4001511680, 0x240, 0x240})                         github.com/sagernet/sing-vmess@v0.1.8/client.go:431 +0x38                                             crypto/tls.(*atLeastReader).Read(0x40031bdec0, {0x4001511680?, 0x0?, 0x40031bdec0?})                                  crypto/tls/conn.go:806 +0x40                   bytes.(*Buffer).ReadFrom(0x40011ba630, {0x62d118b840, 0x40031bdec0})                                                  bytes/buffer.go:211 +0x90                      crypto/tls.(*Conn).readFromUntil(0x40011ba388, {0x707cb8fca8, 0x40017b8280}, 0x0?)                                    crypto/tls/conn.go:828 +0xd0                   crypto/tls.(*Conn).readRecordOrCCS(0x40011ba388, 0x0)          crypto/tls/conn.go:626 +0x35c                  crypto/tls.(*Conn).readRecord(...)                             crypto/tls/conn.go:588                         crypto/tls.(*Conn).readHandshakeBytes(0x40011ba388, 0x4)                                                              crypto/tls/conn.go:1075 +0x60                  crypto/tls.(*Conn).readHandshake(0x40011ba388, {0x0, 0x0})                                                            crypto/tls/conn.go:1086 +0x30                  crypto/tls.(*Conn).clientHandshake(0x40011ba388, {0x62d119b380, 0x4004c46320})                                        crypto/tls/handshake_client.go:223 +0x1ec      crypto/tls.(*Conn).handshakeContext(0x40011ba388, {0x62d119b3f0, 0x400471e7e0})                                       crypto/tls/conn.go:1553 +0x338                 crypto/tls.(*Conn).HandshakeContext(...)                       crypto/tls/conn.go:1493                        net/http.(*persistConn).addTLS.func2()                         net/http/transport.go:1573 +0x6c               created by net/http.(*persistConn).addTLS in goroutine 55826                                                          net/http/transport.go:1569 +0x284

### 重现方式

运行一会就这样了，Android终端 zerotemux

### 日志

```shell
goroutine 55827 [running]:                             github.com/gobwas/pool/internal/pmath.CeilToPowerOfTwo(0x8?)                                                          github.com/gobwas/pool@v0.2.1/internal/pmath/pmath.go:34 +0x80                                        github.com/gobwas/pool.(*Pool).Get(0x4000054060, 0x4a385ee185f2daeb)                                                  github.com/gobwas/pool@v0.2.1/generic.go:63 +0x30                                                     github.com/gobwas/pool/pbytes.(*Pool).Get(0x4000463018?, 0x4a385ee185f2daeb, 0x4003126400?)                           github.com/gobwas/pool@v0.2.1/pbytes/pool.go:33 +0x30                                                 github.com/gobwas/pool/pbytes.(*Pool).GetLen(...)              github.com/gobwas/pool@v0.2.1/pbytes/pool.go:58github.com/gobwas/pool/pbytes.GetLen(...)                      github.com/gobwas/pool@v0.2.1/pbytes/pbytes.go:20                                                     github.com/sagernet/ws/wsutil.ControlHandler.HandleClose({{0x62d1189e20, 0x4002674d80}, {0x707cb88cb0, 0x40031bde48}, 0x2, 0x1}, {0x0, 0x7, 0x8, 0x0, ...})                  github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/handler.go:156 +0xd4                 github.com/sagernet/ws/wsutil.ControlHandler.Handle({{0x62d1189e20, 0x4002674d80}, {0x707cb88cb0, 0x40031bde48}, 0x2, 0x1}, {0x0, 0x7, 0x8, 0x0, ...})                       github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/handler.go:64 +0xd4                  github.com/sagernet/sing-box/transport/v2raywebsocket.NewConn.ControlFrameHandler.func1({0x0, 0x7, 0x8, 0x0, {0x0, 0x0, 0x0, 0x0}, 0x4a385ee185f2dadd}, {0x62d1189e20?, ...})                                                       github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/helper.go:244 +0x74                  github.com/sagernet/ws/wsutil.(*Reader).NextFrame(0x4002674d20)                                                       github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/reader.go:212 +0x27c                 github.com/sagernet/ws/wsutil.(*Reader).Discard(0x4002674d20)                                                         github.com/sagernet/ws@v0.0.0-20231204124109-acfe8907c854/wsutil/reader.go:154 +0x6c                  github.com/sagernet/sing-box/transport/v2raywebsocket.(*WebsocketConn).Read(0x40007eff40, {0x40012823c0, 0x12, 0x40})                                                        github.com/sagernet/sing-box/transport/v2raywebsocket/conn.go:84 +0xf0                                github.com/sagernet/sing-box/transport/v2raywebsocket.(*EarlyWebsocketConn).Read(0x4000463388?, {0x40012823c0?, 0x38?, 0x62d10cc320?})                                       github.com/sagernet/sing-box/transport/v2raywebsocket/conn.go:145 +0x68                               io.ReadAtLeast({0x708002f0f8, 0x400238a980}, {0x40012823c0, 0x12, 0x40}, 0x12)                                        io/io.go:335 +0xa0                             io.ReadFull(...)                                               io/io.go:354                                   github.com/sagernet/sing/common/buf.(*Buffer).ReadFullFrom(0x4002386a80, {0x708002f0f8?, 0x400238a980?}, 0x62d002a971?)                                                      github.com/sagernet/sing@v0.4.0-beta.18/common/buf/buffer.go:167 +0x74                                github.com/sagernet/sing-vmess.(*rawClientConn).readResponse(0x40017b8280)                                            github.com/sagernet/sing-vmess@v0.1.8/client.go:359 +0x260                                            github.com/sagernet/sing-vmess.(*clientConn).Read(0x40017b8280, {0x4001511680, 0x240, 0x240})                         github.com/sagernet/sing-vmess@v0.1.8/client.go:431 +0x38                                             crypto/tls.(*atLeastReader).Read(0x40031bdec0, {0x4001511680?, 0x0?, 0x40031bdec0?})                                  crypto/tls/conn.go:806 +0x40                   bytes.(*Buffer).ReadFrom(0x40011ba630, {0x62d118b840, 0x40031bdec0})                                                  bytes/buffer.go:211 +0x90                      crypto/tls.(*Conn).readFromUntil(0x40011ba388, {0x707cb8fca8, 0x40017b8280}, 0x0?)                                    crypto/tls/conn.go:828 +0xd0                   crypto/tls.(*Conn).readRecordOrCCS(0x40011ba388, 0x0)          crypto/tls/conn.go:626 +0x35c                  crypto/tls.(*Conn).readRecord(...)                             crypto/tls/conn.go:588                         crypto/tls.(*Conn).readHandshakeBytes(0x40011ba388, 0x4)                                                              crypto/tls/conn.go:1075 +0x60                  crypto/tls.(*Conn).readHandshake(0x40011ba388, {0x0, 0x0})                                                            crypto/tls/conn.go:1086 +0x30                  crypto/tls.(*Conn).clientHandshake(0x40011ba388, {0x62d119b380, 0x4004c46320})                                        crypto/tls/handshake_client.go:223 +0x1ec      crypto/tls.(*Conn).handshakeContext(0x40011ba388, {0x62d119b3f0, 0x400471e7e0})                                       crypto/tls/conn.go:1553 +0x338                 crypto/tls.(*Conn).HandshakeContext(...)                       crypto/tls/conn.go:1493                        net/http.(*persistConn).addTLS.func2()                         net/http/transport.go:1573 +0x6c               created by net/http.(*persistConn).addTLS in goroutine 55826                                                          net/http/transport.go:1569 +0x284
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by nekohasekai** [comment]
日志不完整
