### ISSUE TITLE
`1.9.0-rc.13`及以上版本Linux环境下运行hysteria2入站会发生Panic崩溃

### ISSUE THREAD

**Issue by Perplexed5040** [SagerNet/sing-box#1732]
### 操作系统

Linux

### 系统版本

Alpine Linux v3.19

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.9.0-rc.14

Environment: go1.22.2 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: b2111b8683aaa4ccebb4e46338ea9cf5560ef59e
CGO: disabled
```

### 描述

发生Panic崩溃，进程退出。

### 重现方式

1. sing-box版本在`1.9.0-rc.13`及以上
2. 服务端hysteria2入站启用ech
3. 服务端hysteria2入站有连接传入
4. 服务端发生Panic崩溃，进程退出

### 日志

```shell
+0900 2024-05-01 13:40:07 INFO router: updated default interface eth0, index 2
+0900 2024-05-01 13:40:07 INFO inbound/direct[_dns_in]: udp server started at 127.0.0.1:53
+0900 2024-05-01 13:40:07 INFO inbound/socks[_socks_in]: tcp server started at 127.0.0.1:1080
+0900 2024-05-01 13:40:07 INFO inbound/hysteria2[_hy2_in]: udp server started at [::]:23333
+0900 2024-05-01 13:40:07 INFO sing-box started (0.33s)
panic: interface conversion: interface {} is nil, not quic.ConnectionTracingID

goroutine 65 [running]:
github.com/sagernet/quic-go/http3.(*Server).handleRequest.func1(0x401, {0x0, 0x0})
        github.com/sagernet/quic-go@v0.43.0-beta.2/http3/server.go:473 +0xb8
github.com/sagernet/quic-go/http3.parseNextFrame({0x7fc5f14ccc78, 0xc0000ef140}, 0xc0000e9f60)
        github.com/sagernet/quic-go@v0.43.0-beta.2/http3/frames.go:39 +0x118
github.com/sagernet/quic-go/http3.(*Server).handleRequest(0xc0000c2e70, 0xc0002c4a50, {0x1493618, 0xc0000ef140}, 0xc0002c4cd0, 0xc0001246c0)
        github.com/sagernet/quic-go@v0.43.0-beta.2/http3/server.go:479 +0xe5
created by github.com/sagernet/quic-go/http3.(*Server).handleConn in goroutine 59
        github.com/sagernet/quic-go@v0.43.0-beta.2/http3/server.go:456 +0x2bb
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [x] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Nicker222** [comment]
相同情况，在最新commit修改依赖
```
	github.com/sagernet/quic-go v0.42.0-beta.3
	github.com/sagernet/sing-quic v0.1.13-beta.1
```
回退到`https://github.com/SagerNet/quic-go/tree/v0.42.0-beta.3`这个版本
并回退一些相关的代码到`v1.9.0-rc.12`可正常运行
