### ISSUE TITLE
keeps crashing in Dashboard tab

### ISSUE THREAD

**Issue by douniwan5788** [SagerNet/sing-box#1894]
### Operating system

Android

### System version

N/A

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.10.0-alpha.17

### Description

keeps crashing in Dashboard tab

### Reproduction

tag contains emoji. Especially 2️⃣ 

### Logs

```shell
panic: runtime error: makeslice: len out of range

goroutine 70 [running]:
github.com/sagernet/sing/common/varbin.read({0x79063a99b8, 0x4000120180}, {0x79063b9390, 0x7906bded00}, {0x790618ba20?, 0x4000216190?, 0x40000cb238?})
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/varbin/data.go:98 +0x794
github.com/sagernet/sing/common/varbin.read({0x79063a99b8, 0x4000120180}, {0x79063b9390, 0x7906bded00}, {0x79062ec6a0?, 0x4000216180?, 0x199?})
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/varbin/data.go:183 +0x6c0
github.com/sagernet/sing/common/varbin.read({0x79063a99b8, 0x4000120180}, {0x79063b9390, 0x7906bded00}, {0x79061c1d80?, 0x400022c3e0?, 0x400025ca98?})
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/varbin/data.go:89 +0x158
github.com/sagernet/sing/common/varbin.read({0x79063a99b8, 0x4000120180}, {0x79063b9390, 0x7906bded00}, {0x79061786e0?, 0x40001ba000?, 0x197?})
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/varbin/data.go:150 +0xb48
github.com/sagernet/sing/common/varbin.Read({0x79063a4ec0?, 0x40001264e8?}, {0x79063b9390, 0x7906bded00}, {0x79061786a0, 0x40001ba000})
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/varbin/data.go:45 +0x5d0
github.com/sagernet/sing/common/varbin.ReadValue[...]({0x79063a4ec0, 0x40001264e8}, {0x79063b9390, 0x7906bded00})
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/varbin/data.go:50 +0x60
github.com/sagernet/sing-box/experimental/libbox.readGroups({0x79063a4ec0?, 0x40001264e8?})
	github.com/sagernet/sing-box/experimental/libbox/command_group.go:102 +0x44
github.com/sagernet/sing-box/experimental/libbox.(*CommandClient).handleGroupConn(0x40003103f0, {0x79063bb178, 0x40001264e8})
	github.com/sagernet/sing-box/experimental/libbox/command_group.go:22 +0xbc
created by github.com/sagernet/sing-box/experimental/libbox.(*CommandClient).Connect in goroutine 135
	github.com/sagernet/sing-box/experimental/libbox/command_client.go:106 +0x678
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by douniwan5788** [comment]
fixed？
