### ISSUE TITLE
[Android] crashing/panic randomly in Tun mode with logging enabled

### ISSUE THREAD

**Issue by douniwan5788** [SagerNet/sing-box#1895]
### Operating system

Android

### System version

N/A

### Installation type

sing-box for Android Graphical Client

### If you are using a graphical client, please provide the version of the client.

1.10.0-alpha.17

### Description

The VPN randomly stops

### Reproduction

Tun mode with logging enabled. It seems to no longer crash after disabling logging

### Logs

```shell
panic: unknown ref 0

goroutine 1727 [running]:
github.com/sagernet/gomobile/bind/seq.(*Ref).Get(0x7900000000?)
	github.com/sagernet/gomobile@v0.1.3/bind/seq/ref.go:118 +0x188
main.proxylibbox_CommandServer_WriteMessage(0x5fb688?, {0xb40000788904d400, 0x78, {0x0, 0x0, 0x0, 0x0}})
	github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:379 +0x20
main._Cfunc_cproxylibbox_PlatformInterface_WriteLog(0x2c, {0xb40000788904d400, 0xf0, {0x0, 0x0, 0x0, 0x0}})
	_cgo_gotypes.go:1108 +0x30
main.(*proxylibbox_PlatformInterface).WriteLog.func1(0x40002a6018, {0xb40000788904d400, 0xf0, {0x0, 0x0, 0x0, 0x0}})
	github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:3257 +0x78
main.(*proxylibbox_PlatformInterface).WriteLog(0x40002a6018, {0x4000734c00?, 0x7903724acb?})
	github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:3257 +0x44
github.com/sagernet/sing-box/experimental/libbox.(*platformInterfaceWrapper).WriteMessage(0xc1972836d00cd05b?, 0x65?, {0x4000734c00?, 0xc1972834e7c7b95f?})
	github.com/sagernet/sing-box/experimental/libbox/service.go:237 +0x34
github.com/sagernet/sing-box/log.(*observableLogger).Log(0x40005240d8, {0x79045aa158, 0x400054c9f0}, 0x74?, {0x400023c980, 0x2, 0x2})
	github.com/sagernet/sing-box/log/observable.go:139 +0x410
github.com/sagernet/sing-box/log.(*observableLogger).InfoContext(0x790453c7e0?, {0x79045aa158?, 0x400054c9f0?}, {0x400023c980?, 0x40005fbbc8?, 0x79038da104?})
	github.com/sagernet/sing-box/log/observable.go:180 +0x38
github.com/sagernet/sing-box/inbound.(*Tun).NewPacketConnection(0x4000148388, {0x79045aa158?, 0x40001640f0?}, {0x79045af8e0, 0x400022cfd0}, {{0x0, 0x0}, {{{0x0, 0xffffac130001}, 0x400000e0a8}, ...}, ...})
	github.com/sagernet/sing-box/inbound/tun.go:423 +0x188
github.com/sagernet/sing/common/udpnat.(*Service[...]).NewContextPacket.func2()
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/udpnat/service.go:82 +0x98
created by github.com/sagernet/sing/common/udpnat.(*Service[...]).NewContextPacket in goroutine 1425
	github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/udpnat/service.go:81 +0x2b4




panic: unknown ref 0

goroutine 1088 [running]:
github.com/sagernet/gomobile/bind/seq.(*Ref).Get(0x4000000000?)
        github.com/sagernet/gomobile@v0.1.3/bind/seq/ref.go:118 +0x188
main.proxylibbox_CommandServer_WriteMessage(0x7eb5b8?, {0xb4000078a2922b80, 0x9a, {0x0, 0x0, 0x0, 0x0}})
        github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:379 +0x20
main._Cfunc_cproxylibbox_PlatformInterface_WriteLog(0x2c, {0xb4000078a2922b80, 0x134, {0x0, 0x0, 0x0, 0x0}})
        _cgo_gotypes.go:1108 +0x30
main.(*proxylibbox_PlatformInterface).WriteLog.func1(0x400035805c, {0xb4000078a2922b80, 0x134, {0x0, 0x0, 0x0, 0x0}})
        github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:3257 +0x78
main.(*proxylibbox_PlatformInterface).WriteLog(0x400035805c, {0x40000160a0?, 0x790371d68c?})
        github.com/sagernet/sing-box/build/arm64/libbox/go_libboxmain.go:3257 +0x44
github.com/sagernet/sing-box/experimental/libbox.(*platformInterfaceWrapper).WriteMessage(0xc1972bb58df20964?, 0xcf?, {0x40000160a0?, 0xc1972bae2efd4874?})
        github.com/sagernet/sing-box/experimental/libbox/service.go:237 +0x34
github.com/sagernet/sing-box/log.(*observableLogger).Log(0x4000608138, {0x79045b2158, 0x400028e3c0}, 0x9c?, {0x40000898c0, 0x2, 0x2})
        github.com/sagernet/sing-box/log/observable.go:139 +0x410
github.com/sagernet/sing-box/log.(*observableLogger).DebugContext(0x79045a31a0?, {0x79045b2158?, 0x400028e3c0?}, {0x40000898c0?, 0x8?, 0x2f5807467b?})
        github.com/sagernet/sing-box/log/observable.go:176 +0x38
github.com/sagernet/sing-box/inbound.NewError({0x79045c1268, 0x4000608138}, {0x79045b2158, 0x400028e3c0}, {0x79045a31a0, 0x40005ba270})
        github.com/sagernet/sing-box/inbound/default.go:192 +0x1d4
github.com/sagernet/sing-box/inbound.(*Tun).NewError(...)
        github.com/sagernet/sing-box/inbound/tun.go:433
github.com/sagernet/sing-box/inbound.(*Tun).NewPacketConnection(0x40001a3888, {0x79045b2158?, 0x40003c8210?}, {0x79045b78e0, 0x40006f6000}, {{0x0, 0x0}, {{{0x0, 0xffffac130001}, 0x400000e0a8}, ...}, ...})
        github.com/sagernet/sing-box/inbound/tun.go:427 +0x284
github.com/sagernet/sing/common/udpnat.(*Service[...]).NewContextPacket.func2()
        github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/udpnat/service.go:82 +0x98
created by github.com/sagernet/sing/common/udpnat.(*Service[...]).NewContextPacket in goroutine 275
        github.com/sagernet/sing@v0.5.0-alpha.11.0.20240624055149-4745c34b4c70/common/udpnat/service.go:81 +0x2b4
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by douniwan5788** [comment]
fixed？
