### ISSUE TITLE
Wireguard under tun mode crashed 

### ISSUE THREAD

**Issue by debiansid** [SagerNet/sing-box#197]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

wireguard under tun mode panic 

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1-beta12

Environment: go1.19.2 android/arm64
Tags: with_gvisor,with_quic,with_wireguard,with_clash_api
Revision: 6e8c4f6576c508c8dfea472aacd2922961274ba6
CGO: disabled
```

</details>

### Server and client configuration file

normal wireguard setup 

### Server and client log file

<details>

```console
# paste log here
panic: send on closed channel

goroutine 17690 [running]:
github.com/sagernet/sing-box/transport/wireguard.(*wireEndpoint).WritePackets(0x40000a9e00, {{0x4000856108, 0x1, 0x1}})
	github.com/sagernet/sing-box/transport/wireguard/device_stack.go:249 +0x6c
gvisor.dev/gvisor/pkg/tcpip/stack.(*delegatingQueueingDiscipline).WritePacket(0x400027cf00, 0x4001014640)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:152 +0xa0
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writeRawPacket(0x400028c200, 0x4001014640)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:396 +0x34
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writePacket(0x400028c200, 0x0?)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:392 +0x40
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).WritePacket(0x400028c200, 0x40000004d8?, 0x4001014640)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:353 +0x148
gvisor.dev/gvisor/pkg/tcpip/network/ipv6.(*endpoint).writePacket(0x4000205b00, 0x40016a4500, 0x4001014640, 0x0?, 0x0?)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/network/ipv6/ipv6.go:863 +0x3d4
gvisor.dev/gvisor/pkg/tcpip/network/ipv6.(*endpoint).WritePacket(0x4000205b00, 0x40016a4500, {0x86dd?, 0xfc?, 0xef?}, 0x42dc006d?)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/network/ipv6/ipv6.go:814 +0x204
gvisor.dev/gvisor/pkg/tcpip/stack.(*Route).WritePacket(0x40016a4500, {0x2814b0?, 0x40?, 0x0?}, 0x10?)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/route.go:468 +0x78
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.sendTCP(0x40016a4500, {{0xeffc, {0x40002814b0, 0x10}, 0x1bb, {0x4000f14cc0, 0x10}}, 0x40, 0x0, 0x2, ...}, ...)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:911 +0x19c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendTCP(0x4000e19800, 0x61bf644f80?, {{0xeffc, {0x40002814b0, 0x10}, 0x1bb, {0x4000f14cc0, 0x10}}, 0x40, 0x0, ...}, ...)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:809 +0x8c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendSynTCP(0x4000e19800, 0x40016a4500, {{0xeffc, {0x40002814b0, 0x10}, 0x1bb, {0x4000f14cc0, 0x10}}, 0x40, 0x0, ...}, ...)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:799 +0x184
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*handshake).start(0x40016438c0)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:574 +0x238
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).connect(0x4000e19800, {0x0?, {0x4000f14cc0?, 0x0?}, 0x1?}, 0x1)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/endpoint.go:2431 +0x3d8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).Connect(0x4000e19800, {0x162510?, {0x4000f14cc0?, 0x0?}, 0xdc1e?})
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/endpoint.go:2158 +0x88
gvisor.dev/gvisor/pkg/tcpip/adapters/gonet.DialTCPWithBind({0x61bf00c5e0, 0x4000a0f050}, 0x10?, {0xbe5abd48?, {0x40002814b0?, 0x61be5dee0a?}, 0x1000?}, {0xaa?, {0x4000f14cc0?, 0x61be5ac11c?}, ...}, ...)
	gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/adapters/gonet/gonet.go:514 +0x2c0
github.com/sagernet/sing-box/transport/wireguard.(*StackDevice).DialContext(0x40000a9e00, {0x61bf00c5e0, 0x4000a0f050}, {0x61be416a8d, 0x3}, {{{0x2606470030360000, 0x68153bc2}, 0x400000e048}, 0x1bb, {0x0, ...}})
	github.com/sagernet/sing-box/transport/wireguard/device_stack.go:110 +0x208
github.com/sagernet/sing-box/outbound.(*WireGuard).DialContext(0x4000194c00, {0x61bf00c5e0, 0x4000a0f050}, {0x61be416a8d, 0x3}, {{{0x2606470030360000, 0x68153bc2}, 0x400000e048}, 0x1bb, {0x0, ...}})
	github.com/sagernet/sing-box/outbound/wireguard.go:151 +0x324
github.com/sagernet/sing/common/network.DialSerial({0x61bf00c5e0, 0x4000a0f050}, {0x61bf0045f8, 0x4000194c00}, {0x61be416a8d, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, ...}, ...)
	github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/network/multi.go:24 +0x1b0
github.com/sagernet/sing-box/outbound.NewConnection({_, _}, {_, _}, {_, _}, {{0x40001e0d20, 0x6}, {0x61be416a99, 0x3}, ...})
	github.com/sagernet/sing-box/outbound/default.go:46 +0x108
github.com/sagernet/sing-box/outbound.(*WireGuard).NewConnection(_, {_, _}, {_, _}, {{0x40001e0d20, 0x6}, {0x61be416a99, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box/outbound/wireguard.go:160 +0x6c
github.com/sagernet/sing-box/outbound.(*Selector).NewConnection(_, {_, _}, {_, _}, {{0x40001e0d20, 0x6}, {0x61be416a99, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box/outbound/selector.go:127 +0x5c
github.com/sagernet/sing-box/route.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0x40001e0d20, 0x6}, {0x61be416a99, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box/route/router.go:603 +0xf1c
github.com/sagernet/sing-box/inbound.(*Tun).NewConnection(0x40000fdd40, {0x61bf00c570?, 0x4000044060?}, {0x61bf015d58, 0x40002ec668}, {{0x0, 0x0}, {{{0x0, 0xffffac130001}, 0x400000e030}, ...}, ...})
	github.com/sagernet/sing-box/inbound/tun.go:188 +0x254
github.com/sagernet/sing-tun.(*System).acceptLoop.func1()
	github.com/sagernet/sing-tun@v0.0.0-20221028015259-ea5c35f62f07/system.go:197 +0x10c
created by github.com/sagernet/sing-tun.(*System).acceptLoop
	github.com/sagernet/sing-tun@v0.0.0-20221028015259-ea5c35f62f07/system.go:196 +0x31c


</details>

**Comment by nekohasekai** [comment]
Try 904937d1dd969e2005e23a7ad4d344b2c23d723a

**Comment by zakuwaki** [comment]
> Try [904937d](https://github.com/SagerNet/sing-box/commit/904937d1dd969e2005e23a7ad4d344b2c23d723a)

This commit introduces a new bug.

```console
sing-box version 1.1-beta12

Environment: go1.19.3 linux/amd64
Tags: with_wireguard,with_utls,with_gvisor
Revision: 6e8c4f6576c508c8dfea472aacd2922961274ba6
CGO: disabled
```

After I apply this patch, call `systemctl restart sing-box` will cause process hangs.

```
Nov 04 20:11:51 RN sing[1896]: ERROR[0142] [57006924] inbound/trojan[in-trojan]: process connection from x.x.x.x:42290: session shutdown | upstream: context canceled
Nov 04 20:11:51 RN systemd[1]: Stopping Sing Service...
```

**Comment by nekohasekai** [comment]
Try 0ad1bbea11618f138577ca3345832763cd997a05
