### ISSUE TITLE
tuic报错和断流

### ISSUE THREAD

**Issue by nightyin** [SagerNet/sing-box#2036]
### Operating system

Linux

### System version

linux-6.4.0

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version v1.10.0-alpha.28 & v1.10.0-alpha.29

Environment: go1.23.0 linux/amd64

测了两个版本
```

### Description

在nginx STREAM中监听 在一个server块监听443tcp和udp就会出现这个问题

### Reproduction

   stream{
   .........
    
    server {
        listen 443 ;
        listen 443 udp
        proxy_pass $stream_map;
        ssl_preread on;
    }
}

### Logs

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12170d2]

goroutine 20690 [running]:
github.com/sagernet/sing-box/outbound.(*loopBackDetector).NewConn(0xc00007d310, {0x0, 0x0})
 /app/outbound/direct_loopback_detect.go:30 +0x32
github.com/sagernet/sing-box/outbound.(*Direct).DialContext(0xc0001fd450, {0x1932998?, 0xc00067cba0?}, {0x16e69dd, 0x3}, {{{0x0, 0x0}, {0x0}}, 0x1bb, {0xc000c514e0, ...}})
 /app/outbound/direct.go:97 +0x4f5
github.com/sagernet/sing-box/outbound.NewConnection({_, _}, {_, _}, {_, _}, {{0xc0001c8040, 0x7}, {0x16e71fb, 0x4}, ...})
 /app/outbound/default.go:67 +0x192
github.com/sagernet/sing-box/outbound.(*Direct).NewConnection(_, {_, _}, {_, _}, {{0xc0001c8040, 0x7}, {0x16e71fb, 0x4}, 0x0, ...})
 /app/outbound/direct.go:162 +0x247
github.com/sagernet/sing-box/route.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0xc0001c8040, 0x7}, {0x16e71fb, 0x4}, 0x0, ...})
 /app/route/router.go:914 +0x17f3
github.com/sagernet/sing-box/common/uot.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0xc0001c8040, 0x7}, {0x16e71fb, 0x4}, 0x0, ...})
 /app/common/uot/router.go:48 +0x15b
github.com/sagernet/sing-box/inbound.(*TUIC).newConnection(_, {_, _}, {_, _}, {{0xc0001c8040, 0x7}, {0x16e71fb, 0x4}, 0x0, ...})
 /app/inbound/tuic.go:109 +0x3f5
github.com/sagernet/sing-box/adapter.(*myUpstreamHandlerWrapper).NewConnection(0xc0001483c0, {0x1932998, 0xc00067ca20}, {0x193c508, 0xc0005a2168}, {{0x0, 0x0}, {{{0x0, 0xffffac0a0002}, {0xc000010480}}, ...}, ...})
 /app/adapter/upstream.go:48 +0x32e
github.com/sagernet/sing-quic/tuic.(*serverSession[...]).handleStream(0x1949d80, {0x7f04384b2498, 0xc0006456c0})
 /go/pkg/mod/github.com/sagernet/sing-quic@v0.2.0-beta.12/tuic/service.go:366 +0x97d
github.com/sagernet/sing-quic/tuic.(*serverSession[...]).loopStreams.func1()
 /go/pkg/mod/github.com/sagernet/sing-quic@v0.2.0-beta.12/tuic/service.go:322 +0x45
created by github.com/sagernet/sing-quic/tuic.(*serverSession[...]).loopStreams in goroutine 71
 /go/pkg/mod/github.com/sagernet/sing-quic@v0.2.0-beta.12/tuic/service.go:321 +0x3c
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by nightyin** [comment]
目前从a.29版本开始到现在的beta.4 第一次ping是通的 第二次ping就必不通 也没有日志信息。 已经切回a.28版本
