### ISSUE TITLE
1.10.0-beta.1 crash

### ISSUE THREAD

**Issue by vanes32** [SagerNet/sing-box#2047]
### Operating system

Linux

### System version

RouterOS 7.15.3

### Installation type

Others

### Version

```shell
1.10.0-beta.1
```

### Description

I use sing-box in RouterOS container. Version [1.10.0-alpha.29] works great, new 1.10.0-beta.1 crash after few minutes

### Reproduction

`config.json`
```
{
  "log": {
    "disabled": false,
    "level": "error",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_ui": "ui",
      "external_controller": "0.0.0.0:9090",
      "external_ui_download_detour": "direct",
      "default_mode": "rule"
    }
  },
  "dns": {
    "servers": [
      {
        "tag": "local-dns",
        "address": "tls://77.88.8.8",
        "detour": "direct"
      },
      {
        "tag": "fakeip-dns",
        "address": "fakeip"
      },
      {
        "tag": "comss-dns",
        "address": "https://dns.controld.com/comss",
        "address_resolver": "local-dns",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "rule_set": [
          "microsoft"
        ],
        "server": "comss-dns"
      },
      {
        "domain_suffix": [
          "gemini.google.com",
          "aitestkitchen.withgoogle.com"
        ],
        "server": "comss-dns"
      },
      {
        "domain_suffix": [
          "whoer.net",
          "kinozal.tv",
          "rutracker.org",
          "rutracker.cc",
          "clamav.net",
          "veeam.com",
          "ntc.party",
          "strava.com",
          "servarr.com",
          "prowlarr.com"
        ],
        "server": "fakeip-dns"
      },
      {
        "domain_suffix": [
          "lgtvonline.lge.com",
          "ngfts.lge.com",
          "lgtvsdp.com",
          "lgeapi.com",
          "lgsmartad.com",
          "lgappstv.com",
          "aws-prd.net",
          "lgtvcommon.com"
        ],
        "server": "fakeip-dns"
      },
      {
        "rule_set": [
          "twitter",
          "facebook",
          "instagram",
          "openai",
          "tmdb",
          "intel",
          "medium",
          "adguard",
          "youtube"
        ],
        "server": "fakeip-dns"
      }
    ],
    "strategy": "ipv4_only",
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15"
    },
    "disable_cache": true,
    "final": "local-dns"
  },
  "inbounds": [
    {
      "type": "tun",
      "inet4_address": "172.19.0.1/30",
      "stack": "system",
      "sniff": true,
      "auto_route": true,
      "sniff_override_destination": true,
      "strict_route": true,
      "gso": false
    },
    {
      "type": "direct",
      "listen": "::",
      "listen_port": 53,
      "sniff": true,
      "tag": "dns-in"
    }
  ],
  "route": {
    "rule_set": [
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "twitter",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/twitter.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "facebook",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/facebook.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "instagram",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/instagram.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "openai",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/openai.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "tmdb",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/tmdb.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "intel",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/intel.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "medium",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/medium.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "adguard",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/adguard.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "youtube",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/youtube.srs"
      },
      {
        "type": "remote",
        "format": "binary",
        "download_detour": "direct",
        "tag": "microsoft",
        "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/microsoft.srs"
      }
    ],
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "domain_suffix": [
          "whoer.net",
          "kinozal.tv",
          "rutracker.org",
          "rutracker.cc",
          "clamav.net",
          "veeam.com",
          "ntc.party",
          "strava.com",
          "servarr.com",
          "prowlarr.com"
        ],
        "outbound": "domains"
      },
      {
        "domain_suffix": [
          "lgtvonline.lge.com",
          "ngfts.lge.com",
          "lgtvsdp.com",
          "lgeapi.com",
          "lgsmartad.com",
          "lgappstv.com",
          "aws-prd.net",
          "lgtvcommon.com"
        ],
        "outbound": "lg-domains"
      },
      {
        "rule_set": [
          "twitter",
          "facebook",
          "instagram",
          "openai",
          "tmdb",
          "intel",
          "medium",
          "adguard"
        ],
        "outbound": "rulesets"
      },
      {
        "rule_set": [
          "youtube"
        ],
        "outbound": "youtube"
      },
      {
        "ip_is_private": true,
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true,
    "final": "direct"
  },
  "outbounds": [
    {
      "tag": "Proxy",
      "outbounds": [
        "vps"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "tag": "domains",
      "outbounds": [
        "Proxy"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "tag": "rulesets",
      "outbounds": [
        "Proxy"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "tag": "youtube",
      "outbounds": [
        "wg",
        "direct",
        "Proxy"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "tag": "lg-domains",
      "outbounds": [
        "wg",
        "direct",
        "Proxy"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "tag": "vps",
      "server": "xxxxx",
      "server_port": 443,
      "type": "vless",
      "uuid": "xxxxx",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "insecure": true,
        "server_name": "xxxxx",
        "reality": {
          "enabled": true,
          "public_key": "xxxxx",
          "short_id": "xxxxx"
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "wireguard",
      "tag": "wg",
      "server": "xxxxx",
      "server_port": 2408,
      "local_address": [
        "172.16.0.2/32"
      ],
      "private_key": "xxxxx",
      "peer_public_key": "xxxxx",
      "reserved": [
        0,
        0,
        0
      ],
      "mtu": 1420,
      "workers": 4
    }
  ]
}
```

### Logs

```shell
Aug/19/2024 12:44:25 container,info,debug panic: close of nil channel
Aug/19/2024 12:44:25 container,info,debug 
Aug/19/2024 12:44:25 container,info,debug goroutine 1114 [running]:
Aug/19/2024 12:44:25 container,info,debug github.com/sagernet/sing/common/pipe.(*Deadline).Set.func1()
Aug/19/2024 12:44:25 container,info,debug 	github.com/sagernet/sing@v0.5.0-alpha.18/common/pipe/pipe.go:58 +0x24
Aug/19/2024 12:44:25 container,info,debug created by time.goFunc
Aug/19/2024 12:44:25 container,info,debug 	time/sleep.go:215 +0x38
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by ghmajx** [comment]
I noticed the same thing, and after some testing I found that it might be related to the "stack": "system" option. If I change it to “mixed”, then it works.

**Comment by vanes32** [comment]
>  I change it to “mixed”, then it works.
I can confirm that it works

**Comment by ghmajx** [comment]
1.10.0-beta.2 seems to be working fine with "stack": "system" option now.
with 1.10-beta.1, it will restart in less than 2 minutes with the panic error.
```
Aug 19 16:36:53  sing-box[43054]: panic: close of nil channel
Aug 19 16:37:15  sing-box[43114]: panic: close of nil channel
Aug 19 16:38:03  sing-box[43158]: panic: close of nil channel
Aug 19 16:39:17  sing-box[43245]: panic: close of nil channel
Aug 19 16:40:14  sing-box[43343]: panic: close of nil channel
Aug 19 16:40:28  sing-box[43422]: panic: close of nil channel
Aug 19 16:42:20  sing-box[43577]: panic: close of nil channel
Aug 19 16:43:07  sing-box[43627]: panic: close of nil channel
Aug 19 16:43:34  sing-box[43699]: panic: close of nil channel
Aug 19 16:44:19  sing-box[43751]: panic: close of nil channel
Aug 19 16:45:05  sing-box[43871]: panic: close of nil channel
Aug 19 16:45:19  sing-box[43913]: panic: close of nil channel
Aug 19 16:46:01  sing-box[43949]: panic: close of nil channel
Aug 19 16:46:13  sing-box[44014]: panic: close of nil channel
Aug 19 16:46:26  sing-box[44049]: panic: close of nil channel
Aug 19 16:46:39  sing-box[44082]: panic: close of nil channel
Aug 19 16:46:51  sing-box[44114]: panic: close of nil channel
Aug 19 16:47:10  sing-box[44150]: panic: close of nil channel
Aug 19 16:47:31  sing-box[44195]: panic: close of nil channel
Aug 19 16:48:07  sing-box[44238]: panic: close of nil channel
Aug 19 16:50:29  sing-box[44298]: panic: close of nil channel
Aug 19 16:51:19  sing-box[44482]: panic: close of nil channel
Aug 19 16:51:43  sing-box[44654]: panic: close of nil channel
Aug 19 16:51:59  sing-box[44701]: panic: close of nil channel
Aug 19 16:52:12  sing-box[44743]: panic: close of nil channel
Aug 19 16:54:03  sing-box[44987]: panic: close of nil channel
Aug 19 16:55:04  sing-box[45022]: panic: close of nil channel
Aug 19 16:55:16  sing-box[45112]: panic: close of nil channel
Aug 19 16:56:00  sing-box[45144]: panic: close of nil channel
```
1.10.0-beta.2 has worked for more than 14 minutes now.
```
● sing-box.service - sing-box service
     Loaded: loaded (/usr/lib/systemd/system/sing-box.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-08-19 19:31:11 CST; 14min ago
```
