### ISSUE TITLE
多个tags编译后，运行报错

### ISSUE THREAD

**Issue by guigeng** [SagerNet/sing-box#21]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

编译选项：
 `go install -v -tags with_clash_api,with_quic github.com/sagernet/sing-box/cmd/sing-box@latest`
没有报错。

`sing-box run -c config.json`报错
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb25d12]

goroutine 1 [running]:
github.com/sagernet/sing-box/experimental/clashapi.(*Server).Close(0xc00008cbe0)
        /home/go/pkg/mod/github.com/sagernet/sing-box@v0.0.0-20220822075508-f755a346ce29/experimental/clashapi/server.go:107 +0x32
github.com/sagernet/sing/common.Close({0xc0000d9b38?, 0x4, 0x0?})
        /home/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220822075357-8b9965b73533/common/cond.go:324 +0xa4
github.com/sagernet/sing-box.(*Box).Close(0xc000286000)
        /home/go/pkg/mod/github.com/sagernet/sing-box@v0.0.0-20220822075508-f755a346ce29/box.go:232 +0x15b
github.com/sagernet/sing-box.(*Box).Start(0xc00019b0b0?)
        /home/go/pkg/mod/github.com/sagernet/sing-box@v0.0.0-20220822075508-f755a346ce29/box.go:173 +0x39
main.run()
        /home/go/pkg/mod/github.com/sagernet/sing-box@v0.0.0-20220822075508-f755a346ce29/cmd/sing-box/cmd_run.go:74 +0x23c
main.glob..func3(0x14b0340?, {0xdc47e8?, 0x2?, 0x2?})
        /home/go/pkg/mod/github.com/sagernet/sing-box@v0.0.0-20220822075508-f755a346ce29/cmd/sing-box/cmd_run.go:25 +0x1d
github.com/spf13/cobra.(*Command).execute(0x14b0340, {0xc000044a20, 0x2, 0x2})
        /home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x14b05c0)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/go/pkg/mod/github.com/sagernet/sing-box@v0.0.0-20220822075508-f755a346ce29/cmd/sing-box/main.go:29 +0x25
```

### Version of sing-box

<details>

```console
$ sing-box --version
# Paste output here
# sing-box version
sing-box 1.0 (go1.19, linux, amd64, CGO enabled)
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```
outbound只有hysteria服务器
单个tags正常运行，加了clash api报错
</details>

**Comment by nekohasekai** [comment]
Try 6253e2e24c76e0abdc572b3a0d3b4dd50f9a992c

**Comment by nekohasekai** [comment]
Try 6253e2e24c76e0abdc572b3a0d3b4dd50f9a992c
