### ISSUE TITLE
Crash while using vmess-in and vmess-out/vless-out combinations (slice bounds out of range)

### ISSUE THREAD

**Issue by meinthebox** [SagerNet/sing-box#212]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

In this case, the server acts as a relay role, both of the two combinations crash after a few seconds to minutes of use. Not much traffic, maybe just a few times of connection tests.

Tried vmess-in with socks-out, works perfectly.

### Version of sing-box

<details>

```console

/ # sing-box version
sing-box version 1.1-beta13

Environment: go1.19.3 linux/amd64
Tags: with_quic,with_wireguard,with_acme
CGO: disabled

Same result: 
1.1-beta11
1.1-beta12

```
</details>

### Server and client configuration file

<details>

```console

client config:

{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      {
        "address": "fakedns",
        "domains": [
          "geosite:cn"
        ]
      },
      "1.1.1.1"
    ]
  },
  "fakedns": [
    {
      "ipPool": "198.18.0.0/15",
      "poolSize": 10000
    }
  ],
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls",
          "fakedns"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "192.168.88.100",
            "port": 25002,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "583ef6a6-1111-1111-a291-111111111111",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "wsSettings": {
          "headers": {
            "Host": ""
          },
          "path": "/ghost"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

server config:

{
  "inbounds": [
    {
      "type": "mixed",
      "listen": "::",
      "listen_port": 1080
    },
    {
      "type": "vmess",
      "tag": "vmess-in",
      "listen": "::",
      "listen_port": 25002,
      "users": [
        {
          "name": "jullia",
          "uuid": "583ef6a6-1111-1111-a291-111111111111",
          "alterId": 0
        }
      ],
      "tls": {},
      "transport":{
        "type": "ws",
        "path": "/ghost",
        "headers": {},
        "max_early_data": 0,
        "early_data_header_name": ""
      }
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "vless-out",
      "server": "freedomserver.com",
      "server_port": 443,
      "uuid": "583ef6a6-1111-1111-a291-111111111111",
      "network": "tcp",
      "tls":
        {
          "enabled": true,
          "disable_sni": false,
          "server_name": "",
          "insecure": false,
          "alpn": [],
          "min_version": "",
          "max_version": "",
          "cipher_suites": [],
          "certificate": "",
          "certificate_path": "",
          "ech": {
             "enabled": false,
             "pq_signature_schemes_enabled": false,
             "dynamic_record_sizing_disabled": false,
             "config": ""
          },
          "utls": {
          "enabled": false,
          "fingerprint": ""
        }
      },
      "packet_encoding": "",
      "transport":{
        "type": "ws",
        "path": "/ghost",
        "headers": {},
        "max_early_data": 0,
        "early_data_header_name": ""
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "rules": [
      {
        "ip_cidr": [
          "192.168.88.0/24",
          "192.168.1.0/24",
          "172.16.0.1/24"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "cn",
        "geoip": "cn",
        "outbound": "direct"
      },
      {
        "geoip": "private",
        "outbound": "direct"
      }
    ]
  }
}

```

</details>

### Server and client log file

<details>

```console

(relay) server log:

INFO[0120] [3596479253] outbound/vless[vless-out]: outbound connection to rr2---sn-a5meknde.gvt1.com:443
panic: runtime error: slice bounds out of range [824634764032:824634762496]

goroutine 141 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Read(...)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/buf/buffer.go:280
github.com/sagernet/sing/common/bufio.(*CachedReader).Read(0xc0004e4450, {0xc0003a352a, 0x2, 0x2})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/cache.go:105 +0x165
io.ReadAtLeast({0x10ad400, 0xc0004e4450}, {0xc0003a352a, 0x2, 0x2}, 0x2)
        $GOROOT/src/io/io.go:332 +0x9a
io.ReadFull(...)
        $GOROOT/src/io/io.go:351
encoding/binary.Read({0x10ad400, 0xc0004e4450}, {0x10c1850, 0x1740e50}, {0xd6fd00?, 0xc0003a3528})
        $GOROOT/src/encoding/binary/binary.go:233 +0xc8
github.com/sagernet/sing-vmess.(*StreamChunkReader).Read(0xc000119ef0, {0xc0005d4021, 0x4000, 0x7fdf})
        pkg/mod/github.com/sagernet/sing-vmess@v0.0.0-20220925083655-063bc85ea685/chunk_length_stream.go:36 +0x89
github.com/sagernet/sing/common/bufio.(*ExtendedReaderWrapper).ReadBuffer(0x10000?, 0xc000323470)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/conn.go:141 +0x5d
github.com/sagernet/sing-vmess.(*AEADReader).ReadBuffer(0xc00003ea00, 0xc000323470)
        pkg/mod/github.com/sagernet/sing-vmess@v0.0.0-20220925083655-063bc85ea685/chunk_aead.go:54 +0x35
github.com/sagernet/sing/common/bufio.(*ChunkReader).ReadBuffer(0xe20c40?, 0xc00034ae80?)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/chunk.go:26 +0x150
github.com/sagernet/sing/common/bufio.CopyExtendedBuffer({0x10b41e0?, 0xc00034ae80}, {0x7f3068bd3428, 0xc0000cd100}, 0xc000595c80)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:112 +0x1b3
github.com/sagernet/sing/common/bufio.CopyExtended({0x10b41e0?, 0xc00034ae80}, {0x7f3068bd3428?, 0xc0000cd100})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:99 +0x2d4
github.com/sagernet/sing/common/bufio.Copy({0x7f3068b5f318, 0xc00012a0e0}, {0x10ad420?, 0xc0000cd100?})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:75 +0x394
github.com/sagernet/sing-vmess.(*serverConn).WriteTo(0x7f3068b5f318?, {0x7f3068b5f318, 0xc00012a0e0})
        pkg/mod/github.com/sagernet/sing-vmess@v0.0.0-20220925083655-063bc85ea685/service.go:465 +0x51
github.com/sagernet/sing/common/bufio.Copy({0x7f3068b5f318, 0xc00012a0e0}, {0x7f306929cb78?, 0xc0001140e0?})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:67 +0x18f
github.com/sagernet/sing/common/bufio.CopyConn.func1({0x0?, 0x0?})
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:191 +0x85
github.com/sagernet/sing/common/task.(*Group).Run.func1()
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/task/task.go:59 +0x93
created by github.com/sagernet/sing/common/task.(*Group).Run
        pkg/mod/github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/task/task.go:58 +0x54a





another log:

INFO[0003] [1040449508] outbound/vless[vless-out]: outbound connection to rr3---sn-o097znze.googlevideo.com:443
panic: runtime error: slice bounds out of range [824634200352:824634200320]

goroutine 100 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Read(...)
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/buf/buffer.go:280
github.com/sagernet/sing/common/bufio.(*CachedReader).Read(0xc0002269f0, {0xc0000417b6, 0x2, 0x2})
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/cache.go:105 +0x15b
io.ReadAtLeast({0x1085380, 0xc0002269f0}, {0xc0000417b6, 0x2, 0x2}, 0x2)
        io/io.go:331 +0x9a
io.ReadFull(...)
        io/io.go:350
encoding/binary.Read({0x1085380, 0xc0002269f0}, {0x1098890, 0x16fcde0}, {0xd524a0?, 0xc0000417b4})
        encoding/binary/binary.go:166 +0xc8
github.com/sagernet/sing-vmess.(*StreamChunkReader).Read(0xc00057e960, {0xc00070001c, 0x7fe4, 0x7fe4})
        github.com/sagernet/sing-vmess@v0.0.0-20220925083655-063bc85ea685/chunk_length_stream.go:36 +0x89
github.com/sagernet/sing/common/bufio.(*ExtendedReaderWrapper).ReadBuffer(0x10000?, 0xc00057ecc0)
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/conn.go:141 +0x5d
github.com/sagernet/sing-vmess.(*AEADReader).ReadBuffer(0xc00022d880, 0xc00057ecc0)
        github.com/sagernet/sing-vmess@v0.0.0-20220925083655-063bc85ea685/chunk_aead.go:54 +0x35
github.com/sagernet/sing/common/bufio.(*ChunkReader).ReadBuffer(0xdff880?, 0xc00031cf50?)
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/chunk.go:26 +0x150
github.com/sagernet/sing/common/bufio.CopyExtendedBuffer({0x108c028?, 0xc00031cf50}, {0x7f2ee40780d0, 0xc00004b6a0}, 0xc000306c80)
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:112 +0x1b3
github.com/sagernet/sing/common/bufio.CopyExtended({0x108c028?, 0xc00031cf50}, {0x7f2ee40780d0?, 0xc00004b6a0})
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:99 +0x2c5
github.com/sagernet/sing/common/bufio.Copy({0x7f2ed5fd7450, 0xc0000ed2d0}, {0x10853a0?, 0xc00004b6a0?})
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:75 +0x394
github.com/sagernet/sing-vmess.(*serverConn).WriteTo(0x7f2ed5fd7450?, {0x7f2ed5fd7450, 0xc0000ed2d0})
        github.com/sagernet/sing-vmess@v0.0.0-20220925083655-063bc85ea685/service.go:465 +0x51
github.com/sagernet/sing/common/bufio.Copy({0x7f2ed5fd7450, 0xc0000ed2d0}, {0x7f2ed5f7f8e0?, 0xc0000b7500?})
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:67 +0x18f
github.com/sagernet/sing/common/bufio.CopyConn.func1({0xc00005d718?, 0xc00005d7d0?})
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/bufio/copy.go:191 +0x85
github.com/sagernet/sing/common/task.(*Group).Run.func1()
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/task/task.go:59 +0x93
created by github.com/sagernet/sing/common/task.(*Group).Run
        github.com/sagernet/sing@v0.0.0-20221008120626-60a9910eefe4/common/task/task.go:58 +0x52d


```

</details>

**Comment by meinthebox** [comment]
> Try [7358ca4](https://github.com/SagerNet/sing-box/commit/7358ca4a526959e9708d15609ce93835eb7c6dfd)

Test for hours, it works!

Thank you.
