### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by b14aa178** [SagerNet/sing-box#2234]
### Operating system

Windows

### System version

Microsoft Windows 11 专业版版本	10.0.22631 版本 22631

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.10.1

Environment: go1.23.2 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: b80ec55ba0aafc60774e19c409e55ced50ddaab3
CGO: disabled
```

### Description

crash, and program exit.

### Reproduction

运行一会儿, 它可能就崩溃退出了.

### Logs

```shell
[36mINFO[0m[35116] [[38;5;159m3733059400[0m 0ms] router: found process path: C:\Program Files\Google\Chrome\Application\chrome.exe
[37mDEBUG[0m[35116] [[38;5;159m3733059400[0m 0ms] router: match[9] domain_suffix=[wikipedia.org javrate.com javtxt.com...] => proxy
[36mINFO[0m[35116] [[38;5;159m3733059400[0m 0ms] outbound/shadowsocks[hkproxy]: outbound connection to 142.251.33.74:443
[37mDEBUG[0m[35116] [[38;5;75m2247992891[0m 182ms] dns: exchange sp0.baidu.com. IN A
[37mDEBUG[0m[35116] [[38;5;75m2247992891[0m 182ms] dns: match[1] !(rule_set=geosite-geolocation-!cn) && rule_set=geosite-geolocation-cn => local
[37mDEBUG[0m[35116] [[38;5;75m2247992891[0m 209ms] dns: exchanged sp0.baidu.com NOERROR 78
[36mINFO[0m[35116] [[38;5;75m2247992891[0m 209ms] dns: exchanged sp0.baidu.com CNAME sp0.baidu.com. 78 IN CNAME www.a.shifen.com.
[36mINFO[0m[35116] [[38;5;75m2247992891[0m 209ms] dns: exchanged sp0.baidu.com A www.a.shifen.com. 78 IN A 111.206.208.133
[36mINFO[0m[35116] [[38;5;75m2247992891[0m 209ms] dns: exchanged sp0.baidu.com A www.a.shifen.com. 78 IN A 111.206.208.135
[36mINFO[0m[35116] [[38;5;46m281395742[0m 0ms] inbound/tun[2]: inbound connection from 172.19.0.1:10260
[36mINFO[0m[35116] [[38;5;46m281395742[0m 0ms] inbound/tun[2]: inbound connection to 111.206.208.133:443
[37mDEBUG[0m[35116] [[38;5;46m281395742[0m 0ms] router: sniffed protocol: tls, domain: sp0.baidu.com
[36mINFO[0m[35116] [[38;5;46m281395742[0m 0ms] router: found process path: C:\Program Files\Google\Chrome\Application\chrome.exe
[37mDEBUG[0m[35116] [[38;5;46m281395742[0m 0ms] router: match[14] rule_set=[geoip-cn geosite-geolocation-cn] => direct
[36mINFO[0m[35116] [[38;5;46m281395742[0m 0ms] outbound/direct[direct]: outbound connection to 111.206.208.133:443
[37mDEBUG[0m[35116] [[38;5;37m2269621484[0m 10.82s] inbound/tun[2]: connection closed: download: remote alert: use of closed network connection
panic: d.nx != 0

goroutine 56514 [running]:
crypto/sha1.(*digest).checkSum(0xc00109d220)
        crypto/sha1/sha1.go:169 +0x134
crypto/sha1.(*digest).Sum(0xc00098d5e0, {0x0, 0x0, 0x0})
        crypto/sha1/sha1.go:146 +0x9d
crypto/hmac.(*hmac).Sum(0xc000108b40, {0x0?, 0x0, 0x10?})
        crypto/hmac/hmac.go:58 +0x32
github.com/sagernet/sing-shadowtls.(*verifiedConn).write(0xc000485b90, {0xc000916000, 0x3b6, 0x8000})
        github.com/sagernet/sing-shadowtls@v0.1.4/v3_conn.go:123 +0xa2
github.com/sagernet/sing-shadowtls.(*verifiedConn).Write(0xc000485b90, {0xc000916000?, 0x3b6, 0x22b5f00?})
        github.com/sagernet/sing-shadowtls@v0.1.4/v3_conn.go:108 +0x3f
github.com/sagernet/sing-shadowsocks2/shadowaead_2022.(*clientConn).writeRequest(0xc00013d560, {0xc0014439c0, 0x40, 0x40})
        github.com/sagernet/sing-shadowsocks2@v0.2.0/shadowaead_2022/method.go:229 +0xa5c
github.com/sagernet/sing-shadowsocks2/shadowaead_2022.(*clientConn).Write(0x40?, {0xc0014439c0?, 0x40, 0x226db40?})
        github.com/sagernet/sing-shadowsocks2@v0.2.0/shadowaead_2022/method.go:332 +0x37
github.com/sagernet/sing/common/bufio.(*BufferedVectorisedWriter).WriteVectorised(0xc00160b690, {0xc001189230, 0x3, 0xc000008318?})
        github.com/sagernet/sing@v0.5.0-rc.2/common/bufio/vectorised.go:82 +0x358
github.com/sagernet/sing/common/uot.(*LazyClientConn).WriteVectorised(0xc000108c00, {0xc00140e730, 0x2, 0x22b5f00?})
        github.com/sagernet/sing@v0.5.0-rc.2/common/uot/lazy.go:55 +0x17d
github.com/sagernet/sing/common/uot.(*Conn).WriteTo(0xc000485c00, {0xc000196b00, 0x36, 0x40}, {0x17d0228?, 0xc00114c240?})
        github.com/sagernet/sing@v0.5.0-rc.2/common/uot/conn.go:97 +0x49a
github.com/sagernet/sing/common/uot.(*Conn).Write(0xc000485c00, {0xc000196b00, 0x36, 0x40})
        github.com/sagernet/sing@v0.5.0-rc.2/common/uot/conn.go:45 +0x5a
github.com/sagernet/sing-dns.(*UDPTransport).exchange(0xc0002cd380, {0x17da9e0, 0xc000620930}, 0xc000e66870)
        github.com/sagernet/sing-dns@v0.3.0-rc.2/transport_udp.go:150 +0x2eb
github.com/sagernet/sing-dns.(*UDPTransport).Exchange(0xc0002cd380, {0x17da9e0, 0xc000620930}, 0xc000e66870)
        github.com/sagernet/sing-dns@v0.3.0-rc.2/transport_udp.go:100 +0x2b
github.com/sagernet/sing-dns.(*Client).ExchangeWithResponseCheck(0xc0002ca230, {0x17da938, 0xc000987230}, {0x17e1420, 0xc0002cd380}, 0xc000e662d0, 0x0, 0xc00109de80)
        github.com/sagernet/sing-dns@v0.3.0-rc.2/client.go:162 +0x982
github.com/sagernet/sing-box/route.(*Router).Exchange(0xc0002e2008, {0x17da938, 0xc0009871a0}, 0xc000e662d0)
        github.com/sagernet/sing-box/route/router_dns.go:134 +0x454
github.com/sagernet/sing-box/outbound.(*DNS).newPacketConnection.func1.1()
        github.com/sagernet/sing-box/outbound/dns.go:231 +0xa3
created by github.com/sagernet/sing-box/outbound.(*DNS).newPacketConnection.func1 in goroutine 56511
        github.com/sagernet/sing-box/outbound/dns.go:230 +0xaf

```
```


### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by swysgh** [comment]
请提供配置，另外根据我的经验推测，有可能是route中没有加"auto_detect_interface": true
