### ISSUE TITLE
socks5 inbound panic 1.11.0-alpha.7

### ISSUE THREAD

**Issue by SimonTLS** [SagerNet/sing-box#2252]
### 操作系统

Windows

### 系统版本

Window 11 LTSC

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
sing-box version 1.11.0-alpha.7

Environment: go1.23.2 windows/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 51bbc4aaa157bcb09b4ba5fc4311f4559994e8d2
CGO: disabled
```

### 描述

socks5 inbound panic

### 重现方式

sing-box.exe run
curl --proxy socks5://127.0.0.1:11223 one.one.one.one

> {
  "log": {
    "level": "debug",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "local",
        "address": "udp://223.5.5.5",
        "detour": "direct"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "socks",
      "tag": "socks-in",
      "listen": "127.0.0.1",
      "listen_port": 11223
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ]
}

### 日志

```shell
PS C:\Users\air> .\sing-box.exe run
+0800 2024-11-07 22:40:39 INFO router: updated default interface 以太网, index 16
+0800 2024-11-07 22:40:39 INFO inbound/socks[socks-in]: tcp server started at 127.0.0.1:11223
+0800 2024-11-07 22:40:39 INFO sing-box started (0.11s)
+0800 2024-11-07 22:40:42 INFO [455046604 0ms] inbound/socks[socks-in]: inbound connection from 127.0.0.1:6073
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x1b1ad66]

goroutine 34 [running]:
github.com/sagernet/sing-box/protocol/socks.(*Inbound).newUserConnection(_, {_, _}, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
        github.com/sagernet/sing-box/protocol/socks/inbound.go:71 +0x2a6
github.com/sagernet/sing-box/adapter.(*myUpstreamHandlerWrapperEx).NewConnectionEx(0xc00000c000, {0x21aee58, 0xc0002020f0}, {0x21bb0b8, 0xc00030c018}, {{{0x0, 0xffff7f000001}, {0xc000008318}}, 0x17b9, {0x0, ...}}, ...)
        github.com/sagernet/sing-box/adapter/upstream.go:44 +0x388
github.com/sagernet/sing/protocol/socks.HandleConnectionEx({0x21aee58, 0xc0002020f0}, {0x21b7a58, 0xc0000800c8}, 0xc000280060, 0x0, {0x0, 0x0}, {0x136566c0028, 0xc00000c000}, ...)
        github.com/sagernet/sing@v0.5.1-0.20241105104305-c80c8f907c56/protocol/socks/handshake.go:228 +0x130c
github.com/sagernet/sing-box/protocol/socks.(*Inbound).NewConnectionEx(_, {_, _}, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
        github.com/sagernet/sing-box/protocol/socks/inbound.go:61 +0x42b
created by github.com/sagernet/sing-box/common/listener.(*Listener).loopTCPIn in goroutine 9
        github.com/sagernet/sing-box/common/listener/listener_tcp.go:83 +0x566
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by Anidetrix** [comment]
Seems to work as intended in 1.11.0-alpha.8

**Comment by SimonTLS** [comment]
Fixed Thanks!
