### ISSUE TITLE
New panic

### ISSUE THREAD

**Issue by qystishere** [SagerNet/sing-box#2311]
### Operating system

Linux

### System version

OpenWrt 23.05.5 r24106-10cc5fcd00

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.11.0-alpha.24

Environment: go1.23.3 linux/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: ec2cba84dc67afafaed32c4cc57d965f9922a250
CGO: disabled
```

### Description

Running sing-box as a service on OpenWRT, it crashes very quickly (within 5 minutes).

There is no such problem on Alpha 18.

### Reproduction

I don't think it requires reproduction. Perhaps `sync.Once` should be used [here](https://github.com/SagerNet/sing/blob/v0.6.0-alpha.20/common/udpnat2/conn.go#L90)?

[config.json](https://github.com/user-attachments/files/17899728/config.json)

### Logs

```shell
Mon Nov 25 07:44:03 2024 daemon.err sing-box[7083]: +0000 2024-11-25 07:44:03 DEBUG [1687217934 0ms] router: match[0] => sniff
Mon Nov 25 07:44:03 2024 daemon.err sing-box[7083]: +0000 2024-11-25 07:44:03 INFO [1687217934 0ms] outbound/direct[direct]: outbound packet connection
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: +0000 2024-11-25 07:44:06 DEBUG [4016215983 30.0s] connection: packet upload closed: i/o timeout
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: panic: close of closed channel
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]:
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: goroutine 18 [running]:
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: github.com/sagernet/sing/common/udpnat2.(*natConn).Close(0x4000120090)
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]:     github.com/sagernet/sing@v0.6.0-alpha.20/common/udpnat2/conn.go:94 +0x38
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: github.com/sagernet/sing/common/bufio.(*CachedPacketConn).Close(0x13070a0?)
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]:     github.com/sagernet/sing@v0.6.0-alpha.20/common/bufio/cache.go:213 +0xa4
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: github.com/sagernet/sing/common/canceler.(*TimeoutPacketConn).Close(0x400003b200)
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]:     github.com/sagernet/sing@v0.6.0-alpha.20/common/canceler/packet_timeout.go:71 +0x50
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: github.com/sagernet/sing-box/route.(*ConnectionMonitor).monitor(0x40002e39a0)
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]:     github.com/sagernet/sing-box/route/conn_monitor.go:126 +0x470
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]: created by github.com/sagernet/sing-box/route.(*ConnectionMonitor).Start in goroutine 1
Mon Nov 25 07:44:06 2024 daemon.err sing-box[7083]:     github.com/sagernet/sing-box/route/conn_monitor.go:63 +0x5c
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by qystishere** [comment]
Fixed in version `1.11.0-alpha.25` (SagerNet/sing `v0.6.0-alpha.21`).
