### ISSUE TITLE
sing-box panic at random times

### ISSUE THREAD

**Issue by inipew** [SagerNet/sing-box#2332]
### Operating system

Android

### System version

Android 11

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.11.0-beta.4
```

### Description

I don't know how to describe this error, it happened suddenly. maybe the problem is after this commit  [udpnat2: Fix concurrency](https://github.com/SagerNet/sing/commit/39040e06dcd5dd887ca4eafd8be55ed1411160ee)

### Reproduction

The configuration I use is as follows
```json
{
  "log": {
    "level": "fatal",
    "timestamp": true
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "koneksi-in",
      "interface_name": "xtun",
      "mtu": 9000,
      "address": [
        "172.18.0.1/30",
        "fdfe:dcba:9876::1/126"
      ],
      "auto_route": true,
      "strict_route": true,
      "route_exclude_address": "192.168.0.0/16",
      "stack": "system"
    }
  ],
  "experimental": {
    "cache_file": {
      "enabled": true,
      "path": "cacheNew.db",
      "store_rdrc": true
    },
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui": "zashboard",
      "external_ui_download_url": "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip",
      "external_ui_download_detour": "SerperIndo",
      "default_mode": "Rule"
    }
  },
  ......
  "route": {
    "rules": [
      {
        "action": "sniff",
        "timeout": "300ms"
      },
      {
        "protocol": "dns",
        "action": "hijack-dns"
      },
      ......
      {
        "rule_set": "commonports",
        "outbound": "Flow"
      },
      {
        "rule_set": "commonports",
        "invert": true,
        "outbound": "KoneksiDirect"
      }
    ],
    "final": "Flow",
    "auto_detect_interface": true,
    "override_android_vpn": true
  }
}
```

I tried using tproxy as well, and it reproduces the same error

```json
"inbounds": [
    {
      "type": "tproxy",
      "tag": "koneksi-in",
      "listen": "::",
      "listen_port": 65535
    }
  ],
  ```

### Logs

```shell
tun mode log

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d6628b2a8]

goroutine 33 [running]:
github.com/sagernet/sing/common/udpnat2.(*natConn).Close(0x40002a7968?)
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/conn.go:110 +0x18
github.com/sagernet/sing/common/udpnat2.New.func2({{{0x40002a7968?, 0x5d65d03b0c?}, {0xc02e83ebe9ea?}}, 0xdd53?}, 0x16fedd5300000123?)
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/service.go:44 +0x20
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).evict(0x5d6602003c?, 0x2a7998?)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:246 +0x1a8
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).removeAt(0x5d66d06ee0, 0x11b)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:638 +0x2c
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).PurgeExpired(0x5d66d06ee0)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:700 +0xb0
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).getAndRefreshOrAdd(0x5d66d06ee0, 0xc35b7d38, {{{0xda, 0x10a002a7ac8?}, {0x40001be228?}}, 0x5f30?}, 0x40002d4300?)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:546 +0x27c
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).GetAndRefreshOrAdd(0x5d66d06ee0, {{{0x40002a7b28, 0x5d6628b7a0?}, {0x40001be228?}}, 0xd0c0?}, 0x40002d4300?)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:526 +0x7c
github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40003d96e0, {0x40002a7dc0, 0x1, 0x5d65d29e10?}, {{{0x0, 0xffffac120001}, {0x40001be228}}, 0x3a32, {0x0, 0x0}}, ...)
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/service.go:54 +0x178
github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x4000428000, {0x4000712000, 0x3e, 0x2328}, {0x4000712014, 0x2a, 0x2314})
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
github.com/sagernet/sing-tun.(*System).processIPv4(0x4000428000, {0x4000712000, 0x3e, 0x2328})
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x1ec
github.com/sagernet/sing-tun.(*System).processPacket(0x4000428000, {0x4000712000?, 0x2328?, 0x2328?})
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
github.com/sagernet/sing-tun.(*System).tunLoop(0x4000428000)
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64


tproxy mode log

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x62b12a62a8]

goroutine 69 [running]:
github.com/sagernet/sing/common/udpnat2.(*natConn).Close(0x4000081848?)
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/conn.go:110 +0x18
github.com/sagernet/sing/common/udpnat2.New.func2({{{0x4000081848?, 0x62b0d1eb0c?}, {0x23d1867b1862?}}, 0xa56d?}, 0x4e9a56d00081868?)
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/service.go:44 +0x20
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).evict(0x62b103b03c?, 0x81878?)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:246 +0x1a8
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).removeAt(0x62b1d21ee0, 0x83)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:638 +0x2c
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).PurgeExpired(0x62b1d21ee0)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:700 +0xb0
github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket.func1()
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/service.go:67 +0x1c4
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).getAndRefreshOrAdd(0x62b1d21ee0, 0x5bcffe01, {{{0x4000c10780, 0xa00081b28?}, {0x40001b8228?}}, 0xc108?}, 0x4000804280?)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:541 +0x234
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).GetAndRefreshOrAdd(0x62b1d21ee0, {{{0x4000081b88, 0x62b12a67a0?}, {0x40001b8228?}}, 0x80c0?}, 0x4000804280?)
github.com/sagernet/sing@v0.6.0-beta.2/contrab/freelru/lru.go:526 +0x7c
github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40001209f0, {0x4000375d90, 0x1, 0x0?}, {{{0x0, 0xffffc0a82a8f}, {0x40001b8228}}, 0xadbe, {0x0, 0x0}}, ...)
github.com/sagernet/sing@v0.6.0-beta.2/common/udpnat2/service.go:54 +0x178
github.com/sagernet/sing-box/protocol/redirect.(*TProxy).NewPacketEx(0x4000180cc0, 0x400040e000, {0x40001c2c00?, 0x400014adbe?, 0x0?}, {{{0x0, 0xffffc0a82a8f}, {0x40001b8228}}, 0xadbe, {0x0, ...}})
github.com/sagernet/sing-box/protocol/redirect/tproxy.go:119 +0x108
github.com/sagernet/sing-box/common/listener.(*Listener).loopUDPIn(0x40004f8f20)
github.com/sagernet/sing-box/common/listener/listener_udp.go:75 +0x264
created by github.com/sagernet/sing-box/common/listener.(*Listener).Start in goroutine 1
github.com/sagernet/sing-box/common/listener/listener.go:88 +0x23c
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by inipew** [comment]
seems to have been fixed in version 1.11.0-beta.5

**Comment by inipew** [comment]
I thought it was resolved because since using the latest commit it doesn't panic, but now it turns out there is still a panic issue. the connection is currently being used to update windows and watch youtube and tiktok, then the panic occurs.

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x599e0d24e8]

goroutine 83 [running]:
github.com/sagernet/sing/common/udpnat2.(*natConn).Close(0x0?)
github.com/sagernet/sing@v0.6.0-beta.4/common/udpnat2/conn.go:110 +0x18
github.com/sagernet/sing/common/udpnat2.New.func2({{{0x4000543978?, 0x599db4ac8c?}, {0x6afcb670cd96?}}, 0x36ee?}, 0x356b36ee024d8150?)
github.com/sagernet/sing@v0.6.0-beta.4/common/udpnat2/service.go:44 +0x20
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).evict(0x599de6729c?, 0x5439a8?)
github.com/sagernet/sing@v0.6.0-beta.4/contrab/freelru/lru.go:246 +0x1a8
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).removeAt(0x599eb4cde0, 0x295)
github.com/sagernet/sing@v0.6.0-beta.4/contrab/freelru/lru.go:638 +0x2c
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).PurgeExpired(0x599eb4cde0)
github.com/sagernet/sing@v0.6.0-beta.4/contrab/freelru/lru.go:699 +0x48
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).getAndRefreshOrAdd(0x599eb4cde0, 0xa2d3ce34, {{{0x599dade9a4, 0x10a00543ac8?}, {0x400000e240?}}, 0x53e8?}, 0x4001fa6400?)
github.com/sagernet/sing@v0.6.0-beta.4/contrab/freelru/lru.go:546 +0x27c
github.com/sagernet/sing/contrab/freelru.(*LRU[...]).GetAndRefreshOrAdd(0x599eb4cde0, {{{0x4000543b28, 0x599e0d29e0?}, {0x400000e240?}}, 0x30a0?}, 0x4001fa6400?)
github.com/sagernet/sing@v0.6.0-beta.4/contrab/freelru/lru.go:526 +0x7c
github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x400046e9c0, {0x4000543dc0, 0x1, 0x599db70f90?}, {{{0x0, 0xffffac120001}, {0x400000e240}}, 0xd42f, {0x0, 0x0}}, ...)
github.com/sagernet/sing@v0.6.0-beta.4/common/udpnat2/service.go:54 +0x178
github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x4000796000, {0x4000238000, 0x49, 0x58c}, {0x4000238014, 0x35, 0x578})
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
github.com/sagernet/sing-tun.(*System).processIPv4(0x4000796000, {0x4000238000, 0x49, 0x58c})
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x1ec
github.com/sagernet/sing-tun.(*System).processPacket(0x4000796000, {0x4000238000?, 0x58c?, 0x58c?})
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
github.com/sagernet/sing-tun.(*System).tunLoop(0x4000796000)
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
github.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64
```

**Comment by DeHb86** [comment]
**Operating system**
RouterOS

**System version**
7.16.2

**Installation type**
Docker container from hub.docker.com/r/gzxhwq/sing-box

**If you are using a graphical client, please provide the version of the client.**
Yacd 0.3.7

Version
`sing-box version 1.11.0-beta.8`

**Description**
At random times, regardless of the load, the container falls. The first and subsequent container launches occur without errors in the log.

**Reproduction**
The configuration I use is as follows:

```
{
  "log": {
    "disabled": false,
    "level": "error",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_ui": "ui",
      "external_controller": "0.0.0.0:9090",
      "external_ui_download_detour": "direct",
      "default_mode": "rule"
    },
    "cache_file": {
      "enabled": true,
      "store_fakeip": true
    }
  },
  "dns": {
    "servers": [
      {
        "tag": "local-dns",
        "address": "10.6.0.2",
        "detour": "direct"
      },
      {
        "tag": "google-dns",
        "address": "tls://8.8.8.8",
        "detour": "direct"
      },
      {
        "tag": "fakeip-dns",
        "address": "fakeip"
      }
    ],
    "rules": [
      {
        "query_type": [
          "HTTPS",
          "SVCB"
        ],
        "action": "reject"
      },
      {
        "query_type": [
          "A"
        ],
        "domain_suffix": [
          "synology.com",
          "synologyupdate.com",
          "habr.com",
          "lenovo.com",
          "intel.com",
          "dnsleaktest.com",
          "whoer.net",
          "ntc.party",
          "amnezia.org"
        ],
        "rule_set": [
          "adguard",
          "adobe",
          "adobe-activation",
          "adobe-ads",
          "discord",
          "facebook",
          "instagram",
          "intel",
          "openai",
          "tmdb",
          "twitter",
          "youtube"
        ],
        "action": "route",
        "server": "fakeip-dns"
      }
    ],
    "strategy": "ipv4_only",
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15"
    },
    "disable_cache": false,
    "final": "local-dns"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun",
      "address": "172.19.0.1/30",
      "stack": "system",
      "auto_route": true,
      "auto_redirect": true,
      "strict_route": true
    },
    {
      "type": "direct",
      "tag": "dns-in",
      "listen_port": 53,
      "network": "udp",
      "listen": "0.0.0.0"
    }
  ],
  "route": {
    "rules": [
      {
        "inbound": "dns-in",
        "action": "sniff",
        "sniffer": "dns"
      },
      {
        "inbound": "tun",
        "action": "sniff"
      },
      {
        "protocol": "dns",
        "action": "hijack-dns"
      },
      {
        "rule_set": [
          "adguard",
          "adobe",
          "adobe-activation",
          "adobe-ads",
          "discord",
          "facebook",
          "instagram",
          "intel",
          "openai",
          "tmdb",
          "twitter",
          "youtube"
        ],
        "domain_suffix": [
          "synology.com",
          "synologyupdate.com",
          "habr.com",
          "lenovo.com",
          "intel.com",
          "dnsleaktest.com",
          "whoer.net",
          "ntc.party",
          "amnezia.org"
        ],
        "ip_cidr": [
          "5.200.14.128/25",
          "34.0.0.0/15",
          "34.2.0.0/16",
          "34.3.0.0/23",
          "34.3.2.0/24",
          "35.192.0.0/12",
          "35.208.0.0/12",
          "35.224.0.0/12",
          "35.240.0.0/13",
          "66.22.192.0/18",
          "138.128.136.0/21",
          "162.158.0.0/15",
          "172.64.0.0/13"
        ],
        "action": "route",
        "outbound": "vps-lat"
      }
    ],
    "rule_set": [
      {
        "type": "local",
        "format": "binary",
        "tag": "adguard",
        "path": "/home/adguard.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "adobe",
        "path": "/home/adobe.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "adobe-activation",
        "path": "/home/adobe-activation.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "adobe-ads",
        "path": "/home/adobe-ads.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "discord",
        "path": "/home/discord.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "facebook",
        "path": "/home/facebook.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "instagram",
        "path": "/home/instagram.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "intel",
        "path": "/home/intel.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "openai",
        "path": "/home/openai.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "tmdb",
        "path": "/home/tmdb.srs"
      },
      {
        "type": "local",
        "format": "binary",
        "tag": "twitter",
        "path": "/home/twitter.srs"
      },
      {
        "type": "local",
        "tag": "youtube",
        "format": "binary",
        "path": "/home/youtube.srs"
      }
    ],
    "auto_detect_interface": true,
    "final": "direct"
  },
  "outbounds": [
    {
      "tag": "Proxy",
      "outbounds": [
        "vps-lat",
        "vps-hor"
      ],
      "interrupt_exist_connections": true,
      "type": "selector"
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "tag": "vps-lat",
      "server": "xyz",
      "server_port": 443,
      "type": "vless",
      "uuid": "xyz",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "insecure": false,
        "server_name": "xyz",
        "reality": {
          "enabled": true,
          "public_key": "xyz",
          "short_id": "xyz"
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "tag": "vps-hor",
      "server": "xyz",
      "server_port": 443,
      "type": "vless",
      "uuid": "xyz",
      "flow": "xyz",
      "tls": {
        "enabled": true,
        "insecure": false,
        "server_name": "xyz",
        "reality": {
          "enabled": true,
          "public_key": "xyz",
          "short_id": "xyz"
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    }
  ]
}
```

**Logs**

```
 01:35:30 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 01:35:30 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
 01:35:30 container,info,debug 
 01:35:30 container,info,debug goroutine 97 [running]:
 01:35:30 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000865500, {{{0x0, 0xffffac130002}, {0x400000c300}}, 0x35, {0x0, 0x0}})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
 01:35:30 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40002f8a50, {0x4000efbdc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x400000c300}}, 0x99d0, {0x0, 0x0}}, ...)
 01:35:30 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40000ca180, {0x400041c000, 0x42, 0x2328}, {0x400041c014, 0x2e, 0x2314})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x40000ca180, {0x400041c000, 0x42, 0x2328})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x40000ca180, {0x400041c000?, 0x0?, 0x0?})
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
 01:35:30 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x40000ca180)
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
 01:35:30 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
 01:35:30 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64


 04:02:00 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 04:02:00 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
 04:02:00 container,info,debug 
 04:02:00 container,info,debug goroutine 14 [running]:
 04:02:00 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000b13840, {{{0x0, 0xffffac130002}, {0x40000c42e8}}, 0x35, {0x0, 0x0}})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
 04:02:00 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x40002a8150, {0x40009b3dc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x40000c42e8}}, 0xbae1, {0x0, 0x0}}, ...)
 04:02:00 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x40004f2000, {0x40001dc000, 0x42, 0x2328}, {0x40001dc014, 0x2e, 0x2314})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x40004f2000, {0x40001dc000, 0x42, 0x2328})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x40004f2000, {0x40001dc000?, 0x0?, 0x0?})
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
 04:02:00 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x40004f2000)
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
 04:02:00 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
 04:02:00 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64



 11:58:01 container,info,debug panic: runtime error: invalid memory address or nil pointer dereference
 11:58:01 container,info,debug [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a31e0]
 11:58:01 container,info,debug 
 11:58:01 container,info,debug goroutine 103 [running]:
 11:58:01 container,info,debug github.com/sagernet/sing-box/route.(*dnsHijacker).NewPacketEx(0x0, 0x4000eadc40, {{{0x0, 0xffffac130002}, {0x400000c300}}, 0x35, {0x0, 0x0}})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-box/route/dns.go:91 +0x50
 11:58:01 container,info,debug github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket(0x4000335950, {0x40018d1dc0, 0x1, 0xa7ed0?}, {{{0x0, 0xffff0a0a0c03}, {0x400000c300}}, 0xaa8b, {0x0, 0x0}}, ...)
 11:58:01 container,info,debug tgithub.com/sagernet/sing@v0.6.0-beta.5/common/udpnat2/service.go:80 +0x3a4
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x4000572000, {0x40007c0000, 0x42, 0x2328}, {0x40007c0014, 0x2e, 0x2314})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:524 +0x21c
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processIPv4(0x4000572000, {0x40007c0000, 0x42, 0x2328})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:319 +0x204
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).processPacket(0x4000572000, {0x40007c0000?, 0x2328?, 0x2328?})
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:263 +0xf4
 11:58:01 container,info,debug github.com/sagernet/sing-tun.(*System).tunLoop(0x4000572000)
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:188 +0x324
 11:58:01 container,info,debug created by github.com/sagernet/sing-tun.(*System).Start in goroutine 1
 11:58:01 container,info,debug tgithub.com/sagernet/sing-tun@v0.6.0-beta.2/stack_system.go:105 +0x64
```
