### ISSUE TITLE
1.11.0-beta.11 在启用 udp_connect 时 panic

### ISSUE THREAD

**Issue by Zxneric** [SagerNet/sing-box#2377]
### 操作系统

Windows

### 系统版本

26100.2605

### 安装类型

sing-box 原始命令行程序

### 版本

```shell
2024/12/18 00:33:05 sing-box version 1.11.0-beta.11

Environment: go1.23.2 windows/amd64
Tags: with_gvisor,with_dhcp,with_wireguard,with_reality_server,with_clash_api,with_quic,with_utls,with_ech
Revision: 492934f7f295bb57e7ad429eaea0c00f56392761
CGO: disabled
```

### 描述

任何 udp 出站连接即崩溃

### 重现方式

```json
      {
        "action": "sniff",
        "sniffer": [
          "http",
          "tls",
          "dns"
        ]
      },
      {
        "action": "route-options",
        "udp_disable_domain_unmapping": false,
        "udp_connect": true
      },
```

### 日志

```shell
DEBUG[0015] [1575606330 0ms] router: match[0] => sniff(http,tls,dns)
DEBUG[0015] [1575606330 0ms] router: match[1] => route-options(udp-connect)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0xd0653e]

goroutine 394 [running]:
github.com/sagernet/sing/common/bufio.NewUnbindPacketConn({0x0, 0x0})
	github.com/sagernet/sing@v0.6.0-beta.8/common/bufio/bind.go:66 +0x7e
github.com/sagernet/sing-box/route.(*ConnectionManager).NewPacketConnection(_, {_, _}, {_, _}, {_, _}, {{0x1bfc229, 0x1}, {0x1bd0d4d, ...}, ...}, ...)
	github.com/sagernet/sing-box/route/conn.go:114 +0x1905
github.com/sagernet/sing-box/protocol/group.(*Selector).NewPacketConnectionEx(_, {_, _}, {_, _}, {{0x1bfc229, 0x1}, {0x1bd0d4d, 0x3}, 0x4, ...}, ...)
	github.com/sagernet/sing-box/protocol/group/selector.go:173 +0x1ad
github.com/sagernet/sing-box/route.(*Router).routePacketConnection(_, {_, _}, {_, _}, {{0x1bfc229, 0x1}, {0x1bd0d4d, 0x3}, 0x0, ...}, ...)
	github.com/sagernet/sing-box/route/route.go:250 +0xfd7
github.com/sagernet/sing-box/route.(*Router).RoutePacketConnectionEx(_, {_, _}, {_, _}, {{0x1bfc229, 0x1}, {0x1bd0d4d, 0x3}, 0x0, ...}, ...)
	github.com/sagernet/sing-box/route/route.go:157 +0x7e
github.com/sagernet/sing-box/protocol/tun.(*Inbound).NewPacketConnectionEx(0xc0002a8708, {0x1de34c0?, 0xc0002920f0?}, {0x1debc70, 0xc00047c580}, {{{0x0, 0xffffac130001}, {0xc000008258}}, 0xf1a3, {0x0, ...}}, ...)
	github.com/sagernet/sing-box/protocol/tun/inbound.go:458 +0x2e8
created by github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket.func1 in goroutine 153
	github.com/sagernet/sing@v0.6.0-beta.8/common/udpnat2/service.go:67 +0x408
```

### 支持我们

- [ ] 我已经 [赞助](https://github.com/sponsors/nekohasekai/)

### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我保证提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我保证提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

**Comment by inipew** [comment]
same here

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x589d8db030]

goroutine 469 [running]:
github.com/sagernet/sing/common/bufio.NewUnbindPacketConn({0x0, 0x0})
github.com/sagernet/sing@v0.6.0-beta.8/common/bufio/bind.go:66 +0x80
github.com/sagernet/sing-box/route.(*ConnectionManager).NewPacketConnection(_, {_, _}, {_, _}, {_, _}, {{0x400023c7e0, 0xa}, {0x589d4c404b, ...}, ...}, ...)
github.com/sagernet/sing-box/route/conn.go:114 +0x1404
github.com/sagernet/sing-box/protocol/group.(*Selector).NewPacketConnectionEx(_, {_, _}, {_, _}, {{0x400023c7e0, 0xa}, {0x589d4c404b, 0x6}, 0x4, ...}, ...)
github.com/sagernet/sing-box/protocol/group/selector.go:173 +0x168
github.com/sagernet/sing-box/route.(*Router).routePacketConnection(_, {_, _}, {_, _}, {{0x400023c7e0, 0xa}, {0x589d4c404b, 0x6}, 0x0, ...}, ...)
github.com/sagernet/sing-box/route/route.go:250 +0xc80
github.com/sagernet/sing-box/route.(*Router).RoutePacketConnectionEx(_, {_, _}, {_, _}, {{0x400023c7e0, 0xa}, {0x589d4c404b, 0x6}, 0x0, ...}, ...)
github.com/sagernet/sing-box/route/route.go:157 +0x58
github.com/sagernet/sing-box/protocol/redirect.(*TProxy).NewPacketConnectionEx(0x40000a4b40, {0x589e732160, 0x4000438900}, {0x589e73ab30, 0x40001f00b0}, {{{0x0, 0xffffc0a82ab2}, {0x4000144228}}, 0xde3d, {0x0, ...}}, ...)
github.com/sagernet/sing-box/protocol/redirect/tproxy.go:112 +0x2a0
created by github.com/sagernet/sing/common/udpnat2.(*Service).NewPacket.func1 in goroutine 69
github.com/sagernet/sing@v0.6.0-beta.8/common/udpnat2/service.go:67 +0x2f0```

**Comment by nekohasekai** [comment]
`我保证提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。`
