### ISSUE TITLE
shadowsocks inbound 多用户 非2022methods提示`decode psk: illegal base64 data at input byte 0`与`panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by imldy** [SagerNet/sing-box#262]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

服务的shadowsocks入栈**多用户配置**，使用`aes-256-gcm`与`chacha20-ietf-poly1305`加密方式（非2022 methods），报错。
password使用任意字符串报错：
```
FATAL[0000] create service: parse inbound[1]: decode psk: illegal base64 data at input byte 0
```
尝试使用`openssl rand -base64 16`或`openssl rand -base64 32`输出的字符作为password仍然报错：
```
panic: runtime error: invalid memory address or nil pointer dereference
```
详细报错信息在日志

### Version of sing-box

<details>

```console
$ sing-box version
sing-box 1.0.7.18162df (go1.19.3, windows/amd64, CGO disabled)
```

</details>

### Server and client configuration file

<details>

```console
{
  "inbounds": [
    {
      "type": "shadowsocks",
      "tag": "ss-in",
      "listen": "::",
      "listen_port": 18071,
      "method": "aes-256-gcm",
      "password": "111",
      "users": [
        {
          "name": "a",
          "password": "WWF6hWazcadd4IurMzXKcw=="
        }
      ]
    }
  ]
}
```

</details>

### Server and client log file

<details>

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x139b716]

goroutine 1 [running]:
github.com/sagernet/sing-shadowsocks/shadowaead_2022.(*MultiService[...]).UpdateUsers(0x0?, {0xc000089650, 0x1, 0x14b2380}, {0xc0000b2b28?, 0x1, 0x13a5614})
        pkg/mod/github.com/sagernet/sing-shadowsocks@v0.0.0-20220819002358-7461bb09a8f6/shadowaead_2022/service_multi.go:75 +0xf6
github.com/sagernet/sing-shadowsocks/shadowaead_2022.(*MultiService[...]).UpdateUsersWithPasswords(0xc0000d0200, {0xc000089650?, 0x1, 0x1}, {0xc000090e00, 0x1, 0xc0000924a0})
        pkg/mod/github.com/sagernet/sing-shadowsocks@v0.0.0-20220819002358-7461bb09a8f6/shadowaead_2022/service_multi.go:112 +0xcc
github.com/sagernet/sing-box/inbound.newShadowsocksMulti({0x17b1838?, 0xc0000945c0}, {0x17bb860?, 0xc0000e0000}, {0x17bae28?, 0xc0000b2b10}, {0xc000088cfb, _}, {{{{0x0, 0x0}, ...}, ...}, ...})
        /home/sekai/Projects/sing-box/inbound/shadowsocks_multi.go:57 +0x525
github.com/sagernet/sing-box/inbound.NewShadowsocks({0x17b1838?, 0xc0000945c0?}, {0x17bb860?, 0xc0000e0000?}, {0x17bae28?, 0xc0000b2b10?}, {0xc000088cfb?, _}, {{{{0x0, 0x0}, ...}, ...}, ...})
        /home/sekai/Projects/sing-box/inbound/shadowsocks.go:26 +0xc6
github.com/sagernet/sing-box/inbound.New({_, _}, {_, _}, {_, _}, {{0xc000088cf0, 0xb}, {0xc000088cfb, 0x5}, ...})
        /home/sekai/Projects/sing-box/inbound/builder.go:33 +0xa1e
github.com/sagernet/sing-box.New({0x17b1838, 0xc0000945c0}, {0x0, 0x0, {0xc0000ce000, 0x1, 0x4}, {0x0, 0x0, 0x0}, ...})
        /home/sekai/Projects/sing-box/box.go:112 +0x13fa
main.create()
        /home/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:67 +0x138
main.run()
        /home/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:84 +0xc5
main.glob..func3(0x1ddfec0?, {0x163080e?, 0x2?, 0x2?})
        /home/sekai/Projects/sing-box/cmd/sing-box/cmd_run.go:23 +0x1d
github.com/spf13/cobra.(*Command).execute(0x1ddfec0, {0xc000092160, 0x2, 0x2})
        pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1de0140)
        pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/sekai/Projects/sing-box/cmd/sing-box/main.go:29 +0x25

```

</details>

**Comment by nekohasekai** [comment]
由于协议限制，非 2022 支持多用户需要使用暴力解码的办法，故不支持。

**Comment by imldy** [comment]
> 由于协议限制，非 2022 支持多用户需要使用暴力解码的办法，故不支持。

好的，感谢您的工作

**Comment by nekohasekai** [comment]
5f8bc9e9b999b494404c76214877d0f0577d47cb

**Comment by swysgh** [comment]
1.10.7使用ss2022出现 FATAL[0000] parse inbound[0]: missing psk
