### ISSUE TITLE
ACME tls-alpn crashes

### ISSUE THREAD

**Issue by skbeh** [SagerNet/sing-box#272]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

When using acme certificate issuance with tls-alpn mode, sing-box crashes. The http challenge mode works correctly.
This problem does not exist in sing-box [1.0.7](https://github.com/SagerNet/sing-box/releases/tag/v1.0.7).
### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1

Environment: go1.19.3 linux/amd64
Tags: with_acme
Revision: 55ed14d729aabc872c89dade35807a0eb4f45f9c
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": {
    "level": "warn"
  },
  "inbounds": [
    {
      "type": "trojan",
      "tag": "trojan-in",
      "listen": "::",
      "listen_port": 443,
      "users": [
        {
          "name": "user",
          "password": "foobar"
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "foo.bar",
        "alpn": [
          "h2",
          "http/1.1"
        ],
        "min_version": "1.3",
        "max_version": "1.3",
        "acme": {
          "domain": "foo.bar",
          "data_directory": "/etc/sing-box",
          "email": "account@foo.bar",
          "disable_http_challenge": true
        }
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    }
  ]
}
```

</details>

### Server and client log file

<details>

```console
1.6702044760928504e+09  info    maintenance     started background certificate maintenance      {"cache": "0xc0000e08c0"}
1.6702044761348157e+09  info    obtain  acquiring lock  {"identifier": "foo.bar"}
1.6702044761383674e+09  info    obtain  lock acquired   {"identifier": "foo.bar"}
1.6702044761385305e+09  info    obtain  obtaining certificate   {"identifier": "foo.bar"}
1.6702044773846085e+09  info    waiting on internal rate limiter        {"identifiers": ["foo.bar"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": "account@foo.bar"}
1.6702044773846698e+09  info    done waiting on internal rate limiter   {"identifiers": ["foo.bar"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": "account@foo.bar"}
1.6702044778405492e+09  info    acme_client     trying to solve challenge       {"identifier": "foo.bar", "challenge_type": "tls-alpn-01", "ca": "https://acme-v02.api.letsencrypt.org/directory"}
2022/12/05 01:41:18 panic: tls-alpn solver handler: runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn.func1()
github.com/caddyserver/certmagic@v0.17.2/solvers.go:204 +0x65
panic({0x55816db5f1c0, 0x55816e0b78d0})
runtime/panic.go:884 +0x212
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x55816d82ea2a, 0x25})
go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc0001312c0?, {0x55816d82ea2a?, 0x55816d81a87e?}, {0xc000470c00, 0x4, 0x4})
go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc0000b24d0, 0xc000207790)
github.com/caddyserver/certmagic@v0.17.2/handshake.go:67 +0xbd3
crypto/tls.(*Config).getCertificate(0xc0001b6c00, 0xc000207790)
crypto/tls/common.go:1069 +0x42
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc0001ddc38)
crypto/tls/handshake_server_tls13.go:367 +0x354
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc0001ddc38)
crypto/tls/handshake_server_tls13.go:59 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0000c6000, {0x55816dc4d6b8, 0xc000128a80})
crypto/tls/handshake_server.go:54 +0xd0
crypto/tls.(*Conn).handshakeContext(0xc0000c6000, {0x55816dc4d6f0, 0xc000034090})
crypto/tls/conn.go:1462 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
crypto/tls/conn.go:1389
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn(0x55816d3e4d6a, {0x55816dc52798?, 0xc0000c6000?})
github.com/caddyserver/certmagic@v0.17.2/solvers.go:214 +0xc6
created by github.com/caddyserver/certmagic.(*tlsALPNSolver).Present.func1
github.com/caddyserver/certmagic@v0.17.2/solvers.go:192 +0x159
2022/12/05 01:41:18 panic: tls-alpn solver handler: runtime error: invalid memory address or nil pointer dereference
goroutine 31 [running]:
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn.func1()
github.com/caddyserver/certmagic@v0.17.2/solvers.go:204 +0x65
panic({0x55816db5f1c0, 0x55816e0b78d0})
runtime/panic.go:884 +0x212
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x55816d82ea2a, 0x25})
go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc000131380?, {0x55816d82ea2a?, 0x55816d81a87e?}, {0xc000470e00, 0x4, 0x4})
go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc0000b24d0, 0xc000207860)
github.com/caddyserver/certmagic@v0.17.2/handshake.go:67 +0xbd3
crypto/tls.(*Config).getCertificate(0xc0001b6c00, 0xc000207860)
crypto/tls/common.go:1069 +0x42
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc0001ddc38)
crypto/tls/handshake_server_tls13.go:367 +0x354
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc0001ddc38)
crypto/tls/handshake_server_tls13.go:59 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0000c7180, {0x55816dc4d6b8, 0xc000128ac0})
crypto/tls/handshake_server.go:54 +0xd0
crypto/tls.(*Conn).handshakeContext(0xc0000c7180, {0x55816dc4d6f0, 0xc000034090})
crypto/tls/conn.go:1462 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
crypto/tls/conn.go:1389
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn(0x55816d3e4d6a, {0x55816dc52798?, 0xc0000c7180?})
github.com/caddyserver/certmagic@v0.17.2/solvers.go:214 +0xc6
created by github.com/caddyserver/certmagic.(*tlsALPNSolver).Present.func1
github.com/caddyserver/certmagic@v0.17.2/solvers.go:192 +0x159
2022/12/05 01:41:22 panic: tls-alpn solver handler: runtime error: invalid memory address or nil pointer dereference
goroutine 52 [running]:
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn.func1()
github.com/caddyserver/certmagic@v0.17.2/solvers.go:204 +0x65
panic({0x55816db5f1c0, 0x55816e0b78d0})
runtime/panic.go:884 +0x212
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x55816d82ea2a, 0x25})
go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc0001ae270?, {0x55816d82ea2a?, 0x55816d81a87e?}, {0xc000471c00, 0x4, 0x4})
go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc0000b24d0, 0xc000207930)
github.com/caddyserver/certmagic@v0.17.2/handshake.go:67 +0xbd3
crypto/tls.(*Config).getCertificate(0xc0001b6c00, 0xc000207930)
crypto/tls/common.go:1069 +0x42
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc0001ddc38)
crypto/tls/handshake_server_tls13.go:367 +0x354
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc0001ddc38)
crypto/tls/handshake_server_tls13.go:59 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0001aa000, {0x55816dc4d6b8, 0xc000128d80})
crypto/tls/handshake_server.go:54 +0xd0
crypto/tls.(*Conn).handshakeContext(0xc0001aa000, {0x55816dc4d6f0, 0xc000034090})
crypto/tls/conn.go:1462 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
crypto/tls/conn.go:1389
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn(0x55816d3e4d6a, {0x55816dc52798?, 0xc0001aa000?})
github.com/caddyserver/certmagic@v0.17.2/solvers.go:214 +0xc6
created by github.com/caddyserver/certmagic.(*tlsALPNSolver).Present.func1
github.com/caddyserver/certmagic@v0.17.2/solvers.go:192 +0x159
1.67020448284959e+09    error   acme_client     challenge failed        {"identifier": "foo.bar", "challenge_type": "tls-alpn-01", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "[ip] Error getting validation data", "instance": "", "subproblems": []}}
1.6702044828496466e+09  error   acme_client     validating authorization        {"identifier": "foo.bar", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "[ip] Error getting validation data", "instance": "", "subproblems": []}, "order": "https://acme-v02.api.letsencrypt.org/acme/order/856266307/150430015387", "attempt": 1, "max_attempts": 3}
1.6702044828497117e+09  error   obtain  could not get certificate from issuer   {"identifier": "foo.bar", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:connection - [ip] Error getting validation data"}
1.6702044828497357e+09  info    obtain  releasing lock  {"identifier": "foo.bar"}
FATAL[0006] start service: initialize inbound/trojan[trojan-in]: create TLS config: foo.bar: obtaining certificate: [foo.bar] Obtain: [foo.bar] solving challenge: foo.bar: [foo.bar] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - [ip] Error getting validation data (ca=https://acme-v02.api.letsencrypt.org/directory)
[indianamarquez0@instance-1 ~]$ sudo sing-box run -c /var/lib/sing-box/config.json
1.6702044997658892e+09  info    maintenance     started background certificate maintenance      {"cache": "0xc00019e150"}
1.6702044998062692e+09  info    obtain  acquiring lock  {"identifier": "foo.bar"}
1.670204499809481e+09   info    obtain  lock acquired   {"identifier": "foo.bar"}
1.670204499809655e+09   info    obtain  obtaining certificate   {"identifier": "foo.bar"}
1.6702044998104115e+09  info    waiting on internal rate limiter        {"identifiers": ["foo.bar"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": "account@foo.bar"}
1.6702044998104534e+09  info    done waiting on internal rate limiter   {"identifiers": ["foo.bar"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": "account@foo.bar"}
1.6702045010562642e+09  info    acme_client     trying to solve challenge       {"identifier": "foo.bar", "challenge_type": "tls-alpn-01", "ca": "https://acme-v02.api.letsencrypt.org/directory"}
2022/12/05 01:41:41 panic: tls-alpn solver handler: runtime error: invalid memory address or nil pointer dereference
goroutine 29 [running]:
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn.func1()
github.com/caddyserver/certmagic@v0.17.2/solvers.go:204 +0x65
panic({0x560209d251c0, 0x56020a27d8d0})
runtime/panic.go:884 +0x212
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x5602099f4a2a, 0x25})
go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc0004cc2d0?, {0x5602099f4a2a?, 0x5602099e087e?}, {0xc00038ca00, 0x4, 0x4})
go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc0001da160, 0xc000334000)
github.com/caddyserver/certmagic@v0.17.2/handshake.go:67 +0xbd3
crypto/tls.(*Config).getCertificate(0xc0001e2780, 0xc000334000)
crypto/tls/common.go:1069 +0x42
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc000255c38)
crypto/tls/handshake_server_tls13.go:367 +0x354
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc000255c38)
crypto/tls/handshake_server_tls13.go:59 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0000ed500, {0x560209e136b8, 0xc000404200})
crypto/tls/handshake_server.go:54 +0xd0
crypto/tls.(*Conn).handshakeContext(0xc0000ed500, {0x560209e136f0, 0xc000090000})
crypto/tls/conn.go:1462 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
crypto/tls/conn.go:1389
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn(0x5602095aad6a, {0x560209e18798?, 0xc0000ed500?})
github.com/caddyserver/certmagic@v0.17.2/solvers.go:214 +0xc6
created by github.com/caddyserver/certmagic.(*tlsALPNSolver).Present.func1
github.com/caddyserver/certmagic@v0.17.2/solvers.go:192 +0x159
2022/12/05 01:41:41 panic: tls-alpn solver handler: runtime error: invalid memory address or nil pointer dereference
goroutine 35 [running]:
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn.func1()
github.com/caddyserver/certmagic@v0.17.2/solvers.go:204 +0x65
panic({0x560209d251c0, 0x56020a27d8d0})
runtime/panic.go:884 +0x212
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x5602099f4a2a, 0x25})
go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc00041cff0?, {0x5602099f4a2a?, 0x5602099e087e?}, {0xc000402d00, 0x4, 0x4})
go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc0001da160, 0xc0003961a0)
github.com/caddyserver/certmagic@v0.17.2/handshake.go:67 +0xbd3
crypto/tls.(*Config).getCertificate(0xc0001e2780, 0xc0003961a0)
crypto/tls/common.go:1069 +0x42
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc0000a9c38)
crypto/tls/handshake_server_tls13.go:367 +0x354
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc0000a9c38)
crypto/tls/handshake_server_tls13.go:59 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0001a0000, {0x560209e136b8, 0xc00012e0c0})
crypto/tls/handshake_server.go:54 +0xd0
crypto/tls.(*Conn).handshakeContext(0xc0001a0000, {0x560209e136f0, 0xc000090000})
crypto/tls/conn.go:1462 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
crypto/tls/conn.go:1389
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn(0x0, {0x560209e18798?, 0xc0001a0000?})
github.com/caddyserver/certmagic@v0.17.2/solvers.go:214 +0xc6
created by github.com/caddyserver/certmagic.(*tlsALPNSolver).Present.func1
github.com/caddyserver/certmagic@v0.17.2/solvers.go:192 +0x159
2022/12/05 01:41:41 panic: tls-alpn solver handler: runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn.func1()
github.com/caddyserver/certmagic@v0.17.2/solvers.go:204 +0x65
panic({0x560209d251c0, 0x56020a27d8d0})
runtime/panic.go:884 +0x212
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x5602099f4a2a, 0x25})
go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc0004cc390?, {0x5602099f4a2a?, 0x5602099e087e?}, {0xc00038cc00, 0x4, 0x4})
go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc0001da160, 0xc0003340d0)
github.com/caddyserver/certmagic@v0.17.2/handshake.go:67 +0xbd3
crypto/tls.(*Config).getCertificate(0xc0001e2780, 0xc0003340d0)
crypto/tls/common.go:1069 +0x42
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc000255c38)
crypto/tls/handshake_server_tls13.go:367 +0x354
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc000255c38)
crypto/tls/handshake_server_tls13.go:59 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0000ed880, {0x560209e136b8, 0xc000404240})
crypto/tls/handshake_server.go:54 +0xd0
crypto/tls.(*Conn).handshakeContext(0xc0000ed880, {0x560209e136f0, 0xc000090000})
crypto/tls/conn.go:1462 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
crypto/tls/conn.go:1405
crypto/tls.(*Conn).Handshake(...)
crypto/tls/conn.go:1389
github.com/caddyserver/certmagic.(*tlsALPNSolver).handleConn(0x5602095aad6a, {0x560209e18798?, 0xc0000ed880?})
github.com/caddyserver/certmagic@v0.17.2/solvers.go:214 +0xc6
created by github.com/caddyserver/certmagic.(*tlsALPNSolver).Present.func1
github.com/caddyserver/certmagic@v0.17.2/solvers.go:192 +0x159
1.6702045021539721e+09  error   acme_client     challenge failed        {"identifier": "foo.bar", "challenge_type": "tls-alpn-01", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "[ip] Error getting validation data", "instance": "", "subproblems": []}}
1.6702045021540356e+09  error   acme_client     validating authorization        {"identifier": "foo.bar", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "[ip] Error getting validation data", "instance": "", "subproblems": []}, "order": "https://acme-v02.api.letsencrypt.org/acme/order/856266307/150430091017", "attempt": 1, "max_attempts": 3}
1.6702045021540844e+09  error   obtain  could not get certificate from issuer   {"identifier": "foo.bar", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:connection - [ip] Error getting validation data"}
1.6702045021541054e+09  info    obtain  releasing lock  {"identifier": "foo.bar"}
FATAL[0002] start service: initialize inbound/trojan[trojan-in]: create TLS config: foo.bar: obtaining certificate: [foo.bar] Obtain: [foo.bar] solving challenge: foo.bar: [foo.bar] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - [ip] Error getting validation data (ca=https://acme-v02.api.letsencrypt.org/directory)
```

</details>

**Comment by nekohasekai** [comment]
Are you sure the submitted configuration is complete?

**Comment by nekohasekai** [comment]
Try a828c3b5da030365d9b327d9eef64a38d7697e6a
