### ISSUE TITLE
使用多路复用和 Packet Encoding 选择 Packet 连接服务端后，服务端崩溃

### ISSUE THREAD

**Issue by yneit** [SagerNet/sing-box#273]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

客户端使用 SagerNet，协议选择 vmess，Packet Encoding 选择 Packet，再到设置中开启多路复用。

启用连接，使用 SagerNet 工具中的 NAT 行为发现，可以看到服务端崩溃。

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1

Environment: go1.19.3 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: df3b130dc9a16211d7a68ab7737fd96695b4dec2
CGO: disabled
```

</details>

### Server and client configuration file

`server.json`
<details>

```console
{
    "log": {},
    "dns": {
        "servers": [
            {
                "tag": "local",
                "address": "local"
            }
        ]
    },
    "inbounds": [
        {
            "type": "vmess",
            "tag": "vmess-in",
            "users": [
                {
                    "name": "",
                    "uuid": "<UUID>",
                    "alterId": 0
                }
            ],
            "tls": {},
            "transport": {
                "type": "ws",
                "path": "/<UUID>/",
                "max_early_data": 2048,
                "headers": {}
            },
            "listen": "127.0.0.1",
            "listen_port": 12345
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct-out"
        }
    ],
    "route": {},
    "experimental": {}
}
```

</details>

`SagerNet.json`

<details>

```console
{
  "outbounds": [
    {
      "domainStrategy": "UseIP",
      "mux": {
        "concurrency": 8,
        "enabled": true,
        "packetEncoding": "packet"
      },
      "protocol": "vmess",
      "settings": {
        "packetEncoding": "packet",
        "vnext": [
          {
            "address": "<address>",
            "port": 443,
            "users": [
              {
                "id": "<uuid>",
                "security": "zero"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {},
        "wsSettings": {
          "headers": {
            "Host": "<address>"
          },
          "path": "/<uuid>/"
        }
      },
      "tag": "proxy-global-53"
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "freedom",
      "tag": "bypass"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    },
    {
      "protocol": "dns",
      "settings": {
        "address": "dns.google",
        "userLevel": 1
      },
      "tag": "dns-out"
    }
  ],
  "ping": {
    "disableIPv6": false,
    "protocol": "unprivileged"
  },
  "policy": {
    "levels": {
      "1": {
        "connIdle": 30
      }
    },
    "system": {
      "statsOutboundDownlink": true,
      "statsOutboundUplink": true
    }
  }
}
```
</details>

### Server and client log file

<details>

```console
sing-box[1766925]: panic: interface conversion: *vmess.serverMuxPacketConn is not vmess.PacketConn: missing method Read
sing-box[1766925]: goroutine 192 [running]:
sing-box[1766925]: github.com/sagernet/sing-box/inbound.(*VMess).newPacketConnection(_, {_, _}, {_, _}, {{0xc000043d88, 0x8}, {0xfc7363, 0x5}, 0x0, ...})
sing-box[1766925]:         /home/sekai/Projects/sing-box/inbound/vmess.go:175 +0x294
sing-box[1766925]: github.com/sagernet/sing-box/adapter.(*myUpstreamContextHandlerWrapper).NewPacketConnection(0xc000078f20, {0x1162de0, 0xc000020a80}, {0x11688e0, 0xc000010588}, {{0x0, 0x0}, {{{0x0, 0x0}, 0x0}, ...}, ...})
sing-box[1766925]:         /home/sekai/Projects/sing-box/adapter/upstream.go:110 +0x356
sing-box[1766925]: github.com/sagernet/sing-vmess.(*serverSession).recv.func1()
sing-box[1766925]:         pkg/mod/github.com/sagernet/sing-vmess@v0.1.0/mux.go:149 +0x263
sing-box[1766925]: created by github.com/sagernet/sing-vmess.(*serverSession).recv
sing-box[1766925]:         pkg/mod/github.com/sagernet/sing-vmess@v0.1.0/mux.go:138 +0x99b
systemd[1]: sing.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: sing.service: Failed with result 'exit-code'.
```

</details>

**Comment by oplle** [comment]
关于多路复用，我也有个问题需要反馈下。尝试的版本1.1.0和1.0.7，协议是shadowtls（非tun）

当我添加并开启多路复用，三个max相关的值不管设置为多少。
使用IDM走sing的代理，单线程下载https://lg.naranja.tech/1024MB.test这个文件，下载几秒钟之后取消下载，然后sing会一直占用下载网速，测试过多次，也测试过v4v6都会这样，v6应该是更容易复现。
只有关闭或删除多路复用，才不会出现
我后来又使用了多路复用里面的另一个参数，"protocol": "smux",将smux改为"protocol": "yamux",之后，就不会再出现这种情况了，但是yamux的速度不如smux，不知道为什么会出现这种情况，所以来这里反馈下。

**Comment by nekohasekai** [comment]
Try c95e4a13a17588a1853a076917f24d27b360dd2b

**Comment by yneit** [comment]
不崩溃了，但是选择 Packet 后 udp 不通。

log
<details>

```
INFO[0005] [1330519997] outbound/direct[direct-out]: outbound connection to <vps ip>:29671
INFO[0005] [1330519997] router: inbound multiplex connection to <vps ip>:29671
INFO[0005] [1330519997] outbound/direct[direct-out]: outbound connection to <vps ip>:29671
INFO[0005] [1330519997] router: inbound multiplex connection to <vps ip>:29671
INFO[0005] [1330519997] outbound/direct[direct-out]: outbound connection to <vps ip>:29671
INFO[0005] [1330519997] router: inbound multiplex connection to <vps ip>:29671
INFO[0005] [1330519997] outbound/direct[direct-out]: outbound connection to <vps ip>:29671
INFO[0005] [1833759561] inbound/vmess[vmess-in]: inbound connection from <client ip>:46538
INFO[0006] [4187452467] inbound/vmess[vmess-in]: [username] inbound connection to 8.8.8.8:853
INFO[0006] [4187452467] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
INFO[0007] [4187452467] inbound/vmess[vmess-in]: [username] inbound connection to [2607:f8b0:4003:c3c::68]:443
INFO[0007] [4187452467] outbound/direct[direct-out]: outbound connection to [2607:f8b0:4003:c3c::68]:443
INFO[0007] [4187452467] inbound/vmess[vmess-in]: [username] inbound connection to 142.250.149.103:443
INFO[0007] [4187452467] outbound/direct[direct-out]: outbound connection to 142.250.149.103:443
INFO[0007] [4187452467] inbound/vmess[vmess-in]: [username] inbound connection to [2607:f8b0:4003:c18::5f]:443
INFO[0007] [4187452467] outbound/direct[direct-out]: outbound connection to [2607:f8b0:4003:c18::5f]:443
DEBUG[0007] [4187452467] inbound/vmess[vmess-in]: connection closed: upload: EOF | download: EOF
DEBUG[0009] [4187452467] inbound/vmess[vmess-in]: connection closed: upload: EOF | download: EOF
DEBUG[0009] [4187452467] inbound/vmess[vmess-in]: connection closed: upload: EOF | download: EOF
DEBUG[0009] [4187452467] inbound/vmess[vmess-in]: connection closed: upload: EOF | download: EOF
INFO[0012] [3399497796] inbound/vmess[vmess-in]: inbound connection from <client ip>:39420
INFO[0012] [3822295249] inbound/vmess[vmess-in]: [username] inbound connection to [2001:4860:4860::8844]:853
INFO[0012] [3822295249] outbound/direct[direct-out]: outbound connection to [2001:4860:4860::8844]:853
INFO[0015] [3822295249] inbound/vmess[vmess-in]: [username] inbound connection to 172.67.152.9:443
INFO[0015] [3822295249] outbound/direct[direct-out]: outbound connection to 172.67.152.9:443
DEBUG[0016] [3822295249] inbound/vmess[vmess-in]: connection closed: download: EOF | upload: EOF
INFO[0019] [3822295249] inbound/vmess[vmess-in]: [username] inbound connection to 172.67.152.9:443
INFO[0019] [3822295249] outbound/direct[direct-out]: outbound connection to 172.67.152.9:443
DEBUG[0019] [3822295249] inbound/vmess[vmess-in]: connection closed: download: EOF | upload: EOF
INFO[0020] [3822295249] inbound/vmess[vmess-in]: [username] inbound connection to 172.67.152.9:443
INFO[0020] [3822295249] outbound/direct[direct-out]: outbound connection to 172.67.152.9:443
DEBUG[0020] [3822295249] inbound/vmess[vmess-in]: connection closed: download: EOF | upload: EOF
INFO[0021] [3822295249] inbound/vmess[vmess-in]: [username] inbound connection to 172.67.152.9:443
INFO[0021] [3822295249] outbound/direct[direct-out]: outbound connection to 172.67.152.9:443
DEBUG[0021] [3822295249] inbound/vmess[vmess-in]: connection closed: download: EOF | upload: EOF
DEBUG[0022] [1833759561] inbound/vmess[vmess-in]: connection closed: process connection from <client ip>:46538: mux connection closed: read frame header: EOF
INFO[0022] [3822295249] inbound/vmess[vmess-in]: [username] inbound connection to 172.67.152.9:443
INFO[0022] [3822295249] outbound/direct[direct-out]: outbound connection to 172.67.152.9:443
DEBUG[0023] [3822295249] inbound/vmess[vmess-in]: connection closed: download: EOF | upload: EOF
INFO[0025] [3822295249] inbound/vmess[vmess-in]: [username] inbound packet addr connection
INFO[0025] [3822295249] outbound/direct[direct-out]: outbound packet connection
DEBUG[0027] [3399497796] inbound/vmess[vmess-in]: connection closed: process connection from <client ip>:39420: mux connection closed: read frame header: EOF
DEBUG[0027] [3822295249] inbound/vmess[vmess-in]: connection closed: upload: read frame header: EOF | download: read udp [::]:59763: use of closed network connection
DEBUG[0027] [3822295249] inbound/vmess[vmess-in]: connection closed: upload: readfrom tcp [2606:4700:110:84fd:6617:5ece:3a2d:b4ad]:54594->[2001:4860:4860::8844]:853: read frame header: EOF | download: EOF
INFO[0034] [3300608234] inbound/vmess[vmess-in]: inbound connection from <client ip>:60818
INFO[0035] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 149.154.175.56:443
INFO[0035] [3265651950] outbound/direct[direct-out]: outbound connection to 149.154.175.56:443
INFO[0035] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 149.154.175.56:443
INFO[0035] [3265651950] outbound/direct[direct-out]: outbound connection to 149.154.175.56:443
INFO[0035] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 91.108.56.133:443
INFO[0035] [3265651950] outbound/direct[direct-out]: outbound connection to 91.108.56.133:443
INFO[0035] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 91.108.56.133:443
INFO[0035] [3265651950] outbound/direct[direct-out]: outbound connection to 91.108.56.133:443
INFO[0035] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 91.108.56.195:443
INFO[0035] [3265651950] outbound/direct[direct-out]: outbound connection to 91.108.56.195:443
INFO[0035] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 91.108.56.195:443
INFO[0035] [3265651950] outbound/direct[direct-out]: outbound connection to 91.108.56.195:443
INFO[0036] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 149.154.167.41:443
INFO[0036] [3265651950] outbound/direct[direct-out]: outbound connection to 149.154.167.41:443
INFO[0037] [3265651950] inbound/vmess[vmess-in]: [username] inbound connection to 91.108.56.118:443
INFO[0037] [3265651950] outbound/direct[direct-out]: outbound connection to 91.108.56.118:443
INFO[0037] [23315701] inbound/vmess[vmess-in]: inbound connection from <client ip>:60826
INFO[0037] [3442841622] inbound/vmess[vmess-in]: [username] inbound connection to 91.108.56.118:443
INFO[0037] [3442841622] outbound/direct[direct-out]: outbound connection to 91.108.56.118:443
INFO[0037] [3442841622] inbound/vmess[vmess-in]: [username] inbound connection to 149.154.167.222:443
INFO[0037] [3442841622] outbound/direct[direct-out]: outbound connection to 149.154.167.222:443
```

</details>
