### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by imhansai** [SagerNet/sing-box#307]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

panic: runtime error: index out of range [0] with length 0

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1.2

Environment: go1.19.4 darwin/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: ff0693be3210e6434eb1d6be7eb21c5bc1ffde88
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
{
    "log": {
        "disabled": false,
        "level": "info",
        "output": "box.log",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "google",
                "address": "tls://8.8.8.8"
            },
            {
                "tag": "ali",
                "address": "223.5.5.5",
                "detour": "direct"
            },
            {
                "tag": "local",
                "address": "192.168.0.1",
                "detour": "direct"
            },
            {
                "tag": "block",
                "address": "rcode://success"
            }
        ],
        "rules": [
            {
                "geosite": "category-ads-all",
                "server": "block",
                "disable_cache": true
            },
            {
                "domain": [
                    "c78s5.jamjams3.net",
                    "c78s4.jamjams3.net"
                ],
                "geosite": "cn",
                "server": "ali"
            },
            {
                "domain": "ytd-local.com",
                "server": "local"
            }
        ],
        "strategy": "ipv4_only"
    },
    "inbounds": [
        {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "auto_route": true,
            "strict_route": false,
            "sniff": true,
            "domain_strategy": "ipv4_only"
        }
    ],
    "outbounds": [
        {
            "type": "vmess",
            "tag": "vmess-us-out",
            "server": "c78s5.jamjams3.net",
            "server_port": 0,
            "uuid": "uuid",
            "security": "auto",
            "alter_id": 0,
            "network": "tcp"
        },
        {
            "type": "vmess",
            "tag": "vmess-jp-out",
            "server": "c78s4.jamjams3.net",
            "server_port": 0,
            "uuid": "uuid",
            "security": "auto",
            "alter_id": 0,
            "network": "tcp"
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "geosite": "cn",
                "geoip": [
                    "private",
                    "cn"
                ],
                "outbound": "direct"
            },
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            }
        ],
        "auto_detect_interface": true
    }
}
```

</details>

### Server and client log file

<details>

```console
panic: runtime error: index out of range [0] with length 0

goroutine 37520 [running]:
github.com/sagernet/sing-dns.logExchangedResponse({0x2a4f2dd8?, 0xc000288d20?}, {0x1d25388?, 0xc0003e2780?}, 0xc0010d7c48?, 0x1054cd6?)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.1/log.go:29 +0x59d
github.com/sagernet/sing-dns.(*Client).Exchange(0xc0001cce80, {0x1d25388, 0xc0003e2780}, {0x1d27140, 0xc0001fe400}, 0xc0004d01b0, 0x3)
        pkg/mod/github.com/sagernet/sing-dns@v0.1.1/client.go:105 +0x84d
github.com/sagernet/sing-box/route.(*Router).Exchange(0xc000283b00, {0x1d253c0?, 0xc001c64db0?}, 0xc0004d01b0)
        /home/sekai/Projects/sing-box/route/router_dns.go:64 +0x2e5
github.com/sagernet/sing-box/outbound.(*DNS).NewPacketConnection.func1.1()
        /home/sekai/Projects/sing-box/outbound/dns.go:128 +0xad
created by github.com/sagernet/sing-box/outbound.(*DNS).NewPacketConnection.func1
        /home/sekai/Projects/sing-box/outbound/dns.go:127 +0x17d
```

</details>

**Comment by nekohasekai** [comment]
Already fixed.

**Comment by imhansai** [comment]
感谢你的工作:)

**Comment by imhansai** [comment]
看了下 [sing-dns 的提交](https://github.com/SagerNet/sing-dns/commit/6f6f9aa11b3ecab3d708596146f59d77a3fd1e4d#diff-973afd7a3fa6644d1e62a8846c6ee7dde87077ff5c0ee193624f98154eb77687R26),的确这里如果不为空但长度为0，29行调用下标0就会报错。对go不熟悉，不然期待能贡献一份力量。还是谢谢了:)
