### ISSUE TITLE
sing-box does not work when using IPv6 DNS

### ISSUE THREAD

**Issue by xiaoxi404** [SagerNet/sing-box#308]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

When I use ipv6 DNS, sing-box doesn't work.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1.2

Environment: go1.19.4 linux/amd64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api
Revision: ff0693be3210e6434eb1d6be7eb21c5bc1ffde88
CGO: disabled
```
</details>

### Server and client configuration file

<details>

```console
{
  "log": {
    "level": "info"
  },
  "dns": {
    "servers": [
      {
        "address": "2606:4700:4700::1111"
      }
    ]
  },
  "inbounds": [
    {
      "type": "shadowsocks",
      "listen": "::",
      "listen_port": 8080,
      "sniff": true,
      "method": "2022-blake3-aes-128-gcm",
      "password": "8JCsPssfgS8tiRwiMlhARg=="
    }
  ],
  "outbounds": [
    {
      "type": "direct"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      }
    ]
  }
}
```

</details>

### Server and client log file

<details>

```console
FATAL[0000] parse route options: parse "2606:4700:4700::1111": first path segment in URL cannot contain colon
```

</details>

**Comment by nekohasekai** [comment]
Try fa3d519ce5930fa2b573c2c8a50b7fc90f0337ac

**Comment by xiaoxi404** [comment]
> Try [fa3d519](https://github.com/SagerNet/sing-box/commit/fa3d519ce5930fa2b573c2c8a50b7fc90f0337ac)

sing-box still has this bug.

~~~
$ sing-box version

sing-box version 1.1.2

Environment: go1.19.4 linux/amd64
Revision: fa3d519ce5930fa2b573c2c8a50b7fc90f0337ac
CGO: enabled
~~~

**Comment by nekohasekai** [comment]
ef390da3dcbf82c8419a393070aea5b14d96869a

**Comment by xiaoxi404** [comment]
> [ef390da](https://github.com/SagerNet/sing-box/commit/ef390da3dcbf82c8419a393070aea5b14d96869a)

If the dns address is an ipv6 address, ef390da fixed the issue. But if the dns address is a ipv6 address with the protocol name like udp://2606:4700:4700::1111 or udp://[2606:4700:4700::1111], sing-box still doesn't work and thinks the address contains a domain.

~~~
$ ./sing-box version
sing-box version 1.1.2

Environment: go1.19.4 linux/amd64
Tags: with_wireguard
Revision: ef390da3dcbf82c8419a393070aea5b14d96869a
CGO: disabled
~~~

~~~
$ ./sing-box check -c ../test.json
FATAL[0000] parse route options: parse dns server[0]: missing address_resolver
~~~

**Comment by nekohasekai** [comment]
8dc3fdfff625badbd1aaee1a8edfae07cea6b92a

**Comment by Gzxhwq** [comment]
https://github.com/SagerNet/sing-box/commit/8dc3fdfff625badbd1aaee1a8edfae07cea6b92a
崩溃了，并没有用ipv6做dns

```json
"dns": {
    "servers": [
      {
        "tag": "foreign",
        "address": "https://1.1.1.1/dns-query"
      },
      {
        "tag": "local",
        "address": "tls://1.12.12.12",
        "detour": "direct"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "geosite": "category-ads-all",
        "server": "block",
        "disable_cache": true
      },
      {
        "domain": "mydomain.com",
        "geosite": "cn",
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
```

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sagernet/sing/common/metadata.unwrapIPv6Address(...)
	github.com/sagernet/sing@v0.1.5/common/metadata/addr.go:225
github.com/sagernet/sing/common/metadata.ParseSocksaddrHostPort({0x0, 0xf}, 0x0)
	github.com/sagernet/sing@v0.1.5/common/metadata/addr.go:194 +0x14f
github.com/sagernet/sing-box/option.ServerOptions.Build(...)
	github.com/sagernet/sing-box/option/outbound.go:144
github.com/sagernet/sing-box/outbound.NewShadowsocks({_, _}, {_, _}, {_, _}, {_, _}, {{{0xc0002ed390, 0xf}, ...}, ...})
	github.com/sagernet/sing-box/outbound/shadowsocks.go:51 +0x1c7
github.com/sagernet/sing-box/outbound.New({_, _}, {_, _}, {_, _}, {{0xc0002eca90, 0xb}, {0xc0002ecaa0, 0xc}, ...})
	github.com/sagernet/sing-box/outbound/builder.go:29 +0xb1e
github.com/sagernet/sing-box.New({0x11fdf78, 0xc000369680}, {0xc00018fd70, 0xc00007e4b0, {0xc000280000, 0x5, 0x6}, {0xc000380000, 0x26, 0x2a}, ...})
	github.com/sagernet/sing-box/box.go:137 +0x12d2
main.create()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:67 +0x178
main.run()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:99 +0x118
main.glob..func3(0x18e68c0?, {0x104ebdd?, 0x2?, 0x2?})
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:23 +0x1d
github.com/spf13/cobra.(*Command).execute(0x18e68c0, {0xc000046ae0, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x18e6ba0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	github.com/sagernet/sing-box/cmd/sing-box/main.go:30 +0x25
```

**Comment by nekohasekai** [comment]
23a35b3c06304bd0d884f1b24260858afbbae2a5

**Comment by Gzxhwq** [comment]
https://github.com/SagerNet/sing-box/commit/23a35b3c06304bd0d884f1b24260858afbbae2a5 崩溃问题修复。

**Comment by Gzxhwq** [comment]
https://github.com/SagerNet/sing-box/commit/23a35b3c06304bd0d884f1b24260858afbbae2a5 已修复上述崩溃

**Comment by xiaoxi404** [comment]
https://github.com/SagerNet/sing-box/commit/23a35b3c06304bd0d884f1b24260858afbbae2a5 It fixed my issue.
