### ISSUE TITLE
WireGuard outbound does not work properly

### ISSUE THREAD

**Issue by RealTong** [SagerNet/sing-box#319]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

1. 当log disabled: false的时候, 启动sing-box会出现`ERROR outbound/wireguard[wireguard-home]: failed to read packet from tun device: invalid argument` , 并且clash dashboard中wireguard不通. 使用https://gist.github.com/RealTong/3e550aac5714abbcc6de4f90aee3f5ec 这个配置可100%复现
![image](https://user-images.githubusercontent.com/67304509/212482485-eb8e5583-baa0-48fc-8412-fdd04662ac06.png)

2. 当log disabled: true的时候, 会导致CPU 100%, 爆内存内存,  只需要将sing-box-config1.json 中的log disabled改为true, 即可100%复现
![image](https://user-images.githubusercontent.com/67304509/212482431-108c7b05-88de-4032-905b-59f1555b84a0.png)

3. 当log disabled: true的时候, 只需要删除L31-L37即可正常启动sing-box,并且dashboard中wireguard可以连通, 但是由于没有添加route, 所以无法判断wireguard是否正常工作.
![image](https://user-images.githubusercontent.com/67304509/212482960-c300a371-e48c-47c8-8206-9e49c2c0cf0e.png)

4. 当添加2个wireguard时, sing-box 则无法启动. 报错信息如下

```bash
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: uapi: updating private key
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: peer(uYsJ…KcFo) - uapi: created
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: peer(uYsJ…KcFo) - uapi: updating endpoint
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: handshake worker 1 - started
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: tun reader - started
+0800 2023-01-15 00:28:20 ERROR outbound/wireguard[wireguard-home]: failed to read packet from tun device: invalid argument
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: event worker - started
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: encryption worker 1 - started
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: peer(uYsJ…KcFo) - uapi: adding allowedip
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: tun reader - stopped
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: device closing
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: event worker - stopped
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: decryption worker 1 - started
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: decryption worker 1 - stopped
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: handshake worker 1 - stopped
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: routine: encryption worker 1 - stopped
+0800 2023-01-15 00:28:20 DEBUG outbound/wireguard[wireguard-home]: device closed
+0800 2023-01-15 00:28:21 DEBUG outbound/wireguard[wireguard-qingdao]: uapi: updating private key
+0800 2023-01-15 00:28:21 DEBUG outbound/wireguard[wireguard-qingdao]: peer(ZqpJ…XR2U) - uapi: created
+0800 2023-01-15 00:28:21 DEBUG outbound/wireguard[wireguard-qingdao]: peer(ZqpJ…XR2U) - uapi: updating endpoint
+0800 2023-01-15 00:28:21 DEBUG outbound/wireguard[wireguard-qingdao]: peer(ZqpJ…XR2U) - uapi: adding allowedip
panic: send on closed channel

goroutine 1 [running]:
github.com/sagernet/sing-box/transport/wireguard.(*SystemDevice).Start(0xc0000f8680?)
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/transport/wireguard/device_system.go:75 +0x25
github.com/sagernet/sing-box/outbound.(*WireGuard).Start(0x0?)
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/outbound/wireguard.go:175 +0x22
github.com/sagernet/sing-box.(*Box).start(0xc000158000)
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/box.go:207 +0x682
github.com/sagernet/sing-box.(*Box).Start(0xc000106c60?)
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/box.go:188 +0x39
main.create()
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/cmd/sing-box/cmd_run.go:86 +0x3fd
main.run()
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/cmd/sing-box/cmd_run.go:99 +0x118
main.glob..func3(0x1f39ea0?, {0x15f2e70?, 0x2?, 0x2?})
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/cmd/sing-box/cmd_run.go:23 +0x1d
github.com/spf13/cobra.(*Command).execute(0x1f39ea0, {0xc00007cfa0, 0x2, 0x2})
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1f3a180)
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        C:/Users/MY_USERNAME/go/pkg/mod/github.com/sagernet/sing-box@v1.1.4/cmd/sing-box/main.go:30 +0x25
```

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.1.4

Environment: go1.19 windows/amd64
Tags: with_quic,with_wireguard,with_gvisor,with_clash_api,with_ech,with_utls
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console
和gist提供的配置文件一样
{
    "log": {
      "disabled": false,
      "level": "debug",
      "timestamp": true
    },
    "dns": {
      "servers": [
        {
          "tag": "google",
          "address": "tls://8.8.8.8"
        },
        {
          "tag": "local",
          "address": "223.5.5.5",
          "detour": "direct"
        }
      ],
      "rules": [
        {
          "geosite": "cn",
          "server": "local"
        }
      ],
      "strategy": "ipv4_only"
    },
    "route": {
      "final": "Select",
      "auto_detect_interface": true,
      "rules": [
        {
          "ip_cidr": [
            "10.0.0.0/24",
            "10.0.1.0/24"
          ],
          "outbound": "wireguard-home"
        },
        {
          "protocol": "dns",
          "outbound": "dns-out"
        },
        {
          "geosite": "category-ads-all",
          "outbound": "block"
        },
        {
          "geosite": "cn",
          "geoip": "cn",
          "outbound": "direct"
        }
      ]
    },
    "experimental": {
      "clash_api": {
        "external_controller": "127.0.0.1:9820",
        "external_ui": "./yacd/",
        "secret": "",
        "default_mode": "rule",
        "store_selected": false,
        "cache_file": "cache.db"
      }
    },
    "inbounds": [
      {
        "type": "tun",
        "inet4_address": "172.19.0.1/30",
        "auto_route": true,
        "sniff": true
      }
    ],
    "outbounds": [
      {
        "type": "trojan",
        "tag": "San-Jose-Trojan",
        "server": "example.com",
        "server_port": 9964,
        "password": "fuckgfw",
        "tls": {
          "enabled": true,
          "insecure": true
        }
      },
      {
        "type": "wireguard",
        "tag": "wireguard-home",
        "server": "example.com",
        "server_port": 50814,
        "system_interface": true,
        "interface_name": "wg0",
        "local_address": [
          "10.0.1.2/32"
        ],
        "workers": 1,
        "private_key": "key",
        "peer_public_key": "key",
        "mtu": 1420
      },
      {
        "type": "hysteria",
        "tag": "hysteria-out",
        "server": "example.com",
        "server_port": 18004,
        "up": "60 Mbps",
        "up_mbps": 60,
        "down": "60 Mbps",
        "down_mbps": 60,
        "obfs": "obfsString",
        "auth_str": "authString",
        "recv_window_conn": 0,
        "recv_window": 0,
        "disable_mtu_discovery": false,
        "tls": {
          "enabled": true,
          "insecure": true,
          "alpn": [
            "ayaya"
          ]
        }
      },
      {
        "type": "direct",
        "tag": "direct"
      },
      {
        "type": "block",
        "tag": "block"
      },
      {
        "type": "dns",
        "tag": "dns-out"
      },
      {
        "type": "selector",
        "tag": "Select",
        "outbounds": [
          "San-Jose-Trojan",
          "wireguard-home",
          "hysteria-out"
        ],
        "default": "San-Jose-Trojan"
      }
    ]
  }
```

</details>

### Server and client log file

<details>

```console
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: uapi: updating private key
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: decryption worker 1 - started
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: encryption worker 1 - started
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: handshake worker 1 - started
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: tun reader - started
+0800 2023-01-15 00:23:32 ERROR outbound/wireguard[wireguard-home]: failed to read packet from tun device: invalid argument
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: tun reader - stopped
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: event worker - started
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: peer(uYsJ…KcFo) - uapi: created
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: peer(uYsJ…KcFo) - uapi: updating endpoint
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: peer(uYsJ…KcFo) - uapi: adding allowedip
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: device closing
+0800 2023-01-15 00:23:32 INFO router: loaded geoip database: 259 codes
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: interface up requested
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: device closed
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: interface closed, ignored requested state Up
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: event worker - stopped
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: decryption worker 1 - stopped
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: handshake worker 1 - stopped
+0800 2023-01-15 00:23:32 DEBUG outbound/wireguard[wireguard-home]: routine: encryption worker 1 - stopped
+0800 2023-01-15 00:23:32 INFO router: loaded geosite database: 1299 codes
+0800 2023-01-15 00:23:32 INFO router: updated default interface WLAN, index 22
+0800 2023-01-15 00:23:35 INFO inbound/tun[0]: started at tun0
+0800 2023-01-15 00:23:35 INFO clash-api: restful api listening at 127.0.0.1:9820
+0800 2023-01-15 00:23:35 INFO sing-box started (3.833s)
+0800 2023-01-15 00:23:35 INFO [3642445071] inbound/tun[0]: inbound packet connection from 172.19.0.1:137
+0800 2023-01-15 00:23:35 INFO [3642445071] inbound/tun[0]: inbound packet connection to 172.19.0.3:137
+0800 2023-01-15 00:23:35 DEBUG [3642445071] router: sniffed packet protocol: dns
+0800 2023-01-15 00:23:35 DEBUG [3642445071] router: match[1] protocol=dns => dns-out
+0800 2023-01-15 00:23:35 DEBUG [3642445071] dns: exchange FHEPFCELEHFCEPFFFACACACACACACAAA. IN NIMLOC
+0800 2023-01-15 00:23:35 DEBUG [3642445071] dns: exchange FCEFEBEMFEEPEOEHCNFHEJEOEEEPFHCA. IN NIMLOC
+0800 2023-01-15 00:23:35 DEBUG [3642445071] dns: exchange FCEFEBEMFEEPEOEHCNFHEJEOEEEPFHAA. IN NIMLOC
```

</details>

**Comment by nekohasekai** [comment]
您需要提供从零开始的复现步骤以帮助调试，而不是只有您能运行的配置。

**Comment by lyc8503** [comment]
可以复现提到的问题, Windows 系统下创建两个系统 TUN 网卡时 enable logging 则会崩溃.
报错 `failed to read packet from tun device: invalid argument` 和 `panic: send on closed channel`, 与上面的回复一致.

**Comment by malikshi** [comment]
i got similar issues with error `err device or resource busy` when wg outbound speed still high, the issues comes up when i am add/del users in my config so i need restart sing-box services, sometimes i got those error. and need to reboot VM/VPS Debian
