### ISSUE TITLE
badhttp2 or grpc running on server have memory issue in golang 1.20 build

### ISSUE THREAD

**Issue by wsvg14** [SagerNet/sing-box#392]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

I am running singbox in 3 servers , 2 archlinux with golang 1.20 build , 1 debian testing with golang 1.19 build . all in the dev-next branch building on server.
golang 1.20 build will cause memory crash when using http2 or grpc server , but didn't appear on 1.19 build

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.2-beta5

Environment: go1.20 linux/amd64
Tags: with_quic,with_wireguard,with_acme
Revision: 0ca344df5f5ec8b863dbb856971cd01ac8261c16
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console
{
      "type": "trojan",
      "tag": "trojan-grpc-in",                                
      "listen": "127.0.0.1",
      "listen_port": 31301,
      "users": [
        {
          "password": "xxx",
          "name": "rage@outlook.com"
        }
      ],                                                      "transport": {
        "type": "grpc",
        "service_name": "xxxx"
      }
    },
```

</details>

### Server and client log file

<details>

```console
Started sing-box service.
INFO[0000] inbound/trojan[trojan-ws-in]: tcp server started at 127.0.0.1:12001
INFO[0000] inbound/trojan[trojan-grpc-in]: tcp server started at 127.0.0.1:2009
INFO[0000] inbound/vmess[vmess-ws-in]: tcp server started at 127.0.0.1:18080
INFO[0000] inbound/vmess[vmess-grpc-in]: tcp server started at 127.0.0.1:18081
INFO[0000] inbound/hysteria[4]: udp server started at [::]:443
INFO[0000] inbound/hysteria[4]: udp server started at [::]:443
INFO[0000] inbound/direct[direct-in]: tcp server started at [::]:2053
INFO[0000] inbound/direct[direct-in]: udp server started at [::]:5201
INFO[0000] sing-box started (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa18275]
goroutine 10 [running]:
github.com/sagernet/badhttp2.ConfigureServer(0xc0000ec2d0, 0x0?)
        github.com/sagernet/badhttp2@v0.0.0-20230228040529-408b0b8e774d/server.go:297 +0x135
github.com/sagernet/sing-box/transport/v2raygrpclite.(*Server).Serve(0xc000039180, {0xfcf3c0, 0xc000153b00})
        github.com/sagernet/sing-box/transport/v2raygrpclite/server_badhttp.go:102 +0x45
github.com/sagernet/sing-box/inbound.(*Trojan).Start.func1()
        github.com/sagernet/sing-box/inbound/trojan.go:118 +0x4b
created by github.com/sagernet/sing-box/inbound.(*Trojan).Start
        github.com/sagernet/sing-box/inbound/trojan.go:117 +0x237
sing-box.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sing-box.service: Failed with result 'exit-code'.
```

</details>

**Comment by wsvg14** [comment]
fix the full log

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/b453694cfbdfe8f892a5ea7252bbc1123552f566

**Comment by wsvg14** [comment]
> [b453694](https://github.com/SagerNet/sing-box/commit/b453694cfbdfe8f892a5ea7252bbc1123552f566)

have fixed
