### ISSUE TITLE
DNS handling panic

### ISSUE THREAD

**Issue by mazzz1y** [SagerNet/sing-box#400]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

After a few days of uptime, sing-box crashed with a panic.

I am unable to reproduce this issue, so I do not have any debug logs or other information since they were disabled. Perhaps someone else will be able to catch the issue.

Please see panic messsage in the logs above

### Version of sing-box

<details>

```console
$ sing-box version 1.2-beta5

Environment: go1.20.1 linux/amd64
Tags: with_v2ray_api
Revision: cd5c2a7999b157e3ca25b35a958a050efee9456c
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```json
{
  "log": {
    "disabled": true,
    "level": "debug"
  },
  "dns": {
    "final": "gateway",
    "strategy": "ipv4_only",
    "rules": [
      {
        "outbound": [
          "1-out",
          "2-out",
          "3-out",
          "4-out",
          "5-out",
          "6-out",
          "7-out",
          "8-out",
          "9-out"
        ],
        "server": "local",
        "disable_cache": true
      },
      {
        "geosite": [
          "private",
          "category-ads-all"
        ],
        "domain_suffix": ".internal",
        "server": "block",
        "disable_cache": true
      }
    ],
    "servers": [
      {
        "tag": "gateway",
        "address": "192.168.0.1",
        "detour": "direct-out"
      },
      {
        "tag": "local",
        "address": "local",
        "detour": "direct-out"
      },
      {
        "tag": "block",
        "address": "rcode://refused"
      }
    ]
  }
}
```

</details>

### Server and client log file

<details>

```console
panic: runtime error: slice bounds out of range [:106089872899272] with capacity 12
goroutine 36955391 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).ReadFullFrom(0xf3f160?, {0xf3ee40?, 0xc0049dd830?}, 0x0?)
	github.com/sagernet/sing@v0.1.8-0.20230221060643-3401d210384b/common/buf/buffer.go:205 +0xaf
github.com/sagernet/sing-box/common/sniff.StreamDomainNameQuery.func1({0xf40100?, 0xc00648d520?})
	github.com/sagernet/sing-box/common/sniff/dns.go:37 +0x2d
github.com/sagernet/sing/common/task.(*Group).Run.func1()
	github.com/sagernet/sing@v0.1.8-0.20230221060643-3401d210384b/common/task/task.go:59 +0x93
created by github.com/sagernet/sing/common/task.(*Group).Run
	github.com/sagernet/sing@v0.1.8-0.20230221060643-3401d210384b/common/task/task.go:58 +0x225
```

</details>

**Comment by WitchHuntTV** [comment]
Same issue after updated to 1.2-beta6, Using REALITY.
