### ISSUE TITLE
参考示例在服务端配置`ip_rules`分流特定流量至WireGuard后，sing-box返回panic崩溃

### ISSUE THREAD

**Issue by 70599** [SagerNet/sing-box#470]
### Welcome

- [ ] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

参考[示例](https://github.com/SagerNet/sing-box/blob/dev-next/docs/examples/wireguard-direct.md)在服务端配置`ip_rules`分流特定流量至WireGuard后，sing-box返回panic崩溃

### Version of sing-box

<details>

```console
sing-box version 1.2.0-ee4e51b

Environment: go1.20.2 linux/amd64
Tags: with_low_memory,with_quic,with_gvisor,with_wireguard,with_reality_server
Revision: ee4e51b3cd4d1a9aaa58d13be40026c08500abf6
CGO: disabled
```

</details>

### Server and client configuration file

<details>
参考[示例](https://github.com/SagerNet/sing-box/blob/dev-next/docs/examples/wireguard-direct.md)在服务端新增的分流配置：

```json
"route": {
  "geoip": {
    "download_url": "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db"
  },
  "geosite": {
    "download_url": "https://github.com/1715173329/sing-geosite/releases/latest/download/geosite.db"
  },
  "ip_rules": [
    {
      "inbound": [
        "_dns_in"
      ],
      "domain": [
        "engage.cloudflareclient.com"
      ],
      "action": "return"
    },
    {
      "geosite": [
        "cn",
        "telegram"
      ],
      "geoip": [
        "cn",
        "telegram"
      ],
      "action": "direct",
      "outbound": "_wg_out"
    }
  ],
  "rules": [
    {
      "inbound": [
        "_dns_in"
      ],
      "outbound": "_dns_out"
    },
    {
      "geosite": [
        "category-ads-all"
      ],
      "outbound": "_block"
    }
  ],
  "final": "_direct_out"
}
```

</details>

### Server and client log file

<details>

服务端崩溃信息：

```console
panic: unknown value

goroutine 1 [running]:
github.com/sagernet/sing/common/format.ToString({0xc00014dfd8?, 0x2, 0x1b2?})
	github.com/sagernet/sing@v0.2.1/common/format/fmt.go:56 +0x5b0
github.com/sagernet/sing/common/exceptions.New(...)
	github.com/sagernet/sing@v0.2.1/common/exceptions/error.go:24
github.com/sagernet/sing-box/option.(*RouteAction).UnmarshalJSON(0xc000158f51, {0xc00019a64e, 0x8, 0x1b2})
	github.com/sagernet/sing-box/option/rule_ip.go:101 +0x105
encoding/json.(*decodeState).literalStore(0xc00017d2e8, {0xc00019a64e, 0x8, 0x1b2}, {0xe457c0?, 0xc000158f51?, 0x5?}, 0x0)
	encoding/json/decode.go:872 +0x22bc
encoding/json.(*decodeState).value(0xc00017d2e8, {0xe457c0?, 0xc000158f51?, 0x6?})
	encoding/json/decode.go:388 +0x126
encoding/json.(*decodeState).object(0xc00017d2e8, {0xe4d540?, 0xc000158e10?, 0xc00014e648?})
	encoding/json/decode.go:775 +0xd45
encoding/json.(*decodeState).value(0xc00017d2e8, {0xe4d540?, 0xc000158e10?, 0xc00014e698?})
	encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).unmarshal(0xc00017d2e8, {0xe4d540?, 0xc000158e10?})
	encoding/json/decode.go:181 +0x168
encoding/json.(*Decoder).Decode(0xc00017d2c0, {0xe4d540, 0xc000158e10})
	encoding/json/stream.go:73 +0x191
github.com/sagernet/sing-box/option.UnmarshallExcluded({0xc000136efe, 0x9f, 0xf02}, {0xdec7e0?, 0xc000158e00?}, {0xe4d540?, 0xc000158e10})
	github.com/sagernet/sing-box/option/json.go:74 +0x35f
github.com/sagernet/sing-box/option.(*IPRule).UnmarshalJSON(0xc000158e00, {0xc000136efe, 0x9f, 0xf02})
	github.com/sagernet/sing-box/option/rule_ip.go:50 +0x13e
encoding/json.(*decodeState).object(0xc0000bcb68, {0xf10de0?, 0xc000158e00?, 0xb?})
	encoding/json/decode.go:613 +0x6ef
encoding/json.(*decodeState).value(0xc0000bcb68, {0xf10de0?, 0xc000158e00?, 0x1?})
	encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).array(0xc0000bcb68, {0xe010e0?, 0xc0000be780?, 0xf74fe0?})
	encoding/json/decode.go:562 +0x65b
encoding/json.(*decodeState).value(0xc0000bcb68, {0xe010e0?, 0xc0000be780?, 0x8?})
	encoding/json/decode.go:364 +0x7e
encoding/json.(*decodeState).object(0xc0000bcb68, {0xdec1a0?, 0xc0000be678?, 0xe171c0?})
	encoding/json/decode.go:775 +0xd45
encoding/json.(*decodeState).value(0xc0000bcb68, {0xdec1a0?, 0xc0000be678?, 0x5?})
	encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).object(0xc0000bcb68, {0xdec860?, 0xc0000be620?, 0xc0000eb308?})
	encoding/json/decode.go:775 +0xd45
encoding/json.(*decodeState).value(0xc0000bcb68, {0xdec860?, 0xc0000be620?, 0xc0000eb358?})
	encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).unmarshal(0xc0000bcb68, {0xdec860?, 0xc0000be620?})
	encoding/json/decode.go:181 +0x168
encoding/json.(*Decoder).Decode(0xc0000bcb40, {0xdec860, 0xc0000be620})
	encoding/json/stream.go:73 +0x191
github.com/sagernet/sing-box/option.(*Options).UnmarshalJSON(0x7ffc46d01eb5?, {0xc0000f4a00, 0x1329, 0x132a})
	github.com/sagernet/sing-box/option/config.go:27 +0x20c
main.readConfigAt({0x7ffc46d01eb5, 0x19})
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:58 +0x1a5
main.readConfig()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:72 +0xa8
main.readConfigAndMerge()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:101 +0x58
main.create()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:119 +0x98
main.run()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:162 +0x118
main.glob..func7(0x17dda00?, {0xfc967f?, 0x2?, 0x2?})
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:27 +0x1d
github.com/spf13/cobra.(*Command).execute(0x17dda00, {0xc000072f40, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x17ddce0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	github.com/sagernet/sing-box/cmd/sing-box/main.go:33 +0x25
```

</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/4e2c16b7c2af9f72b1e6ee6ebba89fb7d0b11a2a

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/cfadbbb33a173f65150f8cf33a1bd0ef3be045d0

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/76ac135b11809f5ac9ed65af8de8d3bb9de227d5

**Comment by nekohasekai** [comment]
无法重现，请提供完整配置文件。

**Comment by nekohasekai** [comment]
目前只有 tun 入站包含 L3 支持，因为其他类型的入站都建立在 L4 (TCP/UDP) 之上。

**Comment by nekohasekai** [comment]
> 是不是只有tun入站，wireguard出站的组合，支持ip_rules分流？

目前是的。
