### ISSUE TITLE
panic: close of nil channel

### ISSUE THREAD

**Issue by Hryniuk1** [SagerNet/sing-box#517]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

The connection is constantly interrupted when using Vmess+WS . Sing-box server - g6438c83 github build. Client v2rayNG 1.8.2 ( Xray 1.8.0 ). In my case, to reproduce the error, it is enough just to ping the server multiple times in the v2rayng application, after which the connection is interrupted

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.3-beta3

Environment: go1.20.3 linux/arm64
Tags: with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api,with_acme,with_reality_server
Revision: 6438c836fa698e89743074f368b641a9d6e452e5
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console

{
  "log": {
    "level": "debug"
  },
  "inbounds": [
    {
      "type": "vmess",
      "tag": "vmess-80-in",
      "listen": "::",
      "listen_port": 80,
      "tcp_fast_open": true,
      "udp_fragment": true,
      "sniff": true,
      "sniff_override_destination": false,
      "proxy_protocol_accept_no_header": false,
      "users": [
        {
          "name": "user",
          "uuid": "UUID",
          "alterId": 0
        },
        {
          "name": "other",
          "uuid": "UUID",
          "alterId": 0
        }
      ],
      "transport": {
        "type": "ws",
        "headers": {
        	"Host": "google.com"
        },
        "path": "/",
        "max_early_data": 0,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
	}
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
	{
      "type": "wireguard",
      "tag": "WARP",
      "server": "engage.cloudflareclient.com",
      "server_port": 2408,
      "system_interface": false,
      "interface_name": "wg0",
      "local_address": [
        "172.16.0.2/32",
		"2606:4700:110:871d:a289:b031:b245:9dc1/128"
      ],
      "private_key": "PRIVATE_KEY",
      "peer_public_key": "PUBLIC_KEY",
      "reserved": [0, 0, 0],
      "workers": 4,
      "mtu": 1280,
      "network": "tcp"
    }
  ],
  "route": {
    "geoip": {
      "path": "/etc/sing-box/geoip.db",
      "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
	  "download_detour": "direct"
    },
    "geosite": {
      "path": "/etc/sing-box/geosite.db",
      "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
	  "download_detour": "direct"
    },
	"rules": [
      {
        "protocol": [
          "bittorrent"
        ],
        "outbound": "block"
      },
      {
        "geosite": [
          "instagram",
          "openai",
          "zoom"
        ],
        "outbound": "WARP"
      }
    ]
  }
}
```

Xray client config ( Generated by v2rayNG 1.8.2 )
```console
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "SERVER_IP",
            "port": 80,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "UUID",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "httpSettings": {
          "host": [
            "google.com"
          ],
          "path": "/"
        },
        "network": "ws",
        "security": "",
        "tcpSettings": {
          "header": {
            "request": {
              "headers": {
                "Host": [
                  "google.com"
                ]
              },
              "path": [
                "/"
              ]
            },
            "type": "http"
          }
        },
        "wsSettings": {
          "headers": {
            "Host": "google.com"
          },
          "path": "/"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```

</details>

### Server and client log file

<details>

```console
апр 09 12:04:10 instance-20230331-1942 sing-box[1431]: panic: close of nil channel
апр 09 12:04:10 instance-20230331-1942 sing-box[1431]: goroutine 270 [running]:
апр 09 12:04:10 instance-20230331-1942 sing-box[1431]: github.com/sagernet/sing/common/bufio/deadline.(*pipeDeadline).set.func1()
апр 09 12:04:10 instance-20230331-1942 sing-box[1431]:         github.com/sagernet/sing@v0.2.3-0.20230409075123-3adaa7c59fdf/common/bufio/deadline/pipe.go:53 +0x24
апр 09 12:04:10 instance-20230331-1942 sing-box[1431]: created by time.goFunc
апр 09 12:04:10 instance-20230331-1942 sing-box[1431]:         time/sleep.go:176 +0x38
апр 09 12:04:10 instance-20230331-1942 systemd[1]: sing-box@test.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit sing-box@test.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 2.
апр 09 12:04:10 instance-20230331-1942 systemd[1]: sing-box@test.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit sing-box@test.service has entered the 'failed' state with result 'exit-code'.
апр 09 12:04:20 instance-20230331-1942 systemd[1]: sing-box@test.service: Scheduled restart job, restart counter is at 1.
```
v2rayNG 1.8.2 ( Xray 1.8.0 )
```console

04-09 12:27:12.954 I/GoLog   (20265): loading core config
04-09 12:27:12.954 I/GoLog   (20265): Preparing Domain: SERVER_IP:80
04-09 12:27:12.954 I/GoLog   (20265): Prepare Result:
04-09 12:27:12.954 I/GoLog   (20265):  Domain: SERVER_IP
04-09 12:27:12.954 I/GoLog   (20265):  Port: 80
04-09 12:27:12.954 I/GoLog   (20265):  IPs: [SERVER_IP]
04-09 12:27:12.956 I/GoLog   (20265): new core
04-09 12:27:12.957 I/GoLog   (20265): start core
04-09 12:27:12.959 I/GoLog   (20265): [Warning] core: Xray 1.8.0 started
04-09 12:27:12.998 D/com.v2ray.ang(20265): [/data/app/~~Avz4viCy4TNMXS2ennGa9A==/com.v2ray.ang-Owfgr4k5gvmR2FkJpZo_Tw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
04-09 12:27:13.001 D/com.v2ray.ang(20265): Process[pid=21662, hasExited=false]
04-09 12:27:13.001 D/com.v2ray.ang(20265): /data/user/0/com.v2ray.ang/files/sock_path
04-09 12:27:13.001 D/com.v2ray.ang(20265): libtun2socks.so check
04-09 12:27:13.007 I/tun2socks(21662): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
04-09 12:27:13.051 D/com.v2ray.ang(20265): sendFd tries: 0
04-09 12:27:13.053 I/tun2socks(21662): NOTICE(tun2socks): entering event loop
04-09 12:27:13.083 I/GoLog   (20265): udp:127.0.0.1:48650 accepted udp:185.192.248.20:443 [socks >> proxy]
04-09 12:27:13.083 I/GoLog   (20265): udp:127.0.0.1:44931 accepted udp:142.250.184.238:443 [socks >> proxy]
04-09 12:27:13.083 I/GoLog   (20265): udp:127.0.0.1:37029 accepted udp:185.192.249.14:443 [socks >> proxy]
04-09 12:27:13.083 I/GoLog   (20265): udp:127.0.0.1:46767 accepted udp:185.192.251.204:443 [socks >> proxy]
04-09 12:27:13.106 I/GoLog   (20265): udp:127.0.0.1:46598 accepted udp:1.1.1.1:53 [socks -> proxy]
04-09 12:27:13.106 I/GoLog   (20265): udp:127.0.0.1:44547 accepted udp:1.1.1.1:53 [socks -> proxy]
04-09 12:27:13.120 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 110 Err: connection refused
04-09 12:27:13.123 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.123 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 98 Err: connection refused
04-09 12:27:13.123 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 112 Err: connection refused
04-09 12:27:13.142 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 108 Err: connection refused
04-09 12:27:13.142 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 111 Err: connection refused
04-09 12:27:13.159 I/GoLog   (20265): udp:127.0.0.1:41332 accepted udp:1.1.1.1:53 [socks -> proxy]
04-09 12:27:13.159 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 98 Err: connection refused
04-09 12:27:13.159 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 109 Err: connection refused
04-09 12:27:13.160 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 110 Err: connection refused
04-09 12:27:13.160 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 113 Err: connection refused
04-09 12:27:13.178 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.179 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 108 Err: connection refused
04-09 12:27:13.195 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 111 Err: connection refused
04-09 12:27:13.233 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 98 Err: connection refused
04-09 12:27:13.355 I/GoLog   (20265): tcp:127.0.0.1:41282 accepted tcp:140.82.114.26:443 [socks >> proxy]
04-09 12:27:13.394 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.398 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 108 Err: connection refused
04-09 12:27:13.399 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 111 Err: connection refused
04-09 12:27:13.400 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 112 Err: connection refused
04-09 12:27:13.400 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 109 Err: connection refused
04-09 12:27:13.418 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 113 Err: connection refused
04-09 12:27:13.419 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 110 Err: connection refused
04-09 12:27:13.433 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.473 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.575 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.616 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.673 I/GoLog   (20265): fdConn unix.Connect err, Close Fd: 106 Err: connection refused
04-09 12:27:13.839 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.842 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.842 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.842 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.856 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.857 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.858 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.916 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.947 I/GoLog   (20265): udp:127.0.0.1:42275 accepted udp:1.1.1.1:53 [socks -> proxy]
04-09 12:27:13.951 I/GoLog   (20265): udp:127.0.0.1:44580 accepted udp:1.1.1.1:53 [socks -> proxy]
04-09 12:27:13.986 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:13.990 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:14.114 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:14.130 I/GoLog   (20265): tcp:127.0.0.1:41336 accepted tcp:176.197.31.43:8000 [socks >> proxy]
04-09 12:27:14.166 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:14.176 I/GoLog   (20265): tcp:127.0.0.1:41340 accepted tcp:176.197.31.43:443 [socks >> proxy]
04-09 12:27:14.212 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:14.223 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:14.366 D/com.v2ray.ang(20265): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": io: read/write on closed pipe
04-09 12:27:14.718 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:15.269 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:15.479 I/GoLog   (20265): udp:127.0.0.1:38043 accepted udp:1.1.1.1:53 [socks -> proxy]
04-09 12:27:15.517 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:15.721 I/GoLog   (20265): tcp:127.0.0.1:41360 accepted tcp:142.250.185.78:443 [socks >> proxy]
04-09 12:27:15.729 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:15.759 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:16.502 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:17.071 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:18.294 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:18.963 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:19.141 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:19.593 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:19.911 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:20.236 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:20.480 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:20.671 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:20.919 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:21.375 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:21.892 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:22.144 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:22.457 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:22.602 D/com.v2ray.ang(20265): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": io: read/write on closed pipe
04-09 12:27:22.702 I/GoLog   (20265): Using Prepared: SERVER_IP
04-09 12:27:24.849 D/com.v2ray.ang(20265): tun2socks destroy
04-09 12:27:24.849 I/tun2socks(21662): NOTICE(tun2socks): termination requested
04-09 12:27:24.849 I/tun2socks(21662): NOTICE(tun2socks): tearing down
04-09 12:27:24.850 I/tun2socks(21662): NOTICE(tun2socks): Free TCP connections
04-09 12:27:24.850 I/tun2socks(21662): NOTICE(tun2socks): exiting
04-09 12:27:24.855 D/com.v2ray.ang(20265): libtun2socks.so exited
```

</details>

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/fd65bc08c865bd8b1462949edcfa8e28ece12dbd

**Comment by Hryniuk1** [comment]
> Try [fd65bc0](https://github.com/SagerNet/sing-box/commit/fd65bc08c865bd8b1462949edcfa8e28ece12dbd)

Seems now working without service crashing.
But now I sometimes get another connection errors with same configurations.
```console
апр 09 13:08:04 instance-20230331-1942 sing-box[885]: 2023/04/09 13:08:04 http: superfluous response.WriteHeader call from github.com/sagernet/sing-box/transport/v2raywebsocket.(*Server).fallbackRequest (server.go:119)
апр 09 13:08:04 instance-20230331-1942 sing-box[885]: ERROR[0092] inbound/vmess[vmess-80-in]: process connection from 172.71.234.34:51298: upgrade websocket connection: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header | fallback connection
```
Full log: 
[log1.txt](https://github.com/SagerNet/sing-box/files/11185207/log1.txt)

**Comment by nekohasekai** [comment]
https://github.com/SagerNet/sing-box/commit/aa667a1fa70403233b0914178074394d32e15dab

**Comment by Hryniuk1** [comment]
> [aa667a1](https://github.com/SagerNet/sing-box/commit/aa667a1fa70403233b0914178074394d32e15dab)

Seems this fixed too, no this error anymore, but.
Sometimes when do check connection multiple times in v2rayng, I'm getting "Fail to detect internet connection: i/o: read-write on closed pipe". Now server doesn't show any errors, only v2rayng shows something.
[server_log.txt](https://github.com/SagerNet/sing-box/files/11185495/server_log.txt)
[V2rayng.txt](https://github.com/SagerNet/sing-box/files/11185496/V2rayng.txt)
It's worth noting that Nekobox, which is based on the sing-box core and not xray, passes this multiple connection check without errors.  Is this not sing-box but v2rayng (xray) issue?
