### ISSUE TITLE
Panic in github.com/sagernet/sing/common/cache

### ISSUE THREAD

**Issue by JimLee1996** [SagerNet/sing-box#570]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

panic: runtime error: invalid memory address or nil pointer dereference

### Version of sing-box

<details>

```console
$ sing-box version
# Paste output here
sing-box version 1.3-beta9-a185cd3e

Environment: go1.20.3 linux/amd64
Tags: with_utls,with_reality_server,with_gvisor,with_wireguard,with_clash_api
Revision: a185cd3e4c3cf1948ce3fbeb0af276cc7033bbd8
CGO: disabled
```

</details>

### Server and client configuration file

<details>

```console
# paste json here
```

</details>

### Server and client log file

<details>

```console
Apr 26 17:08:46 ICL sing[62014]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 26 17:08:46 ICL sing[62014]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b0501]
Apr 26 17:08:46 ICL sing[62014]: goroutine 395 [running]:
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing/common/cache.(*LruCache[...]).Delete(0x11c9ca0, {{0xc000127000, 0xd}, 0x1, 0x1})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing@v0.2.5-0.20230425211221-a23ffbaeb5b9/common/cache/lrucache.go:252 +0x41
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-dns.(*Client).loadResponse(0xc000344030, {{0xc000127000?, 0xe4d6c0?}, 0x0?, 0x0?}, {0x11ba0d8?, 0xc000315320?})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-dns@v0.1.5-0.20230425204915-8734bfe33307/client.go:497 +0x3dd
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-dns.(*Client).questionCache(0xc000127000?, {{0xc000127000?, 0x0?}, 0x3486?, 0x45?}, {0x11ba0d8?, 0xc000315320?})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-dns@v0.1.5-0.20230425204915-8734bfe33307/client.go:457 +0x28
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-dns.(*Client).lookupToExchange(0xc000344030, {0x11b72c8, 0xc0019d62d0}, {0x11ba0d8, 0xc000315320}, {0xc000127000, 0xd}, 0x1, 0x12?)
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-dns@v0.1.5-0.20230425204915-8734bfe33307/client.go:438 +0x10a
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-dns.(*Client).Lookup(0xc000344030, {0x11b72c8, 0xc0019d62d0}, {0x11ba0d8?, 0xc000315320}, {0xc000126ec0, 0xc}, 0x3)
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-dns@v0.1.5-0.20230425204915-8734bfe33307/client.go:195 +0xd1b
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-box/route.(*Router).Lookup(0xc000346000, {0x11b7300, 0xc0019d62a0}, {0xc000126ec0, 0xc}, 0x3)
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/route/router_dns.go:128 +0x225
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-box/route.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0xc0000d38e8, 0x5}, {0x102af19, 0x5}, 0x0, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/route/router.go:684 +0x13c5
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-box/inbound.(*myInboundAdapter).newUserConnection(_, {_, _}, {_, _}, {{0xc0000d38e8, 0x5}, {0x102af19, 0x5}, 0x0, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/inbound/http.go:97 +0x356
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-box/adapter.(*myUpstreamHandlerWrapper).NewConnection(0xc001266540, {0x11b7300, 0xc0012a4c00}, {0x11c0098, 0xc001284660}, {{0x102b8b3, 0x6}, {{{0x0, 0xffffac10100b}, 0xc00012e018}, ...}, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/adapter/upstream.go:48 +0x365
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing/protocol/socks.HandleConnection0({0x11b7300, 0xc0012a4c00}, {0x11c0098?, 0xc001284660}, 0x40?, {0x0, 0x0}, {0x7f533e6acb98?, 0xc001266540}, {{0x102b8b3, ...}, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing@v0.2.5-0.20230425211221-a23ffbaeb5b9/protocol/socks/handshake.go:190 +0x12fe
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing/protocol/socks.HandleConnection({0x11b7300, 0xc0012a4c00}, {0x11c0098?, 0xc001284660?}, {0x0, 0x0}, {0x7f533e6acb98, 0xc001266540}, {{0x0, 0x0}, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing@v0.2.5-0.20230425211221-a23ffbaeb5b9/protocol/socks/handshake.go:101 +0x11a
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-box/inbound.(*Socks).NewConnection(_, {_, _}, {_, _}, {{0xc0000d38e8, 0x5}, {0x102af19, 0x5}, 0x0, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/inbound/socks.go:45 +0x373
Apr 26 17:08:46 ICL sing[62014]: github.com/sagernet/sing-box/inbound.(*myInboundAdapter).injectTCP(_, {_, _}, {{0xc0000d38e8, 0x5}, {0x102af19, 0x5}, 0x0, {0x0, 0x0}, ...})
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/inbound/default_tcp.go:62 +0x203
Apr 26 17:08:46 ICL sing[62014]: created by github.com/sagernet/sing-box/inbound.(*myInboundAdapter).loopTCPIn
Apr 26 17:08:46 ICL sing[62014]: 	github.com/sagernet/sing-box/inbound/default_tcp.go:54 +0x34c
```

</details>

**Comment by JimLee1996** [comment]
https://github.com/SagerNet/sing-dns/blob/dev/client.go#L497
