### ISSUE TITLE
panic: sing-dns if dns server detour to urltest/selector

### ISSUE THREAD

**Issue by malikshi** [SagerNet/sing-box#581]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

on recent commit, sing-box got panic error in syslog when i set detour to urltest/selector, no error if i set to individual node.

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version d3b41df

Environment: go1.20.3 linux/arm64
Tags: with_clash_api,with_grpc,with_wireguard,with_utls,with_gvisor,with_quic,with_dhcp,with_ech,with_reality_server,with_v2ray_api
CGO: enabled
```

</details>

### Server and client configuration file

<details>

```console
{
  "log": {
    "level": "trace",
    "output": "/var/log/box.log",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "remote-dns",
        "address": "1.1.1.1",
        "strategy": "ipv4_only",
        "detour": "Best Latency"
      },
      {
        "tag": "direct-dns",
        "address": "dhcp://wan",
        "strategy": "ipv4_only",
        "detour": "direct"
      },
      {
        "tag": "wlan0-dns",
        "address": "https://1.0.0.1/dns-query",
        "strategy": "prefer_ipv4",
        "detour": "wlan0"
      },
      {
        "tag": "dns-block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "disable_cache": true,
        "domain_suffix": [
          ".arpa.",
          ".arpa"
        ],
        "server": "dns-block"
      },
      {
        "geosite": "rule-malicious",
        "server": "dns-block",
        "rewrite_ttl": 10
      },
      {
        "protocol": "quic",
        "server": "dns-block",
        "rewrite_ttl": 10
      },
      {
        "outbound": "direct",
        "clash_mode": "direct",
        "server": "direct-dns",
        "disable_cache": false,
        "rewrite_ttl": 20
      },
      {
        "outbound": "wlan0",
        "server": "wlan0-dns",
        "disable_cache": false,
        "rewrite_ttl": 20
      },
      {
        "outbound": "any",
        "server": "remote-dns",
        "disable_cache": false,
        "rewrite_ttl": 20
      }
    ],
    "final": "remote-dns",
    "strategy": "ipv4_only",
    "disable_cache": false,
    "disable_expire": false,
    "reverse_mapping": false,
    "fakeip": {
      "enabled": false,
      "inet4_range": "198.18.0.0/15",
      "inet6_range": "fc00::/18"
    }
  },
  "ntp": {
    "enabled": false,
    "interval": "30m0s",
    "server": "time.bmkg.go.id",
    "server_port": 123,
    "detour": "Best Latency"
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "listen_port": 53,
      "override_address": "1.1.1.1",
      "override_port": 53,
      "tag": "dns-in",
      "type": "direct"
    },
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "vpn0",
      "mtu": 9000,
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": true,
      "udp_timeout": 300,
      "stack": "system",
      "sniff": true
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "Internet",
      "outbounds": [
        "Best Latency",
        "wlan0",
        "BGN Trojan A",
        "BGN Trojan B",
        "BGN Trojan C"
      ]
    },
    {
      "type": "urltest",
      "tag": "Best Latency",
      "outbounds": [
        "BGN Trojan WS",
        "BGN Trojan B",
        "BGN Trojan C"
      ],
      "url": "https://www.gstatic.com/generate_204",
      "interval": "1m0s"
    },
    {
      "type": "selector",
      "tag": "Lock Region ID",
      "outbounds": [
        "wlan0",
        "BGN Trojan WS",
        "BGN Trojan B",
        "BGN Trojan C"
      ]
    },
    {
      "type": "selector",
      "tag": "WhatsApp",
      "outbounds": [
        "direct",
        "wlan0",
        "Internet",
        "Best Latency",
        "Lock Region ID"
      ]
    },
    {
      "type": "selector",
      "tag": "GAMESMAX",
      "outbounds": [
        "direct",
        "wlan0",
        "Internet",
        "Best Latency",
        "Lock Region ID"
      ]
    },
    {
      "type": "selector",
      "tag": "Route Port Game",
      "outbounds": [
        "Best Latency",
        "Internet",
        "Lock Region ID",
        "direct",
        "wlan0"
      ]
    },
    {
      "type": "selector",
      "tag": "Option ADs",
      "outbounds": [
        "block",
        "Internet"
      ]
    },
    {
      "type": "selector",
      "tag": "Option P0rn",
      "outbounds": [
        "block",
        "Internet"
      ]
    },
    {
      "type": "trojan",
      "tag": "BGN Trojan A",
      "server": "IP",
      "server_port": 443,
      "password": "pass",
      "tls": {
        "enabled": true,
        "server_name": "open.spotify.com",
        "insecure": true,
        "utls": {
          "enabled": false,
          "fingerprint": "chrome"
        }
      },
      "multiplex": {
        "enabled": false,
        "protocol": "yamux",
        "max_connections": 36,
        "min_streams": 4,
        "padding": false
      },
      "transport": {
        "type": "ws",
        "path": "/browse/featured",
        "headers": {
          "Host": "open.spotify.com"
        }
      }
    },
    {
      "type": "trojan",
      "tag": "BGN Trojan B",
      "server": "IP",
      "server_port": 443,
      "password": "pass",
      "tls": {
        "enabled": true,
        "server_name": "open.spotify.com",
        "insecure": true,
        "utls": {
          "enabled": false,
          "fingerprint": "chrome"
        }
      },
      "multiplex": {
        "enabled": false,
        "protocol": "yamux",
        "max_connections": 36,
        "min_streams": 4,
        "padding": false
      },
      "transport": {
        "type": "ws",
        "path": "/browse/featured",
        "headers": {
          "Host": "open.spotify.com"
        }
      }
    },
    {
      "type": "trojan",
      "tag": "BGN Trojan C",
      "server": "IP",
      "server_port": 443,
      "password": "pass",
      "tls": {
        "enabled": true,
        "server_name": "open.spotify.com",
        "insecure": true,
        "utls": {
          "enabled": false,
          "fingerprint": "chrome"
        }
      },
      "multiplex": {
        "enabled": false,
        "protocol": "yamux",
        "max_connections": 36,
        "min_streams": 4,
        "padding": false
      },
      "transport": {
        "type": "ws",
        "path": "/browse/featured",
        "headers": {
          "Host": "open.spotify.com"
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "direct",
      "tag": "wlan0",
      "bind_interface": "wlan0"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "geoip": {
      "path": "/etc/sing-box/geoip.db",
      "download_url": "https://github.com/malikshi/sing-box-geo/releases/latest/download/geoip.db",
      "download_detour": "Internet"
    },
    "geosite": {
      "path": "/etc/sing-box/geosite.db",
      "download_url": "https://github.com/malikshi/sing-box-geo/releases/latest/download/geosite.db",
      "download_detour": "Internet"
    },
    "rules": [
      {
        "port": 53,
        "outbound": "dns-out"
      },
      {
        "inbound": [
          "dns-in"
        ],
        "outbound": "dns-out"
      },
      {
        "network": "udp",
        "port": 443,
        "outbound": "block"
      },
      {
        "port": [
          22,
          9090
        ],
        "outbound": "Lock Region ID"
      },
      {
        "domain_suffix": "googlesyndication.com",
        "outbound": "Internet"
      },
      {
        "geosite": [
          "rule-ads",
          "oisd-full"
        ],
        "outbound": "Option ADs"
      },
      {
        "geosite": [
          "oisd-nsfw",
          "category-porn"
        ],
        "outbound": "Option P0rn"
      },
      {
        "geoip": "facebook",
        "port": [
          3478,
          4244,
          5222,
          5223,
          5242,
          45395,
          50318,
          59234
        ],
        "outbound": "WhatsApp"
      },
      {
        "port": 3478,
        "outbound": "Internet"
      },
      {
        "geosite": "rule-indo",
        "outbound": "Lock Region ID"
      },
      {
        "network": "udp",
        "port": [
          2702,
          3702,
          8443,
          9120,
          9992,
          10003,
          6006,
          6008,
          6674,
          7889,
          8008,
          8130,
          8443,
          9008,
          9120,
          10100,
          12008,
          13008,
          8011,
          9030,
          10491,
          10612,
          12235,
          13004,
          13748,
          17000,
          17500,
          10039,
          10096,
          11455,
          13894,
          13972
        ],
        "outbound": "GAMESMAX"
      },
      {
        "network": "udp",
        "port_range": [
          "4001:4009",
          "5000:5221",
          "5224:5241",
          "5243:5287",
          "5289:5352",
          "5354:5509",
          "5517:5529",
          "5551:5559",
          "5601:5700",
          "9000:9010",
          "30000:30300",
          "7006:7008",
          "8001:8012",
          "10000:10015",
          "11000:11019",
          "10101:10201",
          "10080:10110",
          "17000:18000"
        ],
        "outbound": "GAMESMAX"
      },
      {
        "network": "tcp",
        "port": [
          5517,
          8443,
          9443,
          10003,
          6006,
          6008,
          6674,
          7889,
          9006,
          9137,
          12006,
          12008,
          13006,
          15006,
          20561,
          39003,
          39006,
          39698,
          39779,
          39800,
          10012,
          14000,
          15692,
          17000,
          17500,
          18081,
          20371,
          8013,
          8085,
          18082,
          20000,
          50000,
          65010,
          65050,
          8013,
          18082,
          20166,
          31003,
          33445,
          50000,
          42472,
          14422,
          16999,
          8013,
          8888,
          30031,
          14009,
          40005,
          9339,
          2099,
          8088,
          5692,
          8085,
          8500,
          10000,
          10082,
          20000,
          25000,
          29134,
          31003
        ],
        "outbound": "Route Port Game"
      },
      {
        "network": "tcp",
        "port_range": [
          "5000:5221",
          "5224:5227",
          "5229:5241",
          "5243:5287",
          "5289:5352",
          "5354:5509",
          "5520:5529",
          "5551:5559",
          "5601:5700",
          "9000:9010",
          "30000:30300",
          "7006:7008",
          "8001:8012",
          "10000:10012",
          "11000:11019",
          "8085:8088",
          "10000:10019",
          "20000:20002",
          "10000:10001",
          "20000:20001",
          "9330:9340",
          "2080:2099",
          "9100:9200",
          "8230:8250",
          "8110:8120",
          "27000:28998",
          "7770:7790",
          "44590:44610",
          "10500:10515",
          "27015:27030",
          "27036:27037",
          "39190:39200",
          "49001:49190",
          "8393:8400"
        ],
        "outbound": "Route Port Game"
      },
      {
        "network": "udp",
        "port": [
          2702,
          3702,
          8443,
          9120,
          9992,
          10003,
          6006,
          6008,
          6674,
          7889,
          8008,
          8130,
          8443,
          9008,
          9120,
          10100,
          12008,
          13008,
          8700,
          10013,
          10019,
          10039,
          10096,
          10491,
          10612,
          11455,
          12235,
          13748,
          13894,
          13972,
          17000,
          17500,
          8700,
          9030,
          8011,
          9030,
          10491,
          10612,
          12235,
          13004,
          13748,
          17000,
          17500,
          10039,
          10096,
          11455,
          13894,
          13972,
          42472,
          5100,
          39000,
          4380,
          27036,
          14422,
          16999,
          8013,
          8888,
          8000,
          30104,
          14009,
          40005,
          8088,
          5010,
          6650,
          8011,
          8700,
          20000,
          25000,
          29134,
          30000
        ],
        "outbound": "Route Port Game"
      },
      {
        "network": "udp",
        "port_range": [
          "4001:4009",
          "5000:5221",
          "5224:5241",
          "5243:5287",
          "5289:5352",
          "5354:5509",
          "5517:5529",
          "5551:5559",
          "5601:5700",
          "9000:9010",
          "30000:30300",
          "7006:7008",
          "8001:8012",
          "10000:10015",
          "11000:11019",
          "7086:7995",
          "8011:8013",
          "9030:9031",
          "20000:20002",
          "12070:12460",
          "41182:41192",
          "7500:7995",
          "10010:10019",
          "20000:20001",
          "10101:10201",
          "10080:10110",
          "17000:18000",
          "5055:5058",
          "22101:22102",
          "9330:9340",
          "27000:28998",
          "16300:16350",
          "40000:40010",
          "60970:60980",
          "27000:27031",
          "40000:40010",
          "7000:8000",
          "8180:8181",
          "27016:27024",
          "54000:54012"
        ],
        "outbound": "Route Port Game"
      },
      {
        "geoip": "id",
        "port": [
          21,
          22,
          23,
          80,
          81,
          123,
          143,
          182,
          183,
          194,
          443,
          465,
          587,
          853,
          993,
          995,
          998,
          2052,
          2053,
          2082,
          2083,
          2086,
          2095,
          2096,
          5222,
          5228,
          5229,
          5230,
          8000,
          8080,
          8081,
          8088,
          8443,
          8880,
          8883,
          8888,
          8889
        ],
        "outbound": "Lock Region ID"
      },
      {
        "port": [
          21,
          22,
          23,
          80,
          81,
          123,
          143,
          182,
          183,
          194,
          443,
          465,
          587,
          853,
          993,
          995,
          998,
          2052,
          2053,
          2082,
          2083,
          2086,
          2095,
          2096,
          5222,
          5228,
          5229,
          5230,
          8000,
          8080,
          8081,
          8088,
          8443,
          8880,
          8883,
          8888,
          8889
        ],
        "outbound": "Internet"
      },
      {
        "port_range": [
          "1023:42068",
          "42070:65535"
        ],
        "outbound": "Route Port Game"
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block",
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
      }
    ],
    "final": "Internet",
    "auto_detect_interface": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui": "/etc/sing-box/yacd",
      "external_ui_download_url": "https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
      "external_ui_download_detour": "Best Latency",
      "secret": "password",
      "default_mode": "rule",
      "store_selected": true,
      "cache_file": "clash.db"
    }
  }
}

```

</details>

### Server and client log file

<details>
syslog 

```console
May  1 08:09:35 raspberrypi sing-box[14988]: panic: runtime error: invalid memory address or nil pointer dereference
May  1 08:09:35 raspberrypi sing-box[14988]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa6cee0]
May  1 08:09:35 raspberrypi sing-box[14988]: goroutine 108 [running]:
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-box/outbound.(*URLTest).DialContext(0x400026f340, {0x10b6fd8, 0x400048ce60}, {0xec04fd, 0x3}, {{{0x0, 0xffff01010101}, 0x40000be018}, 0x35, {0x0, ...}})
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-box@v1.2.7-0.20230430090056-d3b41dfc0128/outbound/urltest.go:101 +0x80
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-box/outbound.(*Selector).DialContext(0x4000375860?, {0x10b6fd8?, 0x400048ce60?}, {0xec04fd?, 0x4000223748?}, {{{0x0, 0xffff01010101}, 0x40000be018}, 0x35, {0x0, ...}})
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-box@v1.2.7-0.20230430090056-d3b41dfc0128/outbound/selector.go:115 +0x58
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-box/common/dialer.(*DetourDialer).DialContext(0x7f7d119288?, {0x10b6fd8, 0x400048ce60}, {0xec04fd, 0x3}, {{{0x0, 0xffff01010101}, 0x40000be018}, 0x35, {0x0, ...}})
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-box@v1.2.7-0.20230430090056-d3b41dfc0128/common/dialer/detour.go:47 +0x90
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-dns.(*UDPTransport).DialContext(0x10b6fd8?, {0x10b6fd8?, 0x400048ce60?}, {0x212?, 0x400187c8b8?})
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-dns@v0.1.5-0.20230426113254-25d948c44223/transport_udp.go:53 +0x74
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-dns.(*myTransportAdapter).open(0x40003dcc60, {0x10b6fd8, 0x40003758b0})
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-dns@v0.1.5-0.20230426113254-25d948c44223/transport_base.go:71 +0x184
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-dns.(*myTransportAdapter).exchange(0x40003dcc60, {0x10b7080, 0x4001855710}, 0x4000432630)
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-dns@v0.1.5-0.20230426113254-25d948c44223/transport_base.go:132 +0x54
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-dns.(*myTransportAdapter).Exchange(0xce46a0?, {0x10b7080, 0x4001855710}, 0x4000432630)
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-dns@v0.1.5-0.20230426113254-25d948c44223/transport_base.go:119 +0x7c
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-dns.(*Client).exchange(0x40003c0930, {0x10b7048, 0x40018556b0}, {0x10bb080, 0x40003dcc60}, 0x4000432630, 0x3)
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-dns@v0.1.5-0.20230426113254-25d948c44223/client.go:130 +0x67c
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-dns.(*Client).Exchange(0x10b7080?, {0x10b7048, 0x40018556b0}, {0x10bb080?, 0x40003dcc60?}, 0x0?, 0x18?)
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-dns@v0.1.5-0.20230426113254-25d948c44223/client.go:65 +0x30
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-box/route.(*Router).Exchange(0x40003f0000, {0x10b7080, 0x4001855680}, 0x4000432630)
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-box@v1.2.7-0.20230430090056-d3b41dfc0128/route/router_dns.go:97 +0x260
May  1 08:09:35 raspberrypi sing-box[14988]: github.com/sagernet/sing-box/outbound.(*DNS).newPacketConnection.func1.2()
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-box@v1.2.7-0.20230430090056-d3b41dfc0128/outbound/dns.go:230 +0x98
May  1 08:09:35 raspberrypi sing-box[14988]: created by github.com/sagernet/sing-box/outbound.(*DNS).newPacketConnection.func1
May  1 08:09:35 raspberrypi sing-box[14988]: #011github.com/sagernet/sing-box@v1.2.7-0.20230430090056-d3b41dfc0128/outbound/dns.go:229 +0xe0

```
sing-box log:
```console
+0700 2023-05-01 08:09:37 TRACE pre-start clash api
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[Internet]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/urltest[Best Latency]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[Lock Region ID]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[WhatsApp]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[GAMESMAX]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[Route Port Game]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[Option ADs]
+0700 2023-05-01 08:09:37 TRACE initializing outbound/selector[Option P0rn]
+0700 2023-05-01 08:09:37 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 INFO outbound/trojan[BGN Trojan gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 INFO outbound/trojan[BGN Trojan WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 INFO router: updated default interface wan, index 2
+0700 2023-05-01 08:09:37 INFO outbound/vmess[IKD Vmess WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 INFO router: loaded geoip database: 261 codes
+0700 2023-05-01 08:09:37 INFO outbound/vmess[IKD Vmess gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 INFO router: loaded geosite database: 1399 codes
+0700 2023-05-01 08:09:37 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 DEBUG outbound/urltest[Best Latency]: outbound BGN Trojan WS unavailable: Head "https://www.gstatic.com/generate_204": io: read/write on closed pipe
+0700 2023-05-01 08:09:37 DEBUG outbound/urltest[Best Latency]: outbound BGN Trojan gRPC unavailable: Head "https://www.gstatic.com/generate_204": io: read/write on closed pipe
+0700 2023-05-01 08:09:37 DEBUG outbound/urltest[Best Latency]: outbound IKD Vmess gRPC unavailable: Head "https://www.gstatic.com/generate_204": io: read/write on closed pipe
+0700 2023-05-01 08:09:37 DEBUG outbound/urltest[Best Latency]: outbound IKD Vmess WS unavailable: Head "https://www.gstatic.com/generate_204": io: read/write on closed pipe
+0700 2023-05-01 08:09:37 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:37 DEBUG outbound/urltest[Best Latency]: outbound DMD Vless gRPC available: 417ms
+0700 2023-05-01 08:09:37 DEBUG outbound/urltest[Best Latency]: outbound DMD Vless WS available: 546ms
+0700 2023-05-01 08:09:55 INFO dns/transport[direct-dns]: dhcp: query DNS servers on wan
+0700 2023-05-01 08:09:55 INFO dns/transport[direct-dns]: dhcp: updated DNS servers from wan: [10.0.8.1]
+0700 2023-05-01 08:09:55 TRACE starting clash api
+0700 2023-05-01 08:09:55 INFO clash-api: restful api listening at [::]:9090
+0700 2023-05-01 08:09:55 TRACE initializing inbound/direct[dns-in]
+0700 2023-05-01 08:09:55 INFO inbound/direct[dns-in]: tcp server started at 0.0.0.0:53
+0700 2023-05-01 08:09:55 INFO inbound/direct[dns-in]: udp server started at 0.0.0.0:53
+0700 2023-05-01 08:09:55 TRACE initializing inbound/tun[tun-in]
+0700 2023-05-01 08:09:55 TRACE inbound/tun[tun-in]: opening interface
+0700 2023-05-01 08:09:55 TRACE inbound/tun[tun-in]: creating stack
+0700 2023-05-01 08:09:55 TRACE inbound/tun[tun-in]: starting stack
+0700 2023-05-01 08:09:55 INFO inbound/tun[tun-in]: started at vpn0
+0700 2023-05-01 08:09:55 INFO sing-box started (18.544s)
+0700 2023-05-01 08:09:55 INFO [2157080333 0ms] inbound/tun[tun-in]: inbound connection from 192.168.100.6:46152
+0700 2023-05-01 08:09:55 INFO [2157080333 0ms] inbound/tun[tun-in]: inbound connection to 91.108.56.130:443
+0700 2023-05-01 08:09:55 TRACE [2157080333 0ms] router: sniffed no protocol: unexpected EOF | tls: first record does not look like a TLS handshake | malformed HTTP request "\x88\xe8\xaa\x0fF\x94W\x17\xaf\xc8}\xd8O\x92~\xdf\xe4}\x1bX\x>
+0700 2023-05-01 08:09:55 DEBUG [2157080333 0ms] router: match[17] port=[21 22 23 80 81 123 143 182 183 194 443 465 587 853 993 995 998 2052 2053 2082 2083 2086 2095 2096 5222 5228 5229 5230 8000 8080 8081 8088 8443 8880 8883 8888 8889>
+0700 2023-05-01 08:09:55 INFO [2157080333 1ms] outbound/vless[DMD Vless gRPC]: outbound connection to 91.108.56.130:443
+0700 2023-05-01 08:09:55 INFO [2157080333 1ms] outbound/vless[DMD Vless gRPC]: outbound connection to 91.108.56.130:443
+0700 2023-05-01 08:09:55 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:55 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:55 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:55 INFO outbound/trojan[BGN Trojan WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:55 INFO outbound/vmess[IKD Vmess gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:55 INFO outbound/vmess[IKD Vmess WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:55 INFO outbound/trojan[BGN Trojan gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:09:56 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:09:56 DEBUG outbound/urltest[Best Latency]: outbound DMD Vless gRPC available: 217ms
+0700 2023-05-01 08:09:56 DEBUG outbound/urltest[Best Latency]: outbound BGN Trojan gRPC available: 234ms
+0700 2023-05-01 08:09:56 DEBUG outbound/urltest[Best Latency]: outbound IKD Vmess gRPC available: 245ms
+0700 2023-05-01 08:09:56 DEBUG outbound/urltest[Best Latency]: outbound DMD Vless WS available: 314ms
+0700 2023-05-01 08:09:56 DEBUG outbound/urltest[Best Latency]: outbound BGN Trojan WS available: 337ms
+0700 2023-05-01 08:09:56 DEBUG outbound/urltest[Best Latency]: outbound IKD Vmess WS available: 423ms
+0700 2023-05-01 08:09:57 INFO [2231629109 0ms] inbound/direct[dns-in]: inbound packet connection from 192.168.100.1:20896
+0700 2023-05-01 08:09:57 DEBUG [2231629109 0ms] router: match[0] port=53 => dns-out
+0700 2023-05-01 08:09:57 DEBUG dns: exchange mtalk.google.com. IN A
+0700 2023-05-01 08:21:02 TRACE pre-start clash api
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[Internet]
+0700 2023-05-01 08:21:02 TRACE initializing outbound/urltest[Best Latency]
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[Lock Region ID]
+0700 2023-05-01 08:21:02 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:21:02 INFO outbound/trojan[BGN Trojan WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:21:02 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[WhatsApp]
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[GAMESMAX]
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[Route Port Game]
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[Option ADs]
+0700 2023-05-01 08:21:02 TRACE initializing outbound/selector[Option P0rn]
+0700 2023-05-01 08:21:02 INFO outbound/trojan[BGN Trojan gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 08:21:02 INFO outbound/vmess[IKD Vmess gRPC]: outbound multiplex connection to www.gstatic.com:443


```

</details>

**Comment by malikshi** [comment]
it's seem the error relate to cached like in #575 ?
i didn't see any panic again. i want to ask about h2mux, node can't connect/online if using h2mux, i am using trojan,vmess both websocket and grpc failed 

```console
+0700 2023-05-01 14:35:46 TRACE pre-start clash api
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[Internet]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/urltest[Best Latency]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[Lock Region ID]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[WhatsApp]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[GAMESMAX]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[Route Port Game]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[Option ADs]
+0700 2023-05-01 14:35:46 TRACE initializing outbound/selector[Option P0rn]
+0700 2023-05-01 14:35:46 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 INFO outbound/trojan[BGN Trojan WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 INFO outbound/trojan[BGN Trojan gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 INFO router: updated default interface wan, index 2
+0700 2023-05-01 14:35:46 INFO router: loaded geoip database: 261 codes
+0700 2023-05-01 14:35:46 INFO outbound/vmess[IKD Vmess gRPC]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 INFO outbound/vmess[IKD Vmess WS]: outbound multiplex connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 INFO router: loaded geosite database: 1399 codes
+0700 2023-05-01 14:35:46 INFO outbound/vless[DMD Vless gRPC]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 DEBUG outbound/urltest[Best Latency]: outbound BGN Trojan WS unavailable: Head "https://www.gstatic.com/generate_204": io: read/write on closed pipe
+0700 2023-05-01 14:35:46 DEBUG outbound/urltest[Best Latency]: outbound IKD Vmess gRPC unavailable: Head "https://www.gstatic.com/generate_204": http2: client connection force closed via ClientConn.Close
+0700 2023-05-01 14:35:46 DEBUG outbound/urltest[Best Latency]: outbound IKD Vmess WS unavailable: Head "https://www.gstatic.com/generate_204": io: read/write on closed pipe
+0700 2023-05-01 14:35:46 DEBUG outbound/urltest[Best Latency]: outbound BGN Trojan gRPC unavailable: Head "https://www.gstatic.com/generate_204": http2: client connection force closed via ClientConn.Close
+0700 2023-05-01 14:35:46 INFO outbound/vless[DMD Vless WS]: outbound connection to www.gstatic.com:443
+0700 2023-05-01 14:35:46 DEBUG outbound/urltest[Best Latency]: outbound DMD Vless gRPC available: 430ms
+0700 2023-05-01 14:35:46 DEBUG outbound/urltest[Best Latency]: outbound DMD Vless WS available: 518ms
```
