### ISSUE TITLE
panic: close of closed channel | panic: Header called after Handler finished

### ISSUE THREAD

**Issue by hibobmaster** [SagerNet/sing-box#608]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

panic: close of closed channel

goroutine 350145 [running]:
github.com/sagernet/sing-mux.(*h2MuxConnWrapper).Close(0xc0004e3f50)
        github.com/sagernet/sing-mux@v0.0.0-20230425130511-b0a6ffd8406f/h2mux.go:149 +0x37
github.com/sagernet/sing/common.Close({0xc000499ea8?, 0x1, 0xf99140?})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/cond.go:326 +0x8e
github.com/sagernet/sing/common/bufio.CopyConnContextList.func4({0x0?, 0x0?})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/copy.go:240 +0xe2
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/task/task.go:68 +0x84
created by github.com/sagernet/sing/common/task.(*Group).RunContextList
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/task/task.go:67 +0x17e

---

panic: Header called after Handler finished

goroutine 57329 [running]:
golang.org/x/net/http2.(*responseWriter).FlushError(0x7fc7e70f2108?)
        golang.org/x/net@v0.9.0/http2/server.go:2770 +0x119
golang.org/x/net/http2.(*responseWriter).Flush(0xc000352420?)
        golang.org/x/net@v0.9.0/http2/server.go:2764 +0x19
github.com/sagernet/sing-mux.(*h2MuxConnWrapper).Write(0xc0004bdf50, {0xc00014e400, 0x59, 0x80})
        github.com/sagernet/sing-mux@v0.0.0-20230425130511-b0a6ffd8406f/h2mux.go:127 +0x87
github.com/sagernet/sing-mux.(*wrapStream).Write(0x57?, {0xc00014e400?, 0xc000ac9a28?, 0x7384c9?})
        github.com/sagernet/sing-mux@v0.0.0-20230425130511-b0a6ffd8406f/error.go:21 +0x26
github.com/sagernet/sing/common/bufio.(*ExtendedWriterWrapper).WriteBuffer(0xc0003523c0?, 0xc00004c601?)
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/conn.go:117 +0x93
github.com/sagernet/sing/common/bufio.(*ExtendedConnWrapper).WriteBuffer(0x1289b80?, 0xc00050d1a0?)
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/conn.go:156 +0x22
github.com/sagernet/sing-mux.(*serverConn).HandshakeFailure(0xc000959218, {0x128b2a0?, 0xc0001065f0?})
        github.com/sagernet/sing-mux@v0.0.0-20230425130511-b0a6ffd8406f/server_conn.go:32 +0x302
github.com/sagernet/sing/common/network.HandshakeFailure({0x10933a0?, 0xc000470f00?}, {0x128b2a0, 0xc0001065f0})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/network/handshake.go:14 +0x5c
github.com/sagernet/sing/common/bufio.copyWaitWithPool({0x7fc7bfa75ee8?, 0xc000470f00}, {0x7fc7bfa76058?, 0xc000959218}, {0x1289ce0, 0xc00032e8a0}, {0x0, 0x0, 0x73ca74?}, {0x0, ...})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/copy_direct_posix.go:51 +0x372
github.com/sagernet/sing/common/bufio.CopyExtended({0x7fc7bfa75ee8, 0xc000470f00}, {0x7fc7bfa76058?, 0xc000959218}, {0x128fe88?, 0xc0007fe470}, {0x0, 0x0, 0x0}, {0x0, ...})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/copy.go:69 +0x295
github.com/sagernet/sing/common/bufio.Copy({0x7fc7bfa75ee8, 0xc000470f00}, {0x128b2e0?, 0xc000122850?})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/copy.go:55 +0x5b3
github.com/sagernet/sing/common/bufio.CopyConnContextList.func4({0x0?, 0x0?})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/copy.go:240 +0xc9
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/task/task.go:68 +0x84
created by github.com/sagernet/sing/common/task.(*Group).RunContextList
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/task/task.go:67 +0x17e

### Version of sing-box

<details>

```console
sing-box version unknown

Environment: go1.20.4 linux/amd64
Tags: with_quic,with_wireguard,with_utls,with_gvisor,with_reality_server
Revision: e02317a34851617c0eb2cb6634b4b62901aa04dc
CGO: disabled
```
</details>

### Server and client configuration file

<details>

server:
```json
{
    "log": {
      "disabled": false,
      "level": "info",
      "timestamp": true
    },
    "dns": {
      "servers": [
        {
          "tag": "google",
          "address": "tls://8.8.8.8",
          "detour": "direct-out"
        },
        {
          "tag": "cloudflare",
          "address": "https://1.1.1.1/dns-query",
          "detour": "direct-out"
        }
      ]
    },
    "inbounds": [
      {
        "type": "shadowtls",
        "listen": "::",
        "listen_port": 8387,
        "version": 3,
        "users": [
          {
            "name": "xxxxxx",
            "password": "xxxxxxxxxx"
          }
        ],
        "handshake": {
          "server": "p26-sign.bdxiguaimg.com",
          "server_port": 443
        },
        "strict_mode": true,
        "detour": "ss-in"
      },
      {
        "type": "shadowsocks",
        "tag": "ss-in",
        "listen": "127.0.0.1",
        "method": "2022-blake3-aes-128-gcm",
        "password": "xxxxxxxxxx"
      }
    ],
    "outbounds": [
      {
        "type": "direct",
        "tag": "direct-out"
      },
      {
        "type": "block",
        "tag": "block"
      },
      {
        "type": "dns",
        "tag": "dns-out"
      },
      {
        "type": "wireguard",
        "tag": "wireguard-out",
        "server": "engage.cloudflareclient.com",
        "server_port": 2408,
        "system_interface": false,
        "interface_name": "wg0",
        "local_address": [
          "172.16.0.2/32",
          "2606:4700:110:87a6:98c1:cb78:3d90:e07c/128"
        ],
        "private_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
      }
    ],
    "route": {
      "geoip": {
        "path": "",
        "download_url": "https://github.com/1715173329/sing-geoip/releases/download/202211100127/geoip.db",
        "download_detour": "direct-out"
      },
      "rules": [
        {
          "protocol": "dns",
          "outbound": "dns-out"
        },
        {
          "geoip": [
            "cloudflare"
          ],
          "domain_keyword": [
            "openai"
          ],
          "domain": [
            "ai.com",
            "auth0.com",
            "sentry.io"
          ],
          "outbound": "wireguard-out"
        }
      ],
      "final": "direct-out"
    }
  }
```
client
```json
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8",
        "detour": "ca-out"
      },
      {
        "tag": "china",
        "address": "119.29.29.29",
        "detour": "direct"
      },
      {
        "tag": "router",
        "address": "192.168.0.1",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "domain": ["xxxxxxxxxxxxxxxxxxx"],
        "geosite": ["cn"],
        "server": "china"
      },
      {
        "domain": ["xxxxxxxxxxxxxxxxx"],
        "server": "router"
      }
    ],
    "final": "google",
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "sniff": true,
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "stack": "system"
    }
  ],
  "outbounds": [
    {
      "type": "shadowsocks",
      "tag": "ca-out",
      "method": "2022-blake3-aes-128-gcm",
      "password": "xxxxxxxxxxxxxxxxx",
      "detour": "shadowtls-out",
      "multiplex": {
        "enabled": true,
        "max_connections": 4,
        "min_streams": 4,
        "padding": true
      }
    },
    {
      "type": "shadowtls",
      "tag": "shadowtls-out",
      "server": "xxxxxxxxxxxxxx",
      "server_port": 8387,
      "version": 3,
      "password": "xxxxxxxxxxxxxxxxxx",
      "tls": {
        "enabled": true,
        "server_name": "p26-sign.bdxiguaimg.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "geoip": {
      "path": "",
      "download_detour": "ca-out"
    },
    "geosite": {
      "path": "",
      "download_detour": "ca-out"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geosite": ["cn"],
        "geoip": ["cn", "private"],
        "outbound": "direct"
      },
      {
        "process_name": ["tailscaled.exe", "tailscale.exe"],
        "outbound": "direct"
      },
      {
        "domain": ["xxxxxxxxxxxxxx"],
        "outbound": "direct"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
    "final": "ca-out",
    "auto_detect_interface": true
  }
}

```

</details>

### Server and client log file

<details>

server log
```console
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com CNAME p26-sign.bdxiguaimg.com. 600 IN CNAME p26-sign.bdxiguaimg.com.512
96c5e.c.cdnhwc1.com.
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com CNAME p26-sign.bdxiguaimg.com.51296c5e.c.cdnhwc1.com. 60 IN CNAME hcdnd
100.ipv6.c.cdnhwc1.com.
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com A hcdnd100.ipv6.c.cdnhwc1.com. 60 IN A 218.60.15.156
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com A hcdnd100.ipv6.c.cdnhwc1.com. 60 IN A 221.204.21.79
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com A hcdnd100.ipv6.c.cdnhwc1.com. 60 IN A 221.204.21.85
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com A hcdnd100.ipv6.c.cdnhwc1.com. 60 IN A 222.141.28.67
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com A hcdnd100.ipv6.c.cdnhwc1.com. 60 IN A 222.141.28.70
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com A hcdnd100.ipv6.c.cdnhwc1.com. 60 IN A 218.60.15.155
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com CNAME p26-sign.bdxiguaimg.com. 600 IN CNAME p26-sign.bdxiguaimg.com.512
96c5e.c.cdnhwc1.com.
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com CNAME p26-sign.bdxiguaimg.com.51296c5e.c.cdnhwc1.com. 60 IN CNAME hcdnd
100.ipv6.c.cdnhwc1.com.
+0000 2023-05-14 15:16:17 INFO dns: exchanged p26-sign.bdxiguaimg.com SOA cdnhwc1.com. 300 IN SOA ns1.hwclouds-dns.com. zhangxi\.zhang.huawei
.com. 1 7200 900 1209600 300
+0000 2023-05-14 15:16:17 INFO [2387713477 1.1s] inbound/shadowtls[0]: inbound connection to xxxxxxxxxxx:8387
+0000 2023-05-14 15:16:17 INFO [3111936184 0ms] inbound/shadowsocks[ss-in]: inbound connection to sp.mux.sing-box.arpa:444
+0000 2023-05-14 15:16:17 INFO [3111936184 0ms] router: inbound multiplex connection
+0000 2023-05-14 15:16:17 INFO [3111936184 0ms] router: inbound multiplex connection to 40.83.240.146:443
+0000 2023-05-14 15:16:17 INFO [3111936184 0ms] outbound/direct[direct-out]: outbound connection to 40.83.240.146:443
+0000 2023-05-14 15:16:46 INFO [3111936184 28.61s] router: inbound multiplex packet connection
+0000 2023-05-14 15:16:46 INFO [3111936184 28.61s] outbound/direct[direct-out]: outbound packet connection
+0000 2023-05-14 15:16:46 INFO [3111936184 28.61s] router: inbound multiplex packet connection
+0000 2023-05-14 15:16:46 INFO [3111936184 28.61s] outbound/direct[direct-out]: outbound packet connection
+0000 2023-05-14 15:16:52 INFO [3111936184 34.20s] router: inbound multiplex connection to 142.250.141.100:443
+0000 2023-05-14 15:16:52 INFO [3111936184 34.20s] outbound/direct[direct-out]: outbound connection to 142.250.141.100:443
+0000 2023-05-14 15:17:18 INFO [1278103049 350m46s] router: inbound multiplex connection to 20.125.63.4:443
+0000 2023-05-14 15:17:18 INFO [1278103049 350m46s] outbound/direct[direct-out]: outbound connection to 20.125.63.4:443
+0000 2023-05-14 15:17:19 INFO [1278103049 350m47s] router: inbound multiplex connection to 104.122.29.92:443
+0000 2023-05-14 15:17:19 INFO [1278103049 350m47s] outbound/direct[direct-out]: outbound connection to 104.122.29.92:443
+0000 2023-05-14 15:17:20 INFO [524355410 321m30s] router: inbound multiplex connection to 52.113.194.132:443
+0000 2023-05-14 15:17:20 INFO [524355410 321m30s] outbound/direct[direct-out]: outbound connection to 52.113.194.132:443
+0000 2023-05-14 15:18:15 INFO [3111936184 1m57s] router: inbound multiplex connection to 188.34.152.77:443
+0000 2023-05-14 15:18:15 INFO [3111936184 1m57s] outbound/direct[direct-out]: outbound connection to 188.34.152.77:443
+0000 2023-05-14 15:18:26 INFO [524355410 322m35s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:18:26 INFO [524355410 322m35s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:18:26 INFO [524355410 322m36s] router: inbound multiplex connection to 18.65.3.43:443
+0000 2023-05-14 15:18:26 INFO [524355410 322m36s] outbound/direct[direct-out]: outbound connection to 18.65.3.43:443
+0000 2023-05-14 15:19:45 INFO [1278103049 353m13s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:19:45 INFO [1278103049 353m13s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:19:46 INFO [1278103049 353m13s] router: inbound multiplex connection to 142.251.40.35:443
+0000 2023-05-14 15:19:46 INFO [1278103049 353m13s] outbound/direct[direct-out]: outbound connection to 142.251.40.35:443
+0000 2023-05-14 15:20:39 INFO [1278103049 354m7s] router: inbound multiplex connection to 35.223.238.178:443
+0000 2023-05-14 15:20:39 INFO [1278103049 354m7s] outbound/direct[direct-out]: outbound connection to 35.223.238.178:443
+0000 2023-05-14 15:21:52 INFO [1278103049 355m20s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:21:52 INFO [1278103049 355m20s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:21:53 INFO [524355410 326m2s] router: inbound multiplex connection to 142.250.141.138:443
+0000 2023-05-14 15:21:53 INFO [524355410 326m2s] outbound/direct[direct-out]: outbound connection to 142.250.141.138:443
+0000 2023-05-14 15:22:53 INFO [1278103049 356m20s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:22:53 INFO [1278103049 356m20s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:22:56 INFO [524355410 327m5s] router: inbound multiplex connection to 172.217.14.74:443
+0000 2023-05-14 15:22:56 INFO [524355410 327m5s] outbound/direct[direct-out]: outbound connection to 172.217.14.74:443
+0000 2023-05-14 15:22:56 INFO [3111936184 6m38s] router: inbound multiplex connection to 172.217.14.74:443
+0000 2023-05-14 15:22:56 INFO [3111936184 6m38s] outbound/direct[direct-out]: outbound connection to 172.217.14.74:443
+0000 2023-05-14 15:23:02 INFO [1278103049 356m29s] router: inbound multiplex connection to 104.208.16.89:443
+0000 2023-05-14 15:24:12 INFO [1278103049 357m39s] router: inbound multiplex connection to 104.86.72.6:80
+0000 2023-05-14 15:24:12 INFO [1278103049 357m39s] outbound/direct[direct-out]: outbound connection to 104.86.72.6:80
+0000 2023-05-14 15:24:55 INFO [524355410 329m5s] router: inbound multiplex connection to 35.244.181.201:443
+0000 2023-05-14 15:24:55 INFO [524355410 329m5s] outbound/direct[direct-out]: outbound connection to 35.244.181.201:443
+0000 2023-05-14 15:26:29 INFO [1278103049 359m57s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:26:29 INFO [1278103049 359m57s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:26:32 INFO [306774281 24m37s] router: inbound multiplex connection to 35.223.238.178:443
+0000 2023-05-14 15:26:32 INFO [306774281 24m37s] outbound/direct[direct-out]: outbound connection to 35.223.238.178:443
+0000 2023-05-14 15:26:35 INFO [1278103049 360m3s] router: inbound multiplex connection to 35.223.238.178:443
+0000 2023-05-14 15:26:35 INFO [1278103049 360m3s] outbound/direct[direct-out]: outbound connection to 35.223.238.178:443
+0000 2023-05-14 15:26:56 INFO [524355410 331m5s] router: inbound multiplex connection to 142.250.141.101:443
+0000 2023-05-14 15:26:56 INFO [524355410 331m5s] outbound/direct[direct-out]: outbound connection to 142.250.141.101:443
+0000 2023-05-14 15:28:26 INFO [1278103049 361m53s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:28:26 INFO [1278103049 361m53s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:28:26 INFO [524355410 332m36s] router: inbound multiplex connection to 18.65.3.92:443
+0000 2023-05-14 15:28:26 INFO [524355410 332m36s] outbound/direct[direct-out]: outbound connection to 18.65.3.92:443
+0000 2023-05-14 15:31:59 INFO [1278103049 365m27s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:31:59 INFO [1278103049 365m27s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:32:02 INFO [524355410 336m11s] router: inbound multiplex connection to 142.251.2.102:443
+0000 2023-05-14 15:32:02 INFO [524355410 336m11s] outbound/direct[direct-out]: outbound connection to 142.251.2.102:443
+0000 2023-05-14 15:32:34 INFO [524355410 336m43s] router: inbound multiplex connection to 52.143.86.214:443
+0000 2023-05-14 15:32:34 INFO [524355410 336m43s] outbound/direct[direct-out]: outbound connection to 52.143.86.214:443
+0000 2023-05-14 15:34:15 INFO [1278103049 367m42s] router: inbound multiplex connection to 8.8.8.8:853
+0000 2023-05-14 15:34:15 INFO [1278103049 367m42s] outbound/direct[direct-out]: outbound connection to 8.8.8.8:853
+0000 2023-05-14 15:34:17 INFO [524355410 338m26s] router: inbound multiplex connection to 204.79.197.222:443
+0000 2023-05-14 15:34:17 INFO [524355410 338m26s] outbound/direct[direct-out]: outbound connection to 204.79.197.222:443
+0000 2023-05-14 15:34:17 INFO [306774281 32m22s] router: inbound multiplex connection to 204.79.197.222:443
+0000 2023-05-14 15:34:17 INFO [306774281 32m22s] outbound/direct[direct-out]: outbound connection to 204.79.197.222:443
+0000 2023-05-14 15:34:17 INFO [306774281 32m22s] router: inbound multiplex connection to 95.101.74.148:443
+0000 2023-05-14 15:34:17 INFO [306774281 32m22s] outbound/direct[direct-out]: outbound connection to 95.101.74.148:443
panic: close of closed channel
  
goroutine 350145 [running]:
github.com/sagernet/sing-mux.(*h2MuxConnWrapper).Close(0xc0004e3f50)
        github.com/sagernet/sing-mux@v0.0.0-20230425130511-b0a6ffd8406f/h2mux.go:149 +0x37
github.com/sagernet/sing/common.Close({0xc000499ea8?, 0x1, 0xf99140?})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/cond.go:326 +0x8e
github.com/sagernet/sing/common/bufio.CopyConnContextList.func4({0x0?, 0x0?})
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/bufio/copy.go:240 +0xe2
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/task/task.go:68 +0x84
created by github.com/sagernet/sing/common/task.(*Group).RunContextList
        github.com/sagernet/sing@v0.2.5-0.20230501044132-8365dd48a17a/common/task/task.go:67 +0x17e
```

</details>

**Comment by hibobmaster** [comment]
Fixed. 
https://github.com/SagerNet/sing-box/commit/a7758f32c6fc598979c24e643e94703cce3e5e55
