### ISSUE TITLE
dev-next latest 运行hysteria 和 wireguard出现 panic

### ISSUE THREAD

**Issue by wsvg14** [SagerNet/sing-box#648]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

最新dev-next分支，启动带hysteria或wireguard配置会直接Panic，与服务器无关
不知道和我更换了amd cpu电脑是否有关系，因为同一配置在某个老版本程序运行于intel cpu未报错，同一编译程序在amd cpu运行时wireguard outbound会报同样panic
使用了amd64_v3编译，但是v1同样会报错

### Version of sing-box

<details>

```console
$ sing-box version
sing-box version 1.3-beta13

Environment: go1.20.5 windows/amd64
Tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_gvisor
Revision: a7f77d59c112ff352d140c9d394dde6e9022475d
CGO: enabled
```

</details>

### Server and client configuration file

only provide client config because it is not a server related issue
<details>

```console
{
  "log": {
    "disabled": false,
    "level": "error",
    "output": "./src/log/box.log",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "proxyServerNameServer",
        "address": "https://223.5.5.5/dns-query",
        "detour": "direct"
      },
      {
        "tag": "dnspod",
        "address": "https://223.5.5.5/dns-query",
        "detour": "direct"
      },
      {
        "tag": "local",
        "address": "local",
        "detour": "direct"
      },
      {
        "tag": "dhcp",
        "address": "dhcp://auto"
      },
      {
        "tag": "googledns",
        "address": "https://dns.google/dns-query",
        "address_resolver": "dnspod",
        "address_strategy": "ipv4_only",
        "detour": "proxy"
      },
      {
        "tag": "nxdomain",
        "address": "RCode://name_error"
      }
    ],
    "rules": [
      {
        "outbound": "any",
        "server": "proxyServerNameServer"
      },
      {
        "geosite": "category-ads-all",
        "server": "nxdomain",
        "disable_cache": false
      },
      {
        "domain_suffix": [
          ".xn--ngstr-lra8j.com",
          ".googleapis.cn",
          ".dev"
        ],
        "geosite": [
          "tiktok"
        ],
        "server": "googledns",
        "disable_cache": false
      },
      {
        "domain_keyword": [
          "ntp"
        ],
        "domain_suffix": [
          ".mp.microsoft.com"
        ],
        "domain_regex": [
          "(^|\\.)(alt[1-8]-mtalk|mtalk|mtalk4)\\.google\\.com$"
        ],
        "geosite": [
          "bytedance",
          "microsoft@cn",
          "apple@cn",
          "category-games@cn",
          "cn"
        ],
        "server": "dnspod",
        "disable_cache": false
      }
    ],
    "final": "googledns",
    "strategy": "prefer_ipv6",
    "disable_cache": false,
    "disable_expire": false
  },
  "inbounds": [
    {
      "tag": "mixed",
      "type": "mixed",
      "listen": "::",
      "listen_port": 7890,
      "sniff_timeout": "500ms",
      "sniff": true,
      "sniff_override_destination": true
    }
  ],
    "outbounds": [
    {
      "tag": "direct",
      "type": "direct"
    },
    {
      "tag": "block",
      "type": "block"
    },
    {
      "tag": "dns",
      "type": "dns"
    },
    {
      "tag": "proxy",
      "type": "selector",
      "outbounds": [
        "warp",
        "hysteria"
      ]
    },
    {
      "tag": "warp",
      "type": "wireguard",
      "server": "162.159.195.183",
      "server_port": 934,
      "local_address": [
        "172.16.0.2/32",
        "2606:4700:110:80f3:d115:2fe9:9556:311d/128"
      ],
      "private_key": "xxx",
      "peer_public_key": "xxx",
      "reserved": [
        35,
        111,
        54
      ],
      "mtu": 1280,
    },
    {
      "tag": "hysteria",
      "type": "hysteria",
      "server": "xxx",
      "server_port": 5201,
      "disable_mtu_discovery": false,
      "tls": {
        "enabled": true,
        "insecure": false,
        "alpn": [
          "h3"
        ],
        "server_name": "xxx"
      },
      "auth_str": "xxx",
      "up": "200Mbps",
      "down": "200Mbps"
    }
  ],
  "route": {
    "geosite": {
      "path": "./src/geosite.db",
      "download_url": "https://ghproxy.com/https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/geosite.db",
      "download_detour": "direct"
    },
    "geoip": {
      "path": "./src/geoip.db",
      "download_url": "https://ghproxy.com/https://raw.githubusercontent.com/CHIZI-0618/v2ray-rules-dat/release/geoip.db",
      "download_detour": "direct"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns"
      },
      {
        "protocol": [
          "quic"
        ],
        "outbound": "block"
      },
      {
        "protocol": [
          "stun"
        ],
        "ip_cidr": [
          "106.75.74.76/32",
          "111.206.25.147/32",
          "119.3.238.64/32",
          "120.92.108.182/32",
          "120.92.113.99/32",
          "120.92.153.217/32",
          "134.175.207.130/32",
          "203.107.1.0/24"
        ],
        "domain_keyword": [
          "bilibili",
          "douyu"
        ],
        "geosite": [
          "bilibili",
          "douyu"
        ],
        "outbound": "block"
      },
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "domain_keyword": [
              "stun"
            ]
          },
          {
            "domain_keyword": [
              "bilibili",
              "douyu"
            ],
            "geosite": [
              "bilibili",
              "douyu"
            ]
          }
        ],
        "outbound": "block"
      },
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "domain_keyword": [
              "mcdn"
            ]
          },
          {
            "domain_keyword": [
              "bilibili"
            ],
            "geosite": [
              "bilibili"
            ]
          }
        ],
        "outbound": "block"
      },
      {
        "ip_cidr": [
          "106.75.74.76/32",
          "111.206.25.147/32",
          "119.3.238.64/32",
          "120.92.108.182/32",
          "120.92.113.99/32",
          "120.92.153.217/32",
          "134.175.207.130/32",
          "203.107.1.0/24"
        ],
        "domain_keyword": [
          "bilibili",
          "mcdn"
        ],
        "geosite": [
          "bilibili"
        ],
        "port": [
          4483,
          9305
        ],
        "outbound": "block"
      },
      {
        "domain_suffix": [
          ".xn--ngstr-lra8j.com",
          ".googleapis.cn",
          ".dev"
        ],
        "geosite": [
          "tiktok"
        ],
        "outbound": "proxy"
      },
      {
        "domain_keyword": [
          "ntp"
        ],
        "domain_suffix": [
          ".mp.microsoft.com"
        ],
        "domain_regex": [
          "(^|\\.)(alt[1-8]-mtalk|mtalk|mtalk4)\\.google\\.com$"
        ],
        "geosite": [
          "bytedance",
          "microsoft@cn",
          "apple@cn",
          "category-games@cn",
          "cn"
        ],
        "outbound": "domestic"
      },
      {
        "geoip": [
          "private"
        ],
        "outbound": "direct"
      },
      {
        "geoip": [
          "cn"
        ],
        "outbound": "domestic"
      }
    ],
    "final": "proxy",
    "auto_detect_interface": true,
    "find_process": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9909",
      "external_ui": "Dashboard",
      "default_mode": "rule",
      "secret": "singBox",
      "cache_file": "./src/cache_custom.db",
      "store_selected": true
    }
  }
}
```

</details>

### Server and client log file

<details>

```console
~  ♥ 21:00 d:\sing-box\sing-box.exe run -c "D:\sing\mywork.json" -D "D:\sing"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x11e43ff]

goroutine 63 [running]:
github.com/sagernet/sing-box/outbound.(*Selector).DialContext(0x0?, {0x1877180?, 0xc00049a3c0?}, {0x16653fc?, 0x0?}, {{{0x0, 0xffffa29fc3b7}, 0xc000008078}, 0x3a6, {0x0, ...}})
        github.com/sagernet/sing-box/outbound/selector.go:115 +0x3f
github.com/sagernet/sing-box/common/dialer.(*DetourDialer).DialContext(0xc0003a2000?, {0x1877180, 0xc00049a3c0}, {0x16653fc, 0x3}, {{{0x0, 0xffffa29fc3b7}, 0xc000008078}, 0x3a6, {0x0, ...}})
        github.com/sagernet/sing-box/common/dialer/detour.go:47 +0x9c
github.com/sagernet/sing-box/transport/wireguard.(*ClientBind).connect(0xc00030a120)
        github.com/sagernet/sing-box/transport/wireguard/client_bind.go:70 +0x1b5
github.com/sagernet/sing-box/transport/wireguard.(*ClientBind).receive(0xc00030a120, {0xc0003020f0, 0x1, 0xc0000ec7e0?}, {0xc000400080, 0x1, 0xc000362001?}, {0xc000520120, 0x1, 0x1})
        github.com/sagernet/sing-box/transport/wireguard/client_bind.go:105 +0x56
github.com/sagernet/wireguard-go/device.(*Device).RoutineReceiveIncoming(0xc0000cb900, 0x1, 0xc000520020)
        github.com/sagernet/wireguard-go@v0.0.0-20230420044414-a7bac1754e77/device/receive.go:108 +0x3c4
created by github.com/sagernet/wireguard-go/device.(*Device).BindUpdate
        github.com/sagernet/wireguard-go@v0.0.0-20230420044414-a7bac1754e77/device/device.go:532 +0x450
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x80 pc=0x11f16c9]

goroutine 39 [running]:
github.com/sagernet/sing-box/outbound.(*URLTestGroup).Start(0x1000000000000?)
        github.com/sagernet/sing-box/outbound/urltest.go:178 +0x29
github.com/sagernet/sing-box/outbound.(*URLTest).DialContext(0xc000385290, {0x1877180, 0xc00049b0b0}, {0x16653fc, 0x3}, {{{0x0, 0xffffa29fc3b7}, 0xc000008078}, 0x3a6, {0x0, ...}})
        github.com/sagernet/sing-box/outbound/urltest.go:99 +0x4f
github.com/sagernet/sing-box/common/dialer.(*DetourDialer).DialContext(0xc00030c0d0?, {0x1877180, 0xc00049b0b0}, {0x16653fc, 0x3}, {{{0x0, 0xffffa29fc3b7}, 0xc000008078}, 0x3a6, {0x0, ...}})
        github.com/sagernet/sing-box/common/dialer/detour.go:47 +0x9c
github.com/sagernet/sing-box/transport/wireguard.(*ClientBind).connect(0xc00030a2d0)
        github.com/sagernet/sing-box/transport/wireguard/client_bind.go:70 +0x1b5
github.com/sagernet/sing-box/transport/wireguard.(*ClientBind).receive(0xc00030a2d0, {0xc0002b2060, 0x1, 0xc0000ed0a0?}, {0xc00051e230, 0x1, 0xc000462001?}, {0xc0001be120, 0x1, 0x1})
        github.com/sagernet/sing-box/transport/wireguard/client_bind.go:105 +0x56
github.com/sagernet/wireguard-go/device.(*Device).RoutineReceiveIncoming(0xc0000cbb80, 0x1, 0xc0001be020)
        github.com/sagernet/wireguard-go@v0.0.0-20230420044414-a7bac1754e77/device/receive.go:108 +0x3c4
created by github.com/sagernet/wireguard-go/device.(*Device).BindUpdate
        github.com/sagernet/wireguard-go@v0.0.0-20230420044414-a7bac1754e77/device/device.go:532 +0x450

 ~  ♥ 21:00  d:\sing-box\sing-box.exe run -c "D:\sing\box.json" -D "D:\sing"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x11e110a]

goroutine 25 [running]:
github.com/sagernet/sing-box/outbound.(*Hysteria).open(0xc000241800?, {0x1877148, 0xc0004dc3f0}, 0x0)
        github.com/sagernet/sing-box/outbound/hysteria.go:271 +0xaa
github.com/sagernet/sing-box/outbound.(*Hysteria).open(0x160cec0?, {0x1877148, 0xc0004dc3f0}, 0x1)
        github.com/sagernet/sing-box/outbound/hysteria.go:268 +0x91
github.com/sagernet/sing-box/outbound.(*Hysteria).DialContext(0xc000241800, {0x1877148, 0xc0004dc3f0}, {0x16653e4, 0x3}, {{{0x0, 0x0}, 0x0}, 0x1bb, {0x1692eb2, ...}})
        github.com/sagernet/sing-box/outbound/hysteria.go:284 +0x225
github.com/sagernet/sing-box/common/urltest.URLTest({0x1877148?, 0xc0004dc3f0}, {0x0?, 0x0?}, {0x18705d8, 0xc000241800})
        github.com/sagernet/sing-box/common/urltest/urltest.go:72 +0x226
github.com/sagernet/sing-box/outbound.(*URLTestGroup).urlTest.func1()
        github.com/sagernet/sing-box/outbound/urltest.go:299 +0x139
github.com/sagernet/sing/common/batch.(*Batch[...]).Go.func1()
        github.com/sagernet/sing@v0.2.5-0.20230611070640-2812461739c3/common/batch/batch.go:59 +0x12e
created by github.com/sagernet/sing/common/batch.(*Batch[...]).Go
        github.com/sagernet/sing@v0.2.5-0.20230611070640-2812461739c3/common/batch/batch.go:50 +0xdb

```

</details>

**Comment by wsvg14** [comment]
fix
