### ISSUE TITLE
莫名其妙报错

### ISSUE THREAD

**Issue by wish13-un** [SagerNet/sing-box#673]
### Welcome

- [ ] Yes, I'm using the latest major release. Only such installations are supported.
- [ ] Yes, I'm using the latest Golang release. Only such installations are supported.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Description of the problem

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e6c80df98]

goroutine 1 [running]:
github.com/sagernet/sing-box.(*Box).startOutbounds.func2({0x40004716c0?, 0x1, 0x1}, {0x0, 0x0})
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/box_outbound.go:61 +0x58
github.com/sagernet/sing-box.(*Box).startOutbounds(0x4000476b40)
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/box_outbound.go:73 +0x594
github.com/sagernet/sing-box.(*Box).preStart(0x4000476b40)
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/box.go:220 +0x228
github.com/sagernet/sing-box.(*Box).start(0x4000476b40)
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/box.go:228 +0x28
github.com/sagernet/sing-box.(*Box).Start(0x4000476b40)
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/box.go:194 +0x30
main.create()
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/cmd/sing-box/cmd_run.go:153 +0x340
main.run()
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/cmd/sing-box/cmd_run.go:166 +0xc8
main.glob..func7(0x5e6d4cd7a0?, {0x5e6b9fe3eb?, 0x4?, 0x4?})
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/cmd/sing-box/cmd_run.go:28 +0x1c
github.com/spf13/cobra.(*Command).execute(0x5e6d4cd7a0, {0x4000057600, 0x4, 0x4})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x5e6d4cda80)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        github.com/sagernet/sing-box@v1.2.8-0.20230623081225-c2bda9fbdeff/cmd/sing-box/main.go:33 +0x28

### Version of sing-box

<details>

```console
$ sing-box version 这个issue提交前19小时更新的那一次dev-next
# Paste output here
```

</details>

### Server and client configuration file

无

### Server and client log file

无

**Comment by wish13-un** [comment]
具体版本，https://github.com/SagerNet/sing-box/actions/runs/5354272739

**Comment by wish13-un** [comment]
sing-box version 114514

Environment: go1.20.5 android/arm64
Tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_gvisor,with_utls,with_clash_api,with_shadowsocksr,with_ech,with_acme,with_reality_server
CGO: enabled
