### ISSUE TITLE
SFA在setting界面点击dashboard后闪退

### ISSUE THREAD

**Issue by QuietStone** [SagerNet/sing-box#784]
### 操作系统

Android

### 系统版本

13.1

### 安装类型

sing-box for Android 图形客户端程序

### 如果您使用图形客户端程序，请提供该程序版本。

Version 1.4.0-beta.6-alpha (67)

### 版本

<details>
```console
# 使用输出内容覆盖此行
```
</details>

### 描述

在sfa主界面进入setting界面后再返回dashboard界面发生闪退

### 重现方式

在sfa主界面进入setting界面后再返回dashboard界面发生闪退

### 日志

<details>
```console
panic: seq.Inc: unknown refnum: -53

goroutine 17 [running, locked to thread]:
github.com/sagernet/gomobile/bind/seq.Inc(0x3896fd01?)
        github.com/sagernet/gomobile@v0.0.0-20230728014906-3de089147f59/bind/seq/ref.go:132 +0x1c8
main.IncGoRef(...)
        gobind/gobind/seq.go:49
```
</details>

**Comment by QuietStone** [comment]
SFA 1.4.0-beta.6-alpha (68) 已解决
