### ISSUE TITLE
程序运行中 崩溃

### ISSUE THREAD

**Issue by architecturers** [SagerNet/sing-box#817]
### Operating system

Others

### System version

openwrt 23.05 rc3

### Installation type

Original sing-box Command Line

### Version

<details>
```console
root@OpenWrt:~# ./sing-box version
sing-box version 1.4.0

Environment: go1.21.0 linux/amd64
Tags: with_quic,with_ech
Revision: c75e32e7220e8021822956638fcadb6054b3ca8d
CGO: disabled
root@OpenWrt:~#
```
</details>

### Description

程序运行一段时间自动崩溃

### Reproduction

顺便说以下 好多版本都崩溃 目前测试 1.4.0-rc5 这个版本 可以正常运行 不崩溃

### Logs

<details>
```console
root@OpenWrt:~# ./sing-box run -c ./sing-box.jsonc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7d90b7]

goroutine 872 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).Len(...)
        github.com/sagernet/sing@v0.2.10-0.20230824115837-8d731e68853a/common/buf/buffer.go:321
github.com/sagernet/sing/common/bufio.CopyPacketWithSrcBuffer({0x7fe9f56c5140?, 0xc000d72870}, {0x7fe9f56c5120, 0xc000d727e0}, {0x7fe9f56c5210, 0xc000d72870}, {0x0, 0x0, 0x16522e0?}, {0x0, ...}, ...)
        github.com/sagernet/sing@v0.2.10-0.20230824115837-8d731e68853a/common/bufio/copy.go:295 +0x117
github.com/sagernet/sing/common/bufio.CopyPacket({0x7fe9f56c5120?, 0xc000d727e0?}, {0x7fe9f56c5140, 0xc000d72870})
        github.com/sagernet/sing@v0.2.10-0.20230824115837-8d731e68853a/common/bufio/copy.go:265 +0x385
github.com/sagernet/sing/common/bufio.CopyPacketConnContextList.func2({0xfe1800?, 0xc000a03600?})
        github.com/sagernet/sing@v0.2.10-0.20230824115837-8d731e68853a/common/bufio/copy.go:399 +0x66
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.2.10-0.20230824115837-8d731e68853a/common/task/task.go:68 +0x73
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 870
        github.com/sagernet/sing@v0.2.10-0.20230824115837-8d731e68853a/common/task/task.go:67 +0x17c
root@OpenWrt:~#


root@OpenWrt:~# cat /tmp/sing-box.log
+0000 2023-08-29 11:08:03 ERROR router: initialize default interface: no route to internet
+0000 2023-08-29 11:08:04 ERROR router: missing default interface
+0000 2023-08-29 11:12:43 ERROR [148258133 399ms] inbound/tproxy[tproxy-in]: process connection from 192.168.1.160:39006: upload: stream 748 canceled by remote with error code 0
+0000 2023-08-29 11:12:59 ERROR [680974355 1m0s] inbound/tproxy[tproxy-in]: process connection from 192.168.1.228:41510: upload: stream 504 canceled by remote with error code 0
+0000 2023-08-29 11:13:03 ERROR [1339499233 1m7s] inbound/tproxy[tproxy-in]: process connection from 192.168.1.228:40036: upload: stream 408 canceled by remote with error code 0
+0000 2023-08-29 11:13:21 ERROR [2136149633 1.20s] inbound/tproxy[tproxy-in]: process connection from 192.168.1.160:39010: upload: stream 824 canceled by remote with error code 0
+0000 2023-08-29 11:14:14 ERROR [4095167421 359ms] inbound/tproxy[tproxy-in]: process connection from 192.168.1.196:37452: upload: stream 936 canceled by remote with error code 0
+0000 2023-08-29 11:14:17 ERROR [2011819989 356ms] inbound/tproxy[tproxy-in]: process connection from 192.168.1.196:47710: upload: stream 956 canceled by remote with error code 0
+0000 2023-08-29 11:15:24 ERROR [2037726207 601ms] inbound/tproxy[tproxy-in]: process connection from 192.168.1.177:49839: upload: stream 1476 canceled by remote with error code 0
+0000 2023-08-29 11:16:49 ERROR [3671247424 1m1s] inbound/tproxy[tproxy-in]: process connection from 192.168.1.228:42436: upload: stream 1492 canceled by remote with error code 0

```
</details>

**Comment by architecturers** [comment]
已经更新了 你看下 还需要 什么信息
