### ISSUE TITLE
dev-next 分支编译服务端出现 panic 错误

### ISSUE THREAD

**Issue by UptonEdward** [SagerNet/sing-box#827]
### 操作系统

Linux

### 系统版本

Linux 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux

### 安装类型

sing-box 原始命令行程序

### 版本

<details>

```console
sing-box version unknown

Environment: go1.21.0 linux/amd64
Tags: with_reality_server,with_quic,with_v2ray_api
Revision: fcb5a0157b615572a4c8f9c6baca1f57b5136c3a
CGO: disabled
```
</details>

### 描述

使用最新的 dev-next 编译出来的服务端无法启动，出现 panic 错误。

### 重现方式

使用 dev-next 分支的最新提交进行编译更新，编译完成后重启 sing-box 即出现该错误。

服务端配置文件（脱敏）：
```
{
  "experimental": {
    "v2ray_api": {
      "listen": "127.0.0.1:8080",
      "stats": {
        "enabled": true,
        "users": []
      }
    }
  },
  "log": {
    "level": "warn",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "doh",
        "address": "https://8.8.8.8/dns-query",
        "strategy": "prefer_ipv6"
      },
      {
        "tag": "direct-dns",
        "address": "8.8.8.8",
        "strategy": "prefer_ipv6"
      }
    ],
    "rules": [
      {
        "geosite": [
          "dmm",
          "tvb",
          "viu"
        ],
        "domain_suffix": ".jp",
        "server": "direct-dns"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tuic",
      "tag": "tuic-in",
      "listen": "0.0.0.0",
      "listen_port": 10086,
      "sniff": true,
      "users": [],
      "congestion_control": "bbr",
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "alpn": [
          "h3"
        ],
        "certificate_path": "/root/cert/fullchain.cer",
        "key_path": "/root/cert/private.key"
      }
    },
    {
      "type": "vmess",
      "tag": "vmess-relay-in",
      "listen": "::",
      "listen_port": 10086,
      "tcp_fast_open": true,
      "proxy_protocol": true,
      "proxy_protocol_accept_no_header": true,
      "sniff": true,
      "users": [],
      "tls": {
        "enabled": false
      }
    },
    {
      "type": "vless",
      "tag": "vless-in",
      "listen": "0.0.0.0",
      "listen_port": 10086,
      "tcp_fast_open": true,
      "proxy_protocol": true,
      "proxy_protocol_accept_no_header": true,
      "sniff": true,
      "users": [],
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "example.com",
            "server_port": 443
          },
          "private_key": "key",
          "short_id": "id"
        }
      }
    },
    {
      "type": "shadowsocks",
      "tag": "me-ss-in",
      "listen": "0.0.0.0",
      "listen_port": 10086,
      "tcp_fast_open": true,
      "proxy_protocol": true,
      "proxy_protocol_accept_no_header": true,
      "sniff": true,
      "method": "aes-128-gcm",
      "password": "paswd"
    },
    {
      "type": "shadowsocks",
      "tag": "vps-in",
      "listen": "::",
      "listen_port": 10086,
      "tcp_fast_open": true,
      "sniff": true,
      "method": "aes-128-gcm",
      "password": "paswd"
    },
    {
      "type": "trojan",
      "tag": "trojan-ws-in",
      "listen": "127.0.0.1",
      "listen_port": 10086,
      "tcp_fast_open": true,
      "proxy_protocol": true,
      "proxy_protocol_accept_no_header": true,
      "sniff": true,
      "users": [],
      "tls": {
        "enabled": false
      },
      "transport": {
        "type": "ws",
        "path": "/path",
        "max_early_data": 2048,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct",
      "domain_strategy": "prefer_ipv6"
    }
  ]
}
```

### 日志

<details>

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x89fe72]

goroutine 1 [running]:
github.com/sagernet/sing-box/common/dialer.NewDefault({0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, ...})
 github.com/sagernet/sing-box/common/dialer/default.go:35 +0x1b2
github.com/sagernet/sing-box/common/dialer.New({0x0?, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, ...})
 github.com/sagernet/sing-box/common/dialer/dialer.go:23 +0x78
github.com/sagernet/sing-box/common/tls.NewRealityServer({0x113b060, 0xc0001d3c50}, {0xf7cc20?, _}, {0x1, {0xc0001d4054, 0xc}, 0x0, {0x0, 0x0, ...}, ...})
 github.com/sagernet/sing-box/common/tls/reality_server.go:105 +0xe87
github.com/sagernet/sing-box/common/tls.NewServer({0x113b060?, 0xc0001d3c50?}, {0x7f42e3047bb0?, _}, {0x1, {0xc0001d4054, 0xc}, 0x0, {0x0, 0x0, ...}, ...})
 github.com/sagernet/sing-box/common/tls/server.go:20 +0xc5
github.com/sagernet/sing-box/inbound.NewVLESS({0x113b060?, 0xc0001d3c50}, {0x114c980?, 0xc000144500}, {0x1147bb0?, 0xc00021a510}, {0xc0001b0f58, 0x8}, {{0xc0001acf00, 0x2cb3, ...}, ...})
 github.com/sagernet/sing-box/inbound/vless.go:64 +0x6bd
github.com/sagernet/sing-box/inbound.New({_, _}, {_, _}, {_, _}, {{0xc0001b0f50, 0x5}, {0xc0001b0f58, 0x8}, ...}, ...)
 github.com/sagernet/sing-box/inbound/builder.go:46 +0x3e5
github.com/sagernet/sing-box.New({{{0x0, 0x0}, 0xc0001901e0, 0xc00003ab40, 0x0, {0xc0001dc000, 0x6, 0x8}, {0xc00020e000, 0x4, ...}, ...}, ...})
 github.com/sagernet/sing-box/box.go:99 +0xae9
main.create()
 github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:131 +0x1f8
main.run()
 github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:166 +0x10d
main.glob..func8(0xc000121100?, {0xfc0ec9?, 0x4?, 0xfc0ecd?})
 github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:28 +0x17
github.com/spf13/cobra.(*Command).execute(0x1828580, {0xc0000a6d80, 0x4, 0x4})
 github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x1828860)
 github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
 github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
 github.com/sagernet/sing-box/cmd/sing-box/main.go:33 +0x1e
```
</details>

**Comment by nekohasekai** [comment]
Try latest commits

**Comment by Mahdi-zarei** [comment]
#828 this PR fixes the problem, as far as I understand the router has not been added to context and TLS servers operate on a nil object as router which causes the startup to end with a panic.

**Comment by nekohasekai** [comment]
Try the latest commit
