### ISSUE TITLE
Panic, Termux on Android 

### ISSUE THREAD

**Issue by SimonWe1** [SagerNet/sing-box#84]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the latest Golang release. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem

已出现两次，目前仅保存了这部分日志，等待再次复现贴出完整日志

### Version of sing-box

<details>

```console
$ sing-box version
[sing-box-1.1-beta4-android-arm64.tar.gz](https://github.com/SagerNet/sing-box/releases/download/v1.1-beta4/sing-box-1.1-beta4-android-arm64.tar.gz)
```

</details>

### Server and client configuration file

<details>

```console
{
    "log": {
        "disabled": true,
        "level": "error",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "dns",
                "address": "tls://223.5.5.5",
                "strategy": "ipv4_only",
                "detour": "direct"
            }
        ],
        "strategy": "ipv4_only"
    },
    "inbounds": [
        {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fdfe:dcba:9876::1/126",
            "mtu": 1500,
            "auto_route": true,
            "endpoint_independent_nat": false,
            "stack": "system",
            "sniff": true,
            "sniff_override_destination": false
        }
    ],
    "outbounds": [
        {
            "type": "selector",
            "tag": "proxy",
            "outbounds": [
                "us-ss",
                "sg-trojan"
            ],
            "default": "us-ss"
        },
        {
            "type": "shadowsocks",
            "tag": "us-ss",
            "server": "xxx",
            "server_port": 23333,
            "method": "2022-blake3-aes-128-gcm",
            "password": "xxx",
            "udp_over_tcp": true
        },
        {
            "type": "trojan",
            "tag": "sg-trojan",
            "server": "xxx",
            "server_port": 443,
            "password": "xxx",
            "network": "tcp",
            "tls": {
                "enabled": true,
                "server_name": "xxx",
                "alpn": [
                    "http/1.1"
                ]
            },
            "transport": {
                "type": "ws",
                "path": "/xxx",
                "headers": {
                    "Host": "xxx"
                },
                "max_early_data": 2048,
                "early_data_header_name": "Sec-WebSocket-Protocol"
            }
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "geosite": "google",
                "outbound": "proxy"
            },
            {
                "geosite": "cn",
                "outbound": "direct"
            },
            {
                "ip_cidr": [
                    "xxx/32"
                ],
                "outbound": "direct"
            },
            {
                "geoip": "private",
                "outbound": "direct"
            },
            {
                "geoip": "cn",
                "outbound": "direct"
            }
        ],
        "auto_detect_interface": true
    },
    "experimental": {
        "clash_api": {
            "external_controller": "127.0.0.1:9090",
            "external_ui": "yacd",
            "secret": ""
        }
    }
}

```

</details>

### Server and client log file

<details>

```console
/data/adb/sing/sing-box run -c /data/adb/sing/config.json

panic: alloc bad size: 0

goroutine 21 [running]:
github.com/sagernet/sing/common/buf.(*defaultAllocator).Get(0x40?, 0x8?)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20220913004915-27ddefbb8921/common/buf/alloc.go:42 +0x170
github.com/sagernet/sing/common/buf.Get(...)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20220913004915-27ddefbb8921/common/buf/pool.go:4
github.com/sagernet/sing/common/buf.NewSize(0x4000027bd8?)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20220913004915-27ddefbb8921/common/buf/buffer.go:54 +0xac
github.com/sagernet/sing/common/buf.(*Buffer).ToOwned(0x4000027d20)
        pkg/mod/github.com/sagernet/sing@v0.0.0-20220913004915-27ddefbb8921/common/buf/buffer.go:397 +0x28
github.com/sagernet/sing-tun.(*System).processIPv4UDP(0x400013c120, {0x40003fe000, 0x1c, 0x800}, {0x40003fe014, 0x8, 0x7ec})
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20220911034209-c7dd5d457e24/system.go:306 +0x260
github.com/sagernet/sing-tun.(*System).processIPv4(0x5dc?, {0x40003fe000?, 0x400013c000?, 0x0?})
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20220911034209-c7dd5d457e24/system.go:219 +0x134
github.com/sagernet/sing-tun.(*System).tunLoop(0x400013c120)
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20220911034209-c7dd5d457e24/system.go:131 +0x248
created by github.com/sagernet/sing-tun.(*System).Start
        pkg/mod/github.com/sagernet/sing-tun@v0.0.0-20220911034209-c7dd5d457e24/system.go:106 +0x4d0
```

</details>

**Comment by nekohasekai** [comment]
Try 9938a66b0afa97243fff4e05ef78152db2d6d2bd

**Comment by SimonWe1** [comment]
没有再复现，感谢修复！
