### ISSUE TITLE
macOS 平台下使用 FakeIP 模版配置，使用 vless 协议导致 panic

### ISSUE THREAD

**Issue by UptonEdward** [SagerNet/sing-box#843]
### 操作系统

macOS

### 系统版本

13.5.1 (22G90)

### 安装类型

sing-box 原始命令行程序

### 版本

<details>

```console
sing-box version unknown

Environment: go1.21.0 darwin/amd64
Tags: with_clash_api,with_quic,with_utls,with_gvisor,with_ech
Revision: dc985ed99dd91a27e85b30bb6c4cba5ea0bb496f
CGO: disabled
```
</details>

### 描述

在 panic 出现前，debug 级别的日志并没有显示异常。参照以下步骤会在一段时间内（通常短于 5 分钟）出现 panic。

若将 vless 代理换为其他类型代理，或者使用最简配置（指只保留一个 vless 出站和一个 tun 入站）则不会出现 panic。

### 重现方式

1. 使用 dev-next 分支的最新提交编译 sing-box。完整的编译命令：
```bash
CGO_ENABLED=0 go install -v -trimpath -ldflags "-s -w -buildid=" -tags with_clash_api,with_quic,with_utls,with_gvisor,with_ech ./cmd/sing-box
```
2. 使用以下配置（基本上就是 FakeIP 模板）启动 sing-box：

```
{
  "log": {
    "level": "debug",
    "output": "/usr/local/etc/sing-box/sing-box.log",
    "timestamp": true
  },
  "dns": {
    "reverse_mapping": true,
    "disable_cache": false,
    "independent_cache": true,
    "servers": [
      {
        "tag": "google",
        "address": "tcp://8.8.8.8"
      },
      {
        "tag": "local",
        "address": "h3://223.5.5.5/dns-query",
        "detour": "direct"
      },
      {
        "tag": "remote",
        "address": "fakeip"
      },
      {
        "tag": "block",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "geosite": "category-ads-all",
        "server": "block",
        "disable_cache": true
      },
      {
        "outbound": "any",
        "server": "local"
      },
      {
        "geosite": "cn",
        "server": "local"
      },
      {
        "query_type": [
          "A",
          "AAAA"
        ],
        "server": "remote"
      }
    ],
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15",
      "inet6_range": "fc00::/18"
    }
  },
  "route": {
    "rules": [
      {
        "port": 53,
        "outbound": "dns"
      },
      {
        "clash_mode": "direct",
        "outbound": "direct"
      },
      {
        "clash_mode": "global",
        "outbound": "代理"
      },
      {
        "geosite": "cn",
        "geoip": [
          "private",
          "cn"
        ],
        "outbound": "direct"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
    "find_process": true,
    "auto_detect_interface": true
  },
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed-in",
      "listen": "127.0.0.1",
      "listen_port": 6152,
      "sniff": true,
      "domain_strategy": "prefer_ipv4",
      "set_system_proxy": true
    },
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true,
      "stack": "mixed",
      "sniff": true,
      "domain_strategy": "prefer_ipv4"
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "代理",
      "outbounds": [
        "vless",
        "direct"
      ]
    },
    {
      "type": "vless",
      "tag": "vless",
      "server": "1.1.1.1",
      "server_port": 443,
      "tcp_fast_open": true,
      "uuid": "uuid",
      "flow": "",
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "key",
          "short_id": "id"
        }
      },
      "transport": {
        "type": "grpc",
        "service_name": "name"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns"
    }
  ],
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "default_mode": "rule",
      "store_selected": true,
      "store_fakeip": true,
      "cache_file": "/usr/local/etc/sing-box/cache.db"
    }
  }
}
```
3. 使用兼容 clash api 的面板进行节点切换、正常使用。
4. 该 panic 会出现在较为随机的时间，但通常是在节点切换了几次之后。清空系统 DNS 缓存也可能导致 panic。

### 日志

<details>

```console
panic: unsupported address

goroutine 218 [running]:
github.com/sagernet/sing/common.Must(...)
	github.com/sagernet/sing@v0.2.10-0.20230830132630-30bf19f2833c/common/cond.go:287
github.com/sagernet/sing-box/transport/vless.WriteRequest({0x4a8d1190, 0xc0012c6630}, {{0x41, 0xa3, 0xd8, 0xca, 0xfa, 0x4c, 0x5c, 0x68, ...}, ...}, ...)
	github.com/sagernet/sing-box/transport/vless/protocol.go:159 +0x685
github.com/sagernet/sing-box/transport/vless.(*Conn).Write(0xc000c12380, {0xc0012e8400, 0x199, 0x3c00})
	github.com/sagernet/sing-box/transport/vless/client.go:141 +0x118
github.com/sagernet/sing-box/outbound.CopyEarlyConn({0x1fa5268, 0xc0012c65a0}, {0x1faf1d0?, 0xc00040aba0}, {0x1faf800, 0xc000c12380})
	github.com/sagernet/sing-box/outbound/default.go:130 +0x3c7
github.com/sagernet/sing-box/outbound.NewConnection({_, _}, {_, _}, {_, _}, {{0xc0001d2130, 0x6}, {0x1deba2e, 0x3}, ...})
	github.com/sagernet/sing-box/outbound/default.go:70 +0x1fc
github.com/sagernet/sing-box/outbound.(*VLESS).NewConnection(_, {_, _}, {_, _}, {{0xc0001d2130, 0x6}, {0x1deba2e, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box/outbound/vless.go:122 +0x8b
github.com/sagernet/sing-box/outbound.(*Selector).NewConnection(_, {_, _}, {_, _}, {{0xc0001d2130, 0x6}, {0x1deba2e, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box/outbound/selector.go:124 +0x9b
github.com/sagernet/sing-box/route.(*Router).RouteConnection(_, {_, _}, {_, _}, {{0xc0001d2130, 0x6}, {0x1deba2e, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box/route/router.go:713 +0x217b
github.com/sagernet/sing-box/inbound.(*Tun).NewConnection(0xc0002b2000, {0x1fa5268?, 0xc0002aa060?}, {0x1fac4a8, 0xc00022c118}, {{0x0, 0x0}, {{{0x0, 0xffffac130001}, 0xc0000a8018}, ...}, ...})
	github.com/sagernet/sing-box/inbound/tun.go:206 +0x2f6
github.com/sagernet/sing-tun.(*System).acceptLoop.func1()
	github.com/sagernet/sing-tun@v0.1.12-0.20230821065522-7545dc2d5641/stack_system.go:223 +0x142
created by github.com/sagernet/sing-tun.(*System).acceptLoop in goroutine 78
	github.com/sagernet/sing-tun@v0.1.12-0.20230821065522-7545dc2d5641/stack_system.go:222 +0x445
```
</details>

**Comment by nekohasekai** [comment]
初步判断问题由 fakeip 传递了非法的域名造成，修复前可以删除 fakeip 解决问题。

**Comment by nekohasekai** [comment]
尝试最新版本
