### ISSUE TITLE
Linux客户端下无法使用smux以及set_system_proxy

### ISSUE THREAD

**Issue by ricolxwz** [SagerNet/sing-box#882]
### 操作系统

Linux

### 系统版本

debian12

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
sing-box version unknown
Environment: go1.21.1 linux/amd64
CGO: disabled
```
</details>

### 描述

1. 无法设置`set_system_proxy`, 使用`sing-box run`后命令行错误如下: 
```console
root@ip-172-26-2-111:/usr/local/etc/sing-box# sing-box run
ERROR[0004] origin error: initialize inbound/mixed[mixed-in]: initialize system proxy: unsupported desktop environment
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/sagernet/sing-box.(*Box).Start.func1()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/box.go:207 +0xe9
panic({0xbc5c00?, 0x12eac60?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/sagernet/sing-box/common/settings.(*LinuxSystemProxy).IsEnabled(0x10?)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/common/settings/proxy_linux.go:47
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).Close(0xc000159040)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/inbound/default.go:117 +0x44
github.com/sagernet/sing-box.(*Box).Close(0xc000256c60)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/box.go:299 +0x285
github.com/sagernet/sing-box.(*Box).Start(0xc000256c60)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/box.go:211 +0x1b2
main.create()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/cmd_run.go:153 +0x485
main.run()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/cmd_run.go:166 +0x10d
main.glob..func8(0xc0000ff200?, {0xcbaab2?, 0x4?, 0xcbaab6?})
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/cmd_run.go:28 +0x17
github.com/spf13/cobra.(*Command).execute(0x12f9e40, {0x1330900, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x12fa120)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/main.go:33 +0x1e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: panic on early close: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x49 pc=0x83ce20]

goroutine 1 [running]:
github.com/sagernet/sing-box.(*Box).Start.func1()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/box.go:208 +0x145
panic({0xbc5c00?, 0x12eac60?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/sagernet/sing-box/common/settings.(*LinuxSystemProxy).IsEnabled(0x10?)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/common/settings/proxy_linux.go:47
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).Close(0xc000159040)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/inbound/default.go:117 +0x44
github.com/sagernet/sing-box.(*Box).Close(0xc000256c60)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/box.go:299 +0x285
github.com/sagernet/sing-box.(*Box).Start(0xc000256c60)
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/box.go:211 +0x1b2
main.create()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/cmd_run.go:153 +0x485
main.run()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/cmd_run.go:166 +0x10d
main.glob..func8(0xc0000ff200?, {0xcbaab2?, 0x4?, 0xcbaab6?})
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/cmd_run.go:28 +0x17
github.com/spf13/cobra.(*Command).execute(0x12f9e40, {0x1330900, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x12fa120)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /root/go/pkg/mod/github.com/sagernet/sing-box@v1.4.3/cmd/sing-box/main.go:33 +0x1e
```
2. 无法启用多路复用`smux`, 其余协议未测试, 启动含有多路复用的配置后, 通过`netstat -nltp`, 发现端口并未启用. 删除多路复用并重新启动之后, 发现已经无法使用ssh连接我的linux小主机. 后来执行重装系统之后, 导入不含有多路复用的配置, 发现能够正常工作, 并且重启也正常. 

### 重现方式

含有`set_system_proxy`和多路复用的配置(省略部分信息)
```json
{
  "log": {
    "disabled": false,
    "level": "info",
    "output": "box.log",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "8.8.8.8",
        "detour": "🧊 PROXY"
      },
      {
        "tag": "alibaba",
        "address": "223.5.5.5",
        "detour": "🏹 DIRECT"
      }
    ],
    "rules": [
      {
        "geosite": "cn",
        "server": "alibaba"
      },
      {
        "geosite": "geolocation-!cn",
        "server": "google"
      }
    ],
    "strategy": "ipv4_only",
    "final": "google"
  },
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed-in",
      "listen": "127.0.0.1",
      "listen_port": 5353,
      "set_system_proxy": true
    }
  ],
  "outbounds": [
    {
      "type": "vmess",
      "tag": "vmess-out",
      "server": "",
      "server_port": 443,
      "uuid": "",
      "security": "auto",
      "alter_id": 0,
      "global_padding": false,
      "authenticated_length": true,
      "network": "tcp",
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "",
        "insecure": false,
        "alpn": [
          "h2",
          "http/1.1"
        ]
      },
      "transport": {
        "type": "ws",
        "path": "",
        "headers": {}
      },
      "multiplex": {
        "enabled": true,
        "protocol": "smux",
        "max_connections": 5,
        "min_streams": 4,
        "max_streams": 0
      },
      "connect_timeout": "5s",
      "tcp_fast_open": true,
      "udp_fragment": true
    },
    {
      "type": "direct",
      "tag": "🏹 DIRECT"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns"
    },
    {
      "type": "selector",
      "tag": "🧊 PROXY",
      "outbounds": [
        "vmess-out",
        "🏹 DIRECT"
      ],
      "default": "vmess-out"
    },
    {
      "type": "selector",
      "tag": "🇨🇳 CN",
      "outbounds": [
        "🧊 PROXY",
        "🏹 DIRECT"
      ],
      "default": "🏹 DIRECT"
    },
    {
      "type": "selector",
      "tag": "🇺🇳 WORLD",
      "outbounds": [
        "🧊 PROXY",
        "🏹 DIRECT"
      ],
      "default": "🧊 PROXY"
    },
    {
      "type": "selector",
      "tag": "🍎 APPLE",
      "outbounds": [
        "🧊 PROXY",
        "🏹 DIRECT"
      ],
      "default": "🧊 PROXY"
    },
    {
      "type": "selector",
      "tag": "🔬 MICROSOFT",
      "outbounds": [
        "🧊 PROXY",
        "🏹 DIRECT"
      ],
      "default": "🧊 PROXY"
    },
    {
      "type": "selector",
      "tag": "🎣 FINAL",
      "outbounds": [
        "🧊 PROXY",
        "🏹 DIRECT"
      ],
      "default": "🧊 PROXY"
    }
  ],
  "route": {
    "geosite": {
      "path": "geosite.db",
      "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
      "download_detour": "🧊 PROXY"
    },
    "geoip": {
      "path": "geoip.db",
      "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
      "download_detour": "🧊 PROXY"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "geosite": "apple",
        "outbound": "🍎 APPLE"
      },
      {
        "geosite": "microsoft",
        "outbound": "🔬 MICROSOFT"
      },
      {
        "geosite": "cn",
        "outbound": "🇨🇳 CN"
      },
      {
        "geosite": "geolocation-!cn",
        "outbound": "🇺🇳 WORLD"
      }
    ],
    "final": "🎣 FINAL",
    "auto_detect_interface": true
  }
}
```

### 日志

<details>
```console
# 使用日志内容覆盖此行
```
</details>

**Comment by nekohasekai** [comment]
第一个问题： panic 在最新 commit 已经修复，但仍然不能使用，因为设置系统代理依赖 GNOME 或 KDE。如果您使用其他桌面环境，请自行适配。

第二个问题：您似乎正在运行由第三方程序生成的配置，请将问题发送给它们。
