### ISSUE TITLE
Crashed because of mixed-in inbound

### ISSUE THREAD

**Issue by m0ckinGuY** [SagerNet/sing-box#940]
### Operating system

Linux

### System version

1.5.0

### Installation type

Original sing-box Command Line

### Version

<details>

```
sing-box version 1.5.0

Environment: go1.21.1 linux/amd64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api
Revision: 9c4d08c6e1b57af790e7e7c42294da7439d17e17
CGO: disabled
```

</details>

### Description

I have 4 Shadowsocks+Shadowtls outbound and a selector outbound that can select ss+stls servers via clash api,
Also have 1 Tun interface and 5 socks as inbounds 
Tun and one of the socks is based on url selector and other 4 is bound the specific servers via rule
after upgrading to v1.5.0 the service is restart time to time with the error log provided 

### Logs

<details>

```
Started sing-box service.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcaefdc]
goroutine 11986 [running]:
github.com/sagernet/sing/protocol/socks.HandleConnection0({0x1478ef8, 0xc00527c420}, {0x1480658?, 0xc000294080}, 0x0?, {0x0, 0x0}, {0x7fb2ce7b2c20?, 0xc004ad8000}, {{0x0, ...}, ...})
        pkg/mod/github.com/sagernet/sing@v0.2.12-0.20230925124400-0531fd63eaba/protocol/socks/handshake.go:113 +0x21c
github.com/sagernet/sing-box/inbound.(*Mixed).NewConnection(_, {_, _}, {_, _}, {{0xc000174010, 0xd}, {0x12ac78e, 0x5}, 0x0, ...})
        /Users/sekai/Projects/sing-box/inbound/mixed.go:59 +0x3bb
github.com/sagernet/sing-box/inbound.(*myInboundAdapter).injectTCP(_, {_, _}, {{0xc000174010, 0xd}, {0x12ac78e, 0x5}, 0x0, {0x0, 0x0}, ...})
        /Users/sekai/Projects/sing-box/inbound/default_tcp.go:71 +0x1f8
created by github.com/sagernet/sing-box/inbound.(*myInboundAdapter).loopTCPIn in goroutine 15
        /Users/sekai/Projects/sing-box/inbound/default_tcp.go:63 +0x345

```
</details>

**Comment by nekohasekai** [comment]
Please update to the pre-release version or wait for the new release.
