### ISSUE TITLE
使用FakeIP高频率Panic: unsupported address

### ISSUE THREAD

**Issue by TTT-TD** [SagerNet/sing-box#980]
### 操作系统

Windows

### 系统版本

Windows 11 Microsoft Windows [版本 10.0.22621.1105]

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
sing-box version 1.6.0-beta.1

Environment: go1.21.1 windows/amd64
Tags: with_acme,with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_clash_api,with_gvisor,with_reality_server
Revision: bc4545f2ef41745e5f90c6899e5026845e440f82
CGO: disabled
```
</details>

### 描述

配置中dns部分启用fakeip，且proxy类型为urltest的出站被使用时，高频率出现`panic: unsupported address`，手动选择某个服务器节点目前没有出现该情况

dns部分脱敏配置：
```
"dns":{
    "servers":[
      {
        "tag":"dns-remote",
        "address":"https://dns.cloudflare.com/dns-query",
        "address_resolver":"dns-direct",
        "detour":"proxy"
      },
      {
        "tag":"dns-direct",
        "address":"https://dns.pub/dns-query",
        "address_resolver":"dns-local",
        "detour":"direct"
      },
      {
        "tag":"dns-local",
        "address":"local",
        "detour":"direct"
      },
      {
        "tag":"fakedns",
        "address":"fakeip"
      },
      {
        "tag":"dns-block",
        "address":"rcode://success"
      }
    ],
    "rules":[
      {
        "clash_mode":"direct",
        "server":"dns-direct"
      },
      {
        "domain_suffix":[
          ".cn"
        ],
        "server":"dns-direct"
      },
      {
        "domain_suffix":[
          "cp.cloudflare.com",
          "gstatic.com"
        ],
        "server":"dns-local"
      },
      {
        "clash_mode":"global",
        "server":"dns-remote"
      },
      {
        "geosite":"category-ads-all",
        "server":"dns-block"
      },
      {
        "domain_suffix": [
          "*.arpa",
          "arpa.*"
        ],
        "server": "dns-block"
      },
      {
        "query_type":"A",
        "geosite":[
          "geolocation-!cn",
          "tld-!cn",
          "google",
          "microsoft",
          "bing",
          "openai"
        ],
        "server":"fakedns"
      },
      {
        "geosite":"cn",
        "server":"dns-direct"
      }
    ],
    "fakeip":{
      "enabled":true,
      "inet4_range":"198.18.0.0/15"
    },
    "final":"dns-remote",
    "reverse_mapping": true,
    "disable_cache": false,
    "independent_cache": true,
    "strategy": "ipv4_only"
  }
```

urltest出站配置：
```
{
      "tag":"自动选择",
      "type":"urltest",
      "outbounds":[
        "...",
        "...",
        ".."
      ],
      "url":"https://cp.cloudflare.com",
      "interval":"3m",
      "tolerance":50,
      "interrupt_exist_connections": true
    },
```

### 重现方式

使用urltest出站，刷Youtube，或者访问各种DNS Leak Test类站点，大概率可以复现

### 日志

<details>
```console
panic: unsupported address
goroutine 161942 [running]:
github.com/sagernet/sing/common.Must(...)
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/cond.go:287
github.com/sagernet/sing/common/uot.(*Conn).WriteTo(0xc001613020, {0xc000f84000, 0x4e2, 0x4000}, {0x21a6428?, 0xc002160a50?})
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/uot/conn.go:81 +0x529
github.com/sagernet/sing/common/bufio.(*ExtendedPacketConn).WritePacket(0xc000fd43b0, 0xc0018644e0?, {{{0x0, 0x0}, 0x0}, 0x1bb, {0xc000cea540, 0x11}})
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/bufio/conn.go:66 +0x142
github.com/sagernet/sing/common/bufio.CopyPacketWithPool({0x24ec676adb8?, 0xc0018644e0}, {0x24ec676ad98?, 0xc000fd43b0}, {0x24ec676adb8, 0xc0018644e0}, {0x0, 0x0, 0x1ed75c0?}, {0x0, ...}, ...)
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/bufio/copy.go:344 +0x324
github.com/sagernet/sing/common/bufio.CopyPacket({0x24ec676ad98?, 0xc000fd43b0?}, {0x24ec676adb8, 0xc0018644e0})
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/bufio/copy.go:283 +0x428
github.com/sagernet/sing/common/bufio.CopyPacketConnContextList.func1({0x21a03a0?, 0x0?})
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/bufio/copy.go:400 +0x66
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/task/task.go:68 +0x73
created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 161823
	github.com/sagernet/sing@v0.2.14-0.20231011041941-e4d9384bcd84/common/task/task.go:67 +0x185
```
</details>

**Comment by TTT-TD** [comment]
经群友大佬指点，非普通udp的dns不应该走proxy（不是邪教），目前已修改dns-remote的detour为direct，似乎有所改善，但是依然遇到了一次

**Comment by Toad-stool** [comment]
你urltest的interval是多少？

**Comment by TTT-TD** [comment]
> 你urltest的interval是多少？


```
"interval":"3m",
"tolerance":50
```

**Comment by Toad-stool** [comment]
> > 你urltest的interval是多少？
> 
> ```
> "interval":"3m",
> "tolerance":50
> ```

我感觉应该是跟urltest有关系，我使用过程发现interval越小，panic的频率越高。我开始以为跟urltest的url的解析有关系，我尝试过把url改成IP地址，还是会panic

**Comment by TTT-TD** [comment]
> 我感觉应该是跟urltest有关系，我使用过程发现interval越小，panic的频率越高。我开始以为跟urltest的url的解析有关系，我尝试过把url改成IP地址，还是会panic

是的，世界已经给了bug标签了，等修吧，dns rule部分给outbound any指定了dns的话节点server用域名也是可以解析的，就算不能解析应该也是测速失败或不能上网。也不应该panic，现在情况是用fakeip就不能用urltest只能手动指定outbound，要用urltest就不能用fakeip

**Comment by TTT-TD** [comment]
> 根据不完整的日志，该 panic 跟 uot 有关系，你是否未提及自己使用了 uot？请给出最简可复现的完整配置，以及完整的日志。

我的tuic出站中使用了`"udp_over_stream":true`，是跟这个有关系么？然后日志中确实只有我贴出来的部分

**Comment by TTT-TD** [comment]
> 根据不完整的日志，该 panic 跟 uot 有关系，你是否未提及自己使用了 uot？请给出最简可复现的完整配置，以及完整的日志。

我用`udp_relay_mode`之后到目前确实没出现该问题

**Comment by Toad-stool** [comment]
> > 根据不完整的日志，该 panic 跟 uot 有关系，你是否未提及自己使用了 uot？请给出最简可复现的完整配置，以及完整的日志。
> 
> 我用`udp_relay_mode`之后到目前确实没出现该问题

还真跟这个有关系，我改了之后也正常了。
